// Copyright 2023 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

// Code generated by "stringer"; DO NOT EDIT.

package opt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidRuleName-0]
	_ = x[SimplifyRootOrdering-1]
	_ = x[PruneRootCols-2]
	_ = x[SimplifyZeroCardinalityGroup-3]
	_ = x[NumManualRuleNames-4]
	_ = x[startAutoRule-4]
	_ = x[EliminateAggDistinct-5]
	_ = x[EliminateRedundantBarrier-6]
	_ = x[NormalizeNestedAnds-7]
	_ = x[SimplifyTrueAnd-8]
	_ = x[SimplifyAndTrue-9]
	_ = x[SimplifyFalseAnd-10]
	_ = x[SimplifyAndFalse-11]
	_ = x[SimplifyTrueOr-12]
	_ = x[SimplifyOrTrue-13]
	_ = x[SimplifyFalseOr-14]
	_ = x[SimplifyOrFalse-15]
	_ = x[SimplifyRange-16]
	_ = x[FoldNullAndOr-17]
	_ = x[FoldNotTrue-18]
	_ = x[FoldNotFalse-19]
	_ = x[FoldNotNull-20]
	_ = x[NegateComparison-21]
	_ = x[EliminateNot-22]
	_ = x[NegateAnd-23]
	_ = x[NegateOr-24]
	_ = x[ExtractRedundantConjunct-25]
	_ = x[CommuteVarInequality-26]
	_ = x[CommuteConstInequality-27]
	_ = x[NormalizeCmpPlusConst-28]
	_ = x[NormalizeCmpMinusConst-29]
	_ = x[NormalizeCmpConstMinus-30]
	_ = x[NormalizeTupleEquality-31]
	_ = x[FoldNullComparisonLeft-32]
	_ = x[FoldNullComparisonRight-33]
	_ = x[FoldIsNull-34]
	_ = x[FoldNonNullIsNull-35]
	_ = x[FoldNullTupleIsTupleNull-36]
	_ = x[FoldNonNullTupleIsTupleNull-37]
	_ = x[FoldIsNotNull-38]
	_ = x[FoldNonNullIsNotNull-39]
	_ = x[FoldNonNullTupleIsTupleNotNull-40]
	_ = x[FoldNullTupleIsTupleNotNull-41]
	_ = x[CommuteNullIs-42]
	_ = x[NormalizeCmpTimeZoneFunction-43]
	_ = x[NormalizeCmpTimeZoneFunctionTZ-44]
	_ = x[FoldEqTrue-45]
	_ = x[FoldEqFalse-46]
	_ = x[FoldNeTrue-47]
	_ = x[FoldNeFalse-48]
	_ = x[CollapseRepeatedLikePatternWildcards-49]
	_ = x[ConvertLevenshteinToLevenshteinLessEqualLeft-50]
	_ = x[ConvertLevenshteinToLevenshteinLessEqualRight-51]
	_ = x[NormCycleTestRelTrueToFalse-52]
	_ = x[NormCycleTestRelFalseToTrue-53]
	_ = x[DecorrelateJoin-54]
	_ = x[DecorrelateProjectSet-55]
	_ = x[TryRemapJoinOuterColsRight-56]
	_ = x[TryRemapJoinOuterColsLeft-57]
	_ = x[TryRemapSelectOuterCols-58]
	_ = x[TryDecorrelateSelect-59]
	_ = x[TryDecorrelateProject-60]
	_ = x[TryDecorrelateProjectSelect-61]
	_ = x[TryDecorrelateProjectInnerJoin-62]
	_ = x[TryDecorrelateInnerJoin-63]
	_ = x[TryDecorrelateInnerLeftJoin-64]
	_ = x[HoistSelectAboveUnorderedDistinctOn-65]
	_ = x[TryDecorrelateGroupBy-66]
	_ = x[TryDecorrelateUnion-67]
	_ = x[TryDecorrelateScalarGroupBy-68]
	_ = x[TryDecorrelateSemiJoin-69]
	_ = x[TryDecorrelateLimitOne-70]
	_ = x[TryDecorrelateLimit-71]
	_ = x[TryDecorrelateProjectSet-72]
	_ = x[TryDecorrelateWindow-73]
	_ = x[TryDecorrelateMax1Row-74]
	_ = x[HoistUnboundFilterFromExistsSubquery-75]
	_ = x[HoistUnboundJoinFilterFromExistsSubquery-76]
	_ = x[HoistSelectExists-77]
	_ = x[HoistSelectNotExists-78]
	_ = x[HoistSelectSubquery-79]
	_ = x[HoistProjectSubquery-80]
	_ = x[HoistJoinSubquery-81]
	_ = x[HoistValuesSubquery-82]
	_ = x[HoistProjectSetSubquery-83]
	_ = x[NormalizeSelectAnyFilter-84]
	_ = x[NormalizeJoinAnyFilter-85]
	_ = x[NormalizeSelectNotAnyFilter-86]
	_ = x[NormalizeJoinNotAnyFilter-87]
	_ = x[FoldNullCast-88]
	_ = x[FoldNullUnary-89]
	_ = x[FoldNullBinaryLeft-90]
	_ = x[FoldNullBinaryRight-91]
	_ = x[FoldNullInNonEmpty-92]
	_ = x[FoldInEmpty-93]
	_ = x[FoldNotInEmpty-94]
	_ = x[FoldArray-95]
	_ = x[FoldBinary-96]
	_ = x[FoldUnary-97]
	_ = x[FoldComparisonWithAny-98]
	_ = x[FoldComparison-99]
	_ = x[FoldCast-100]
	_ = x[FoldAssignmentCast-101]
	_ = x[FoldIndirection-102]
	_ = x[FoldColumnAccess-103]
	_ = x[FoldFunctionWithNullArg-104]
	_ = x[FoldFunction-105]
	_ = x[FoldEqualsAnyNull-106]
	_ = x[ConvertGroupByToDistinct-107]
	_ = x[EliminateGroupByProject-108]
	_ = x[EliminateJoinUnderGroupByLeft-109]
	_ = x[EliminateJoinUnderGroupByRight-110]
	_ = x[EliminateDistinct-111]
	_ = x[EliminateUpsertDistinct-112]
	_ = x[EliminateGroupBy-113]
	_ = x[ReduceGroupingCols-114]
	_ = x[ReduceNotNullGroupingCols-115]
	_ = x[EliminateAggDistinctForKeys-116]
	_ = x[EliminateAggFilteredDistinctForKeys-117]
	_ = x[EliminateDistinctNoColumns-118]
	_ = x[EliminateEnsureDistinctNoColumns-119]
	_ = x[EliminateDistinctOnValues-120]
	_ = x[PushAggDistinctIntoGroupBy-121]
	_ = x[PushAggFilterIntoScalarGroupBy-122]
	_ = x[ConvertCountToCountRows-123]
	_ = x[ConvertRegressionCountToCount-124]
	_ = x[FoldGroupingOperators-125]
	_ = x[FoldGroupByAndWindow-126]
	_ = x[InlineConstVar-127]
	_ = x[InlineProjectConstants-128]
	_ = x[InlineSelectConstants-129]
	_ = x[InlineJoinConstantsLeft-130]
	_ = x[InlineJoinConstantsRight-131]
	_ = x[PushSelectIntoInlinableProject-132]
	_ = x[InlineSelectVirtualColumns-133]
	_ = x[InlineProjectInProject-134]
	_ = x[InlineUDF-135]
	_ = x[CommuteRightJoin-136]
	_ = x[SimplifyJoinFilters-137]
	_ = x[DetectJoinContradiction-138]
	_ = x[PushFilterIntoJoinLeftAndRight-139]
	_ = x[MapFilterIntoJoinLeft-140]
	_ = x[MapFilterIntoJoinRight-141]
	_ = x[MapEqualityIntoJoinLeftAndRight-142]
	_ = x[PushFilterIntoJoinLeft-143]
	_ = x[PushFilterIntoJoinRight-144]
	_ = x[SimplifyLeftJoin-145]
	_ = x[SimplifyLeftJoinWithZeroRowsRight-146]
	_ = x[SimplifyRightJoin-147]
	_ = x[EliminateSemiJoin-148]
	_ = x[SimplifyZeroCardinalitySemiJoin-149]
	_ = x[EliminateAntiJoin-150]
	_ = x[SimplifyZeroCardinalityAntiJoin-151]
	_ = x[EliminateJoinNoColsLeft-152]
	_ = x[EliminateJoinNoColsRight-153]
	_ = x[HoistJoinProjectRight-154]
	_ = x[HoistJoinProjectLeft-155]
	_ = x[SimplifyJoinNotNullEquality-156]
	_ = x[ExtractJoinComparisons-157]
	_ = x[SortFiltersInJoin-158]
	_ = x[LeftAssociateJoinsLeft-159]
	_ = x[LeftAssociateJoinsRight-160]
	_ = x[RightAssociateJoinsLeft-161]
	_ = x[RightAssociateJoinsRight-162]
	_ = x[RemoveJoinNotNullCondition-163]
	_ = x[ProjectInnerJoinValues-164]
	_ = x[PushLeakproofJoinIntoPermeableBarrierLeft-165]
	_ = x[PushLeakproofJoinIntoPermeableBarrierRight-166]
	_ = x[EliminateLimit-167]
	_ = x[EliminateOffset-168]
	_ = x[PushLimitIntoProject-169]
	_ = x[PushOffsetIntoProject-170]
	_ = x[PushLimitIntoOffset-171]
	_ = x[PushLimitIntoOrdinality-172]
	_ = x[PushLimitIntoJoinLeft-173]
	_ = x[PushLimitIntoJoinRight-174]
	_ = x[FoldLimits-175]
	_ = x[AssociateLimitJoinsLeft-176]
	_ = x[AssociateLimitJoinsRight-177]
	_ = x[PushLimitIntoLock-178]
	_ = x[PushOffsetIntoLock-179]
	_ = x[EliminateMax1Row-180]
	_ = x[SimplifyPartialIndexProjections-181]
	_ = x[RemoveZeroCardLock-182]
	_ = x[UseSwapMutation-183]
	_ = x[FoldPlusZero-184]
	_ = x[FoldZeroPlus-185]
	_ = x[FoldMinusZero-186]
	_ = x[FoldMultOne-187]
	_ = x[FoldOneMult-188]
	_ = x[FoldDivOne-189]
	_ = x[FoldFloorDivOne-190]
	_ = x[InvertMinus-191]
	_ = x[EliminateUnaryMinus-192]
	_ = x[SimplifyLimitOrdering-193]
	_ = x[SimplifyOffsetOrdering-194]
	_ = x[SimplifyGroupByOrdering-195]
	_ = x[SimplifyOrdinalityOrdering-196]
	_ = x[SimplifyExplainOrdering-197]
	_ = x[SimplifyWithBindingOrdering-198]
	_ = x[EliminateJoinUnderProjectLeft-199]
	_ = x[EliminateJoinUnderProjectRight-200]
	_ = x[EliminateProject-201]
	_ = x[MergeProjects-202]
	_ = x[MergeProjectWithValues-203]
	_ = x[PushColumnRemappingIntoValues-204]
	_ = x[PushAssignmentCastsIntoValues-205]
	_ = x[FoldTupleAccessIntoValues-206]
	_ = x[FoldJSONAccessIntoValues-207]
	_ = x[FoldIsNullProject-208]
	_ = x[PushLeakproofProjectionsIntoPermeableBarrier-209]
	_ = x[EliminateZeroCardProject-210]
	_ = x[ConvertZipArraysToValues-211]
	_ = x[PruneProjectCols-212]
	_ = x[PruneScanCols-213]
	_ = x[PruneSelectCols-214]
	_ = x[PruneLimitCols-215]
	_ = x[PruneOffsetCols-216]
	_ = x[PruneJoinLeftCols-217]
	_ = x[PruneJoinRightCols-218]
	_ = x[PruneSemiAntiJoinRightCols-219]
	_ = x[PruneAggCols-220]
	_ = x[PruneGroupByCols-221]
	_ = x[PruneValuesCols-222]
	_ = x[PruneOrdinalityCols-223]
	_ = x[PruneExplainCols-224]
	_ = x[PruneProjectSetCols-225]
	_ = x[PruneWindowOutputCols-226]
	_ = x[PruneWindowInputCols-227]
	_ = x[PruneMutationFetchCols-228]
	_ = x[PruneMutationInputCols-229]
	_ = x[PruneMutationReturnCols-230]
	_ = x[PruneInsertReturnCols-231]
	_ = x[PruneWithScanCols-232]
	_ = x[PruneWithCols-233]
	_ = x[PruneUnionAllCols-234]
	_ = x[RejectNullsLeftJoin-235]
	_ = x[RejectNullsRightJoin-236]
	_ = x[RejectNullsGroupBy-237]
	_ = x[RejectNullsUnderJoinLeft-238]
	_ = x[RejectNullsUnderJoinRight-239]
	_ = x[RejectNullsProject-240]
	_ = x[CommuteVar-241]
	_ = x[CommuteConst-242]
	_ = x[EliminateCoalesce-243]
	_ = x[SimplifyCoalesce-244]
	_ = x[EliminateCast-245]
	_ = x[InlineAnyWithScanOfValues-246]
	_ = x[NormalizeInConst-247]
	_ = x[FoldInNull-248]
	_ = x[SimplifyInSingleElement-249]
	_ = x[SimplifyNotInSingleElement-250]
	_ = x[UnifyComparisonTypes-251]
	_ = x[EliminateExistsZeroRows-252]
	_ = x[EliminateExistsProject-253]
	_ = x[EliminateExistsGroupBy-254]
	_ = x[InlineExistsSelectTuple-255]
	_ = x[ConvertUncorrelatedExistsToCoalesceSubquery-256]
	_ = x[EliminateExistsLimit-257]
	_ = x[EliminateConstValueSubquery-258]
	_ = x[EliminateUDFCallSubquery-259]
	_ = x[SimplifyCaseWhenConstValue-260]
	_ = x[InlineAnyValuesSingleCol-261]
	_ = x[InlineAnyValuesMultiCol-262]
	_ = x[InlineAnyProjectSet-263]
	_ = x[SimplifyEqualsAnyTuple-264]
	_ = x[SimplifyAnyScalarArray-265]
	_ = x[FoldCollate-266]
	_ = x[NormalizeArrayFlattenToAgg-267]
	_ = x[SimplifySameVarEqualities-268]
	_ = x[SimplifySameVarInequalities-269]
	_ = x[SimplifyNotDisjoint-270]
	_ = x[ConvertJSONSubscriptToFetchValue-271]
	_ = x[ConvertLikeEscapeToLike-272]
	_ = x[SimplifySelectFilters-273]
	_ = x[ConsolidateSelectFilters-274]
	_ = x[DeduplicateSelectFilters-275]
	_ = x[EliminateSelect-276]
	_ = x[MergeSelects-277]
	_ = x[PushSelectIntoProject-278]
	_ = x[PushSelectIntoOrdinality-279]
	_ = x[MergeSelectInnerJoin-280]
	_ = x[PushSelectCondLeftIntoJoinLeftAndRight-281]
	_ = x[PushSelectIntoJoinLeft-282]
	_ = x[PushSelectIntoGroupBy-283]
	_ = x[PushSelectIntoUnorderedDistinctOn-284]
	_ = x[RemoveNotNullCondition-285]
	_ = x[SimplifyIsNullCondition-286]
	_ = x[SimplifyIsCondition-287]
	_ = x[EliminateCaseTrailingFalsyBranch-288]
	_ = x[SimplifyCaseSingleFalsyBranch-289]
	_ = x[SimplifyCaseSingleTruthyBranch-290]
	_ = x[PushSelectIntoProjectSet-291]
	_ = x[PushFilterIntoSetOp-292]
	_ = x[PushLeakproofFiltersIntoPermeableBarrier-293]
	_ = x[NormalizeLikeAny-294]
	_ = x[EliminateZeroCardSelect-295]
	_ = x[EliminateSetLeft-296]
	_ = x[EliminateSetRight-297]
	_ = x[EliminateDistinctSetLeft-298]
	_ = x[EliminateDistinctSetRight-299]
	_ = x[SimplifyExcept-300]
	_ = x[SimplifyIntersectLeft-301]
	_ = x[SimplifyIntersectRight-302]
	_ = x[ConvertUnionToDistinctUnionAll-303]
	_ = x[EliminateWindow-304]
	_ = x[ReduceWindowPartitionCols-305]
	_ = x[SimplifyWindowOrdering-306]
	_ = x[PushSelectIntoWindow-307]
	_ = x[PushLimitIntoWindow-308]
	_ = x[InlineWith-309]
	_ = x[ApplyLimitToRecursiveCTEScan-310]
	_ = x[TryAddLimitToRecursiveBranch-311]
	_ = x[startExploreRule-312]
	_ = x[MemoCycleTestRelRule-313]
	_ = x[MemoCycleTestRelRuleFilter-314]
	_ = x[GenerateParameterizedJoin-315]
	_ = x[ConvertParameterizedLookupJoinToPlaceholderScan-316]
	_ = x[ReplaceScalarMinMaxWithScalarSubqueries-317]
	_ = x[ReplaceFilteredScalarMinMaxWithSubqueries-318]
	_ = x[ReplaceScalarMinMaxWithLimit-319]
	_ = x[ReplaceMinWithLimit-320]
	_ = x[ReplaceMaxWithLimit-321]
	_ = x[GenerateStreamingGroupBy-322]
	_ = x[SplitGroupByScanIntoUnionScans-323]
	_ = x[SplitGroupByFilteredScanIntoUnionScans-324]
	_ = x[EliminateIndexJoinOrProjectInsideGroupBy-325]
	_ = x[GenerateLimitedGroupByScans-326]
	_ = x[InsertFastPath-327]
	_ = x[ReorderJoins-328]
	_ = x[CommuteLeftJoin-329]
	_ = x[CommuteSemiJoin-330]
	_ = x[ConvertSemiToInnerJoin-331]
	_ = x[SplitDisjunctionOfJoinTerms-332]
	_ = x[SplitDisjunctionOfAntiJoinTerms-333]
	_ = x[GenerateMergeJoins-334]
	_ = x[GenerateLookupJoins-335]
	_ = x[GenerateInvertedJoins-336]
	_ = x[GenerateInvertedJoinsFromSelect-337]
	_ = x[GenerateLookupJoinsWithFilter-338]
	_ = x[GenerateLookupJoinsWithVirtualCols-339]
	_ = x[GenerateLookupJoinsWithVirtualColsAndFilter-340]
	_ = x[PushJoinIntoIndexJoin-341]
	_ = x[HoistProjectFromInnerJoin-342]
	_ = x[HoistProjectFromLeftJoin-343]
	_ = x[GenerateLocalityOptimizedAntiJoin-344]
	_ = x[GenerateLocalityOptimizedLookupJoin-345]
	_ = x[GenerateLocalityOptimizedSearchOfLocalityOptimizedJoin-346]
	_ = x[GenerateLocalityOptimizedSearchOfLookupJoins-347]
	_ = x[GenerateLimitedScans-348]
	_ = x[PushLimitIntoFilteredScan-349]
	_ = x[PushLimitIntoProjectFilteredScan-350]
	_ = x[PushLimitIntoIndexJoin-351]
	_ = x[PushOffsetIntoIndexJoin-352]
	_ = x[SplitLimitedScanIntoUnionScans-353]
	_ = x[SplitLimitedSelectIntoUnionSelects-354]
	_ = x[GenerateTopK-355]
	_ = x[GenerateLimitedTopKScans-356]
	_ = x[GeneratePartialOrderTopK-357]
	_ = x[GenerateStreamingGroupByLimitOrderingHint-358]
	_ = x[GenerateVectorSearch-359]
	_ = x[EliminateIndexJoinInsideProject-360]
	_ = x[GenerateIndexScans-361]
	_ = x[GenerateLocalityOptimizedScan-362]
	_ = x[GeneratePartialIndexScans-363]
	_ = x[GenerateConstrainedScans-364]
	_ = x[GenerateInvertedIndexScans-365]
	_ = x[GenerateMinimalInvertedIndexScans-366]
	_ = x[GenerateTrigramSimilarityInvertedIndexScans-367]
	_ = x[GenerateZigzagJoins-368]
	_ = x[GenerateInvertedIndexZigzagJoins-369]
	_ = x[SplitDisjunction-370]
	_ = x[SplitDisjunctionAddKey-371]
	_ = x[GenerateStreamingSetOp-372]
	_ = x[NumRuleNames-373]
}

func (i RuleName) String() string {
	switch i {
	case InvalidRuleName:
		return "InvalidRuleName"
	case SimplifyRootOrdering:
		return "SimplifyRootOrdering"
	case PruneRootCols:
		return "PruneRootCols"
	case SimplifyZeroCardinalityGroup:
		return "SimplifyZeroCardinalityGroup"
	case NumManualRuleNames:
		return "NumManualRuleNames"
	case EliminateAggDistinct:
		return "EliminateAggDistinct"
	case EliminateRedundantBarrier:
		return "EliminateRedundantBarrier"
	case NormalizeNestedAnds:
		return "NormalizeNestedAnds"
	case SimplifyTrueAnd:
		return "SimplifyTrueAnd"
	case SimplifyAndTrue:
		return "SimplifyAndTrue"
	case SimplifyFalseAnd:
		return "SimplifyFalseAnd"
	case SimplifyAndFalse:
		return "SimplifyAndFalse"
	case SimplifyTrueOr:
		return "SimplifyTrueOr"
	case SimplifyOrTrue:
		return "SimplifyOrTrue"
	case SimplifyFalseOr:
		return "SimplifyFalseOr"
	case SimplifyOrFalse:
		return "SimplifyOrFalse"
	case SimplifyRange:
		return "SimplifyRange"
	case FoldNullAndOr:
		return "FoldNullAndOr"
	case FoldNotTrue:
		return "FoldNotTrue"
	case FoldNotFalse:
		return "FoldNotFalse"
	case FoldNotNull:
		return "FoldNotNull"
	case NegateComparison:
		return "NegateComparison"
	case EliminateNot:
		return "EliminateNot"
	case NegateAnd:
		return "NegateAnd"
	case NegateOr:
		return "NegateOr"
	case ExtractRedundantConjunct:
		return "ExtractRedundantConjunct"
	case CommuteVarInequality:
		return "CommuteVarInequality"
	case CommuteConstInequality:
		return "CommuteConstInequality"
	case NormalizeCmpPlusConst:
		return "NormalizeCmpPlusConst"
	case NormalizeCmpMinusConst:
		return "NormalizeCmpMinusConst"
	case NormalizeCmpConstMinus:
		return "NormalizeCmpConstMinus"
	case NormalizeTupleEquality:
		return "NormalizeTupleEquality"
	case FoldNullComparisonLeft:
		return "FoldNullComparisonLeft"
	case FoldNullComparisonRight:
		return "FoldNullComparisonRight"
	case FoldIsNull:
		return "FoldIsNull"
	case FoldNonNullIsNull:
		return "FoldNonNullIsNull"
	case FoldNullTupleIsTupleNull:
		return "FoldNullTupleIsTupleNull"
	case FoldNonNullTupleIsTupleNull:
		return "FoldNonNullTupleIsTupleNull"
	case FoldIsNotNull:
		return "FoldIsNotNull"
	case FoldNonNullIsNotNull:
		return "FoldNonNullIsNotNull"
	case FoldNonNullTupleIsTupleNotNull:
		return "FoldNonNullTupleIsTupleNotNull"
	case FoldNullTupleIsTupleNotNull:
		return "FoldNullTupleIsTupleNotNull"
	case CommuteNullIs:
		return "CommuteNullIs"
	case NormalizeCmpTimeZoneFunction:
		return "NormalizeCmpTimeZoneFunction"
	case NormalizeCmpTimeZoneFunctionTZ:
		return "NormalizeCmpTimeZoneFunctionTZ"
	case FoldEqTrue:
		return "FoldEqTrue"
	case FoldEqFalse:
		return "FoldEqFalse"
	case FoldNeTrue:
		return "FoldNeTrue"
	case FoldNeFalse:
		return "FoldNeFalse"
	case CollapseRepeatedLikePatternWildcards:
		return "CollapseRepeatedLikePatternWildcards"
	case ConvertLevenshteinToLevenshteinLessEqualLeft:
		return "ConvertLevenshteinToLevenshteinLessEqualLeft"
	case ConvertLevenshteinToLevenshteinLessEqualRight:
		return "ConvertLevenshteinToLevenshteinLessEqualRight"
	case NormCycleTestRelTrueToFalse:
		return "NormCycleTestRelTrueToFalse"
	case NormCycleTestRelFalseToTrue:
		return "NormCycleTestRelFalseToTrue"
	case DecorrelateJoin:
		return "DecorrelateJoin"
	case DecorrelateProjectSet:
		return "DecorrelateProjectSet"
	case TryRemapJoinOuterColsRight:
		return "TryRemapJoinOuterColsRight"
	case TryRemapJoinOuterColsLeft:
		return "TryRemapJoinOuterColsLeft"
	case TryRemapSelectOuterCols:
		return "TryRemapSelectOuterCols"
	case TryDecorrelateSelect:
		return "TryDecorrelateSelect"
	case TryDecorrelateProject:
		return "TryDecorrelateProject"
	case TryDecorrelateProjectSelect:
		return "TryDecorrelateProjectSelect"
	case TryDecorrelateProjectInnerJoin:
		return "TryDecorrelateProjectInnerJoin"
	case TryDecorrelateInnerJoin:
		return "TryDecorrelateInnerJoin"
	case TryDecorrelateInnerLeftJoin:
		return "TryDecorrelateInnerLeftJoin"
	case HoistSelectAboveUnorderedDistinctOn:
		return "HoistSelectAboveUnorderedDistinctOn"
	case TryDecorrelateGroupBy:
		return "TryDecorrelateGroupBy"
	case TryDecorrelateUnion:
		return "TryDecorrelateUnion"
	case TryDecorrelateScalarGroupBy:
		return "TryDecorrelateScalarGroupBy"
	case TryDecorrelateSemiJoin:
		return "TryDecorrelateSemiJoin"
	case TryDecorrelateLimitOne:
		return "TryDecorrelateLimitOne"
	case TryDecorrelateLimit:
		return "TryDecorrelateLimit"
	case TryDecorrelateProjectSet:
		return "TryDecorrelateProjectSet"
	case TryDecorrelateWindow:
		return "TryDecorrelateWindow"
	case TryDecorrelateMax1Row:
		return "TryDecorrelateMax1Row"
	case HoistUnboundFilterFromExistsSubquery:
		return "HoistUnboundFilterFromExistsSubquery"
	case HoistUnboundJoinFilterFromExistsSubquery:
		return "HoistUnboundJoinFilterFromExistsSubquery"
	case HoistSelectExists:
		return "HoistSelectExists"
	case HoistSelectNotExists:
		return "HoistSelectNotExists"
	case HoistSelectSubquery:
		return "HoistSelectSubquery"
	case HoistProjectSubquery:
		return "HoistProjectSubquery"
	case HoistJoinSubquery:
		return "HoistJoinSubquery"
	case HoistValuesSubquery:
		return "HoistValuesSubquery"
	case HoistProjectSetSubquery:
		return "HoistProjectSetSubquery"
	case NormalizeSelectAnyFilter:
		return "NormalizeSelectAnyFilter"
	case NormalizeJoinAnyFilter:
		return "NormalizeJoinAnyFilter"
	case NormalizeSelectNotAnyFilter:
		return "NormalizeSelectNotAnyFilter"
	case NormalizeJoinNotAnyFilter:
		return "NormalizeJoinNotAnyFilter"
	case FoldNullCast:
		return "FoldNullCast"
	case FoldNullUnary:
		return "FoldNullUnary"
	case FoldNullBinaryLeft:
		return "FoldNullBinaryLeft"
	case FoldNullBinaryRight:
		return "FoldNullBinaryRight"
	case FoldNullInNonEmpty:
		return "FoldNullInNonEmpty"
	case FoldInEmpty:
		return "FoldInEmpty"
	case FoldNotInEmpty:
		return "FoldNotInEmpty"
	case FoldArray:
		return "FoldArray"
	case FoldBinary:
		return "FoldBinary"
	case FoldUnary:
		return "FoldUnary"
	case FoldComparisonWithAny:
		return "FoldComparisonWithAny"
	case FoldComparison:
		return "FoldComparison"
	case FoldCast:
		return "FoldCast"
	case FoldAssignmentCast:
		return "FoldAssignmentCast"
	case FoldIndirection:
		return "FoldIndirection"
	case FoldColumnAccess:
		return "FoldColumnAccess"
	case FoldFunctionWithNullArg:
		return "FoldFunctionWithNullArg"
	case FoldFunction:
		return "FoldFunction"
	case FoldEqualsAnyNull:
		return "FoldEqualsAnyNull"
	case ConvertGroupByToDistinct:
		return "ConvertGroupByToDistinct"
	case EliminateGroupByProject:
		return "EliminateGroupByProject"
	case EliminateJoinUnderGroupByLeft:
		return "EliminateJoinUnderGroupByLeft"
	case EliminateJoinUnderGroupByRight:
		return "EliminateJoinUnderGroupByRight"
	case EliminateDistinct:
		return "EliminateDistinct"
	case EliminateUpsertDistinct:
		return "EliminateUpsertDistinct"
	case EliminateGroupBy:
		return "EliminateGroupBy"
	case ReduceGroupingCols:
		return "ReduceGroupingCols"
	case ReduceNotNullGroupingCols:
		return "ReduceNotNullGroupingCols"
	case EliminateAggDistinctForKeys:
		return "EliminateAggDistinctForKeys"
	case EliminateAggFilteredDistinctForKeys:
		return "EliminateAggFilteredDistinctForKeys"
	case EliminateDistinctNoColumns:
		return "EliminateDistinctNoColumns"
	case EliminateEnsureDistinctNoColumns:
		return "EliminateEnsureDistinctNoColumns"
	case EliminateDistinctOnValues:
		return "EliminateDistinctOnValues"
	case PushAggDistinctIntoGroupBy:
		return "PushAggDistinctIntoGroupBy"
	case PushAggFilterIntoScalarGroupBy:
		return "PushAggFilterIntoScalarGroupBy"
	case ConvertCountToCountRows:
		return "ConvertCountToCountRows"
	case ConvertRegressionCountToCount:
		return "ConvertRegressionCountToCount"
	case FoldGroupingOperators:
		return "FoldGroupingOperators"
	case FoldGroupByAndWindow:
		return "FoldGroupByAndWindow"
	case InlineConstVar:
		return "InlineConstVar"
	case InlineProjectConstants:
		return "InlineProjectConstants"
	case InlineSelectConstants:
		return "InlineSelectConstants"
	case InlineJoinConstantsLeft:
		return "InlineJoinConstantsLeft"
	case InlineJoinConstantsRight:
		return "InlineJoinConstantsRight"
	case PushSelectIntoInlinableProject:
		return "PushSelectIntoInlinableProject"
	case InlineSelectVirtualColumns:
		return "InlineSelectVirtualColumns"
	case InlineProjectInProject:
		return "InlineProjectInProject"
	case InlineUDF:
		return "InlineUDF"
	case CommuteRightJoin:
		return "CommuteRightJoin"
	case SimplifyJoinFilters:
		return "SimplifyJoinFilters"
	case DetectJoinContradiction:
		return "DetectJoinContradiction"
	case PushFilterIntoJoinLeftAndRight:
		return "PushFilterIntoJoinLeftAndRight"
	case MapFilterIntoJoinLeft:
		return "MapFilterIntoJoinLeft"
	case MapFilterIntoJoinRight:
		return "MapFilterIntoJoinRight"
	case MapEqualityIntoJoinLeftAndRight:
		return "MapEqualityIntoJoinLeftAndRight"
	case PushFilterIntoJoinLeft:
		return "PushFilterIntoJoinLeft"
	case PushFilterIntoJoinRight:
		return "PushFilterIntoJoinRight"
	case SimplifyLeftJoin:
		return "SimplifyLeftJoin"
	case SimplifyLeftJoinWithZeroRowsRight:
		return "SimplifyLeftJoinWithZeroRowsRight"
	case SimplifyRightJoin:
		return "SimplifyRightJoin"
	case EliminateSemiJoin:
		return "EliminateSemiJoin"
	case SimplifyZeroCardinalitySemiJoin:
		return "SimplifyZeroCardinalitySemiJoin"
	case EliminateAntiJoin:
		return "EliminateAntiJoin"
	case SimplifyZeroCardinalityAntiJoin:
		return "SimplifyZeroCardinalityAntiJoin"
	case EliminateJoinNoColsLeft:
		return "EliminateJoinNoColsLeft"
	case EliminateJoinNoColsRight:
		return "EliminateJoinNoColsRight"
	case HoistJoinProjectRight:
		return "HoistJoinProjectRight"
	case HoistJoinProjectLeft:
		return "HoistJoinProjectLeft"
	case SimplifyJoinNotNullEquality:
		return "SimplifyJoinNotNullEquality"
	case ExtractJoinComparisons:
		return "ExtractJoinComparisons"
	case SortFiltersInJoin:
		return "SortFiltersInJoin"
	case LeftAssociateJoinsLeft:
		return "LeftAssociateJoinsLeft"
	case LeftAssociateJoinsRight:
		return "LeftAssociateJoinsRight"
	case RightAssociateJoinsLeft:
		return "RightAssociateJoinsLeft"
	case RightAssociateJoinsRight:
		return "RightAssociateJoinsRight"
	case RemoveJoinNotNullCondition:
		return "RemoveJoinNotNullCondition"
	case ProjectInnerJoinValues:
		return "ProjectInnerJoinValues"
	case PushLeakproofJoinIntoPermeableBarrierLeft:
		return "PushLeakproofJoinIntoPermeableBarrierLeft"
	case PushLeakproofJoinIntoPermeableBarrierRight:
		return "PushLeakproofJoinIntoPermeableBarrierRight"
	case EliminateLimit:
		return "EliminateLimit"
	case EliminateOffset:
		return "EliminateOffset"
	case PushLimitIntoProject:
		return "PushLimitIntoProject"
	case PushOffsetIntoProject:
		return "PushOffsetIntoProject"
	case PushLimitIntoOffset:
		return "PushLimitIntoOffset"
	case PushLimitIntoOrdinality:
		return "PushLimitIntoOrdinality"
	case PushLimitIntoJoinLeft:
		return "PushLimitIntoJoinLeft"
	case PushLimitIntoJoinRight:
		return "PushLimitIntoJoinRight"
	case FoldLimits:
		return "FoldLimits"
	case AssociateLimitJoinsLeft:
		return "AssociateLimitJoinsLeft"
	case AssociateLimitJoinsRight:
		return "AssociateLimitJoinsRight"
	case PushLimitIntoLock:
		return "PushLimitIntoLock"
	case PushOffsetIntoLock:
		return "PushOffsetIntoLock"
	case EliminateMax1Row:
		return "EliminateMax1Row"
	case SimplifyPartialIndexProjections:
		return "SimplifyPartialIndexProjections"
	case RemoveZeroCardLock:
		return "RemoveZeroCardLock"
	case UseSwapMutation:
		return "UseSwapMutation"
	case FoldPlusZero:
		return "FoldPlusZero"
	case FoldZeroPlus:
		return "FoldZeroPlus"
	case FoldMinusZero:
		return "FoldMinusZero"
	case FoldMultOne:
		return "FoldMultOne"
	case FoldOneMult:
		return "FoldOneMult"
	case FoldDivOne:
		return "FoldDivOne"
	case FoldFloorDivOne:
		return "FoldFloorDivOne"
	case InvertMinus:
		return "InvertMinus"
	case EliminateUnaryMinus:
		return "EliminateUnaryMinus"
	case SimplifyLimitOrdering:
		return "SimplifyLimitOrdering"
	case SimplifyOffsetOrdering:
		return "SimplifyOffsetOrdering"
	case SimplifyGroupByOrdering:
		return "SimplifyGroupByOrdering"
	case SimplifyOrdinalityOrdering:
		return "SimplifyOrdinalityOrdering"
	case SimplifyExplainOrdering:
		return "SimplifyExplainOrdering"
	case SimplifyWithBindingOrdering:
		return "SimplifyWithBindingOrdering"
	case EliminateJoinUnderProjectLeft:
		return "EliminateJoinUnderProjectLeft"
	case EliminateJoinUnderProjectRight:
		return "EliminateJoinUnderProjectRight"
	case EliminateProject:
		return "EliminateProject"
	case MergeProjects:
		return "MergeProjects"
	case MergeProjectWithValues:
		return "MergeProjectWithValues"
	case PushColumnRemappingIntoValues:
		return "PushColumnRemappingIntoValues"
	case PushAssignmentCastsIntoValues:
		return "PushAssignmentCastsIntoValues"
	case FoldTupleAccessIntoValues:
		return "FoldTupleAccessIntoValues"
	case FoldJSONAccessIntoValues:
		return "FoldJSONAccessIntoValues"
	case FoldIsNullProject:
		return "FoldIsNullProject"
	case PushLeakproofProjectionsIntoPermeableBarrier:
		return "PushLeakproofProjectionsIntoPermeableBarrier"
	case EliminateZeroCardProject:
		return "EliminateZeroCardProject"
	case ConvertZipArraysToValues:
		return "ConvertZipArraysToValues"
	case PruneProjectCols:
		return "PruneProjectCols"
	case PruneScanCols:
		return "PruneScanCols"
	case PruneSelectCols:
		return "PruneSelectCols"
	case PruneLimitCols:
		return "PruneLimitCols"
	case PruneOffsetCols:
		return "PruneOffsetCols"
	case PruneJoinLeftCols:
		return "PruneJoinLeftCols"
	case PruneJoinRightCols:
		return "PruneJoinRightCols"
	case PruneSemiAntiJoinRightCols:
		return "PruneSemiAntiJoinRightCols"
	case PruneAggCols:
		return "PruneAggCols"
	case PruneGroupByCols:
		return "PruneGroupByCols"
	case PruneValuesCols:
		return "PruneValuesCols"
	case PruneOrdinalityCols:
		return "PruneOrdinalityCols"
	case PruneExplainCols:
		return "PruneExplainCols"
	case PruneProjectSetCols:
		return "PruneProjectSetCols"
	case PruneWindowOutputCols:
		return "PruneWindowOutputCols"
	case PruneWindowInputCols:
		return "PruneWindowInputCols"
	case PruneMutationFetchCols:
		return "PruneMutationFetchCols"
	case PruneMutationInputCols:
		return "PruneMutationInputCols"
	case PruneMutationReturnCols:
		return "PruneMutationReturnCols"
	case PruneInsertReturnCols:
		return "PruneInsertReturnCols"
	case PruneWithScanCols:
		return "PruneWithScanCols"
	case PruneWithCols:
		return "PruneWithCols"
	case PruneUnionAllCols:
		return "PruneUnionAllCols"
	case RejectNullsLeftJoin:
		return "RejectNullsLeftJoin"
	case RejectNullsRightJoin:
		return "RejectNullsRightJoin"
	case RejectNullsGroupBy:
		return "RejectNullsGroupBy"
	case RejectNullsUnderJoinLeft:
		return "RejectNullsUnderJoinLeft"
	case RejectNullsUnderJoinRight:
		return "RejectNullsUnderJoinRight"
	case RejectNullsProject:
		return "RejectNullsProject"
	case CommuteVar:
		return "CommuteVar"
	case CommuteConst:
		return "CommuteConst"
	case EliminateCoalesce:
		return "EliminateCoalesce"
	case SimplifyCoalesce:
		return "SimplifyCoalesce"
	case EliminateCast:
		return "EliminateCast"
	case InlineAnyWithScanOfValues:
		return "InlineAnyWithScanOfValues"
	case NormalizeInConst:
		return "NormalizeInConst"
	case FoldInNull:
		return "FoldInNull"
	case SimplifyInSingleElement:
		return "SimplifyInSingleElement"
	case SimplifyNotInSingleElement:
		return "SimplifyNotInSingleElement"
	case UnifyComparisonTypes:
		return "UnifyComparisonTypes"
	case EliminateExistsZeroRows:
		return "EliminateExistsZeroRows"
	case EliminateExistsProject:
		return "EliminateExistsProject"
	case EliminateExistsGroupBy:
		return "EliminateExistsGroupBy"
	case InlineExistsSelectTuple:
		return "InlineExistsSelectTuple"
	case ConvertUncorrelatedExistsToCoalesceSubquery:
		return "ConvertUncorrelatedExistsToCoalesceSubquery"
	case EliminateExistsLimit:
		return "EliminateExistsLimit"
	case EliminateConstValueSubquery:
		return "EliminateConstValueSubquery"
	case EliminateUDFCallSubquery:
		return "EliminateUDFCallSubquery"
	case SimplifyCaseWhenConstValue:
		return "SimplifyCaseWhenConstValue"
	case InlineAnyValuesSingleCol:
		return "InlineAnyValuesSingleCol"
	case InlineAnyValuesMultiCol:
		return "InlineAnyValuesMultiCol"
	case InlineAnyProjectSet:
		return "InlineAnyProjectSet"
	case SimplifyEqualsAnyTuple:
		return "SimplifyEqualsAnyTuple"
	case SimplifyAnyScalarArray:
		return "SimplifyAnyScalarArray"
	case FoldCollate:
		return "FoldCollate"
	case NormalizeArrayFlattenToAgg:
		return "NormalizeArrayFlattenToAgg"
	case SimplifySameVarEqualities:
		return "SimplifySameVarEqualities"
	case SimplifySameVarInequalities:
		return "SimplifySameVarInequalities"
	case SimplifyNotDisjoint:
		return "SimplifyNotDisjoint"
	case ConvertJSONSubscriptToFetchValue:
		return "ConvertJSONSubscriptToFetchValue"
	case ConvertLikeEscapeToLike:
		return "ConvertLikeEscapeToLike"
	case SimplifySelectFilters:
		return "SimplifySelectFilters"
	case ConsolidateSelectFilters:
		return "ConsolidateSelectFilters"
	case DeduplicateSelectFilters:
		return "DeduplicateSelectFilters"
	case EliminateSelect:
		return "EliminateSelect"
	case MergeSelects:
		return "MergeSelects"
	case PushSelectIntoProject:
		return "PushSelectIntoProject"
	case PushSelectIntoOrdinality:
		return "PushSelectIntoOrdinality"
	case MergeSelectInnerJoin:
		return "MergeSelectInnerJoin"
	case PushSelectCondLeftIntoJoinLeftAndRight:
		return "PushSelectCondLeftIntoJoinLeftAndRight"
	case PushSelectIntoJoinLeft:
		return "PushSelectIntoJoinLeft"
	case PushSelectIntoGroupBy:
		return "PushSelectIntoGroupBy"
	case PushSelectIntoUnorderedDistinctOn:
		return "PushSelectIntoUnorderedDistinctOn"
	case RemoveNotNullCondition:
		return "RemoveNotNullCondition"
	case SimplifyIsNullCondition:
		return "SimplifyIsNullCondition"
	case SimplifyIsCondition:
		return "SimplifyIsCondition"
	case EliminateCaseTrailingFalsyBranch:
		return "EliminateCaseTrailingFalsyBranch"
	case SimplifyCaseSingleFalsyBranch:
		return "SimplifyCaseSingleFalsyBranch"
	case SimplifyCaseSingleTruthyBranch:
		return "SimplifyCaseSingleTruthyBranch"
	case PushSelectIntoProjectSet:
		return "PushSelectIntoProjectSet"
	case PushFilterIntoSetOp:
		return "PushFilterIntoSetOp"
	case PushLeakproofFiltersIntoPermeableBarrier:
		return "PushLeakproofFiltersIntoPermeableBarrier"
	case NormalizeLikeAny:
		return "NormalizeLikeAny"
	case EliminateZeroCardSelect:
		return "EliminateZeroCardSelect"
	case EliminateSetLeft:
		return "EliminateSetLeft"
	case EliminateSetRight:
		return "EliminateSetRight"
	case EliminateDistinctSetLeft:
		return "EliminateDistinctSetLeft"
	case EliminateDistinctSetRight:
		return "EliminateDistinctSetRight"
	case SimplifyExcept:
		return "SimplifyExcept"
	case SimplifyIntersectLeft:
		return "SimplifyIntersectLeft"
	case SimplifyIntersectRight:
		return "SimplifyIntersectRight"
	case ConvertUnionToDistinctUnionAll:
		return "ConvertUnionToDistinctUnionAll"
	case EliminateWindow:
		return "EliminateWindow"
	case ReduceWindowPartitionCols:
		return "ReduceWindowPartitionCols"
	case SimplifyWindowOrdering:
		return "SimplifyWindowOrdering"
	case PushSelectIntoWindow:
		return "PushSelectIntoWindow"
	case PushLimitIntoWindow:
		return "PushLimitIntoWindow"
	case InlineWith:
		return "InlineWith"
	case ApplyLimitToRecursiveCTEScan:
		return "ApplyLimitToRecursiveCTEScan"
	case TryAddLimitToRecursiveBranch:
		return "TryAddLimitToRecursiveBranch"
	case startExploreRule:
		return "startExploreRule"
	case MemoCycleTestRelRule:
		return "MemoCycleTestRelRule"
	case MemoCycleTestRelRuleFilter:
		return "MemoCycleTestRelRuleFilter"
	case GenerateParameterizedJoin:
		return "GenerateParameterizedJoin"
	case ConvertParameterizedLookupJoinToPlaceholderScan:
		return "ConvertParameterizedLookupJoinToPlaceholderScan"
	case ReplaceScalarMinMaxWithScalarSubqueries:
		return "ReplaceScalarMinMaxWithScalarSubqueries"
	case ReplaceFilteredScalarMinMaxWithSubqueries:
		return "ReplaceFilteredScalarMinMaxWithSubqueries"
	case ReplaceScalarMinMaxWithLimit:
		return "ReplaceScalarMinMaxWithLimit"
	case ReplaceMinWithLimit:
		return "ReplaceMinWithLimit"
	case ReplaceMaxWithLimit:
		return "ReplaceMaxWithLimit"
	case GenerateStreamingGroupBy:
		return "GenerateStreamingGroupBy"
	case SplitGroupByScanIntoUnionScans:
		return "SplitGroupByScanIntoUnionScans"
	case SplitGroupByFilteredScanIntoUnionScans:
		return "SplitGroupByFilteredScanIntoUnionScans"
	case EliminateIndexJoinOrProjectInsideGroupBy:
		return "EliminateIndexJoinOrProjectInsideGroupBy"
	case GenerateLimitedGroupByScans:
		return "GenerateLimitedGroupByScans"
	case InsertFastPath:
		return "InsertFastPath"
	case ReorderJoins:
		return "ReorderJoins"
	case CommuteLeftJoin:
		return "CommuteLeftJoin"
	case CommuteSemiJoin:
		return "CommuteSemiJoin"
	case ConvertSemiToInnerJoin:
		return "ConvertSemiToInnerJoin"
	case SplitDisjunctionOfJoinTerms:
		return "SplitDisjunctionOfJoinTerms"
	case SplitDisjunctionOfAntiJoinTerms:
		return "SplitDisjunctionOfAntiJoinTerms"
	case GenerateMergeJoins:
		return "GenerateMergeJoins"
	case GenerateLookupJoins:
		return "GenerateLookupJoins"
	case GenerateInvertedJoins:
		return "GenerateInvertedJoins"
	case GenerateInvertedJoinsFromSelect:
		return "GenerateInvertedJoinsFromSelect"
	case GenerateLookupJoinsWithFilter:
		return "GenerateLookupJoinsWithFilter"
	case GenerateLookupJoinsWithVirtualCols:
		return "GenerateLookupJoinsWithVirtualCols"
	case GenerateLookupJoinsWithVirtualColsAndFilter:
		return "GenerateLookupJoinsWithVirtualColsAndFilter"
	case PushJoinIntoIndexJoin:
		return "PushJoinIntoIndexJoin"
	case HoistProjectFromInnerJoin:
		return "HoistProjectFromInnerJoin"
	case HoistProjectFromLeftJoin:
		return "HoistProjectFromLeftJoin"
	case GenerateLocalityOptimizedAntiJoin:
		return "GenerateLocalityOptimizedAntiJoin"
	case GenerateLocalityOptimizedLookupJoin:
		return "GenerateLocalityOptimizedLookupJoin"
	case GenerateLocalityOptimizedSearchOfLocalityOptimizedJoin:
		return "GenerateLocalityOptimizedSearchOfLocalityOptimizedJoin"
	case GenerateLocalityOptimizedSearchOfLookupJoins:
		return "GenerateLocalityOptimizedSearchOfLookupJoins"
	case GenerateLimitedScans:
		return "GenerateLimitedScans"
	case PushLimitIntoFilteredScan:
		return "PushLimitIntoFilteredScan"
	case PushLimitIntoProjectFilteredScan:
		return "PushLimitIntoProjectFilteredScan"
	case PushLimitIntoIndexJoin:
		return "PushLimitIntoIndexJoin"
	case PushOffsetIntoIndexJoin:
		return "PushOffsetIntoIndexJoin"
	case SplitLimitedScanIntoUnionScans:
		return "SplitLimitedScanIntoUnionScans"
	case SplitLimitedSelectIntoUnionSelects:
		return "SplitLimitedSelectIntoUnionSelects"
	case GenerateTopK:
		return "GenerateTopK"
	case GenerateLimitedTopKScans:
		return "GenerateLimitedTopKScans"
	case GeneratePartialOrderTopK:
		return "GeneratePartialOrderTopK"
	case GenerateStreamingGroupByLimitOrderingHint:
		return "GenerateStreamingGroupByLimitOrderingHint"
	case GenerateVectorSearch:
		return "GenerateVectorSearch"
	case EliminateIndexJoinInsideProject:
		return "EliminateIndexJoinInsideProject"
	case GenerateIndexScans:
		return "GenerateIndexScans"
	case GenerateLocalityOptimizedScan:
		return "GenerateLocalityOptimizedScan"
	case GeneratePartialIndexScans:
		return "GeneratePartialIndexScans"
	case GenerateConstrainedScans:
		return "GenerateConstrainedScans"
	case GenerateInvertedIndexScans:
		return "GenerateInvertedIndexScans"
	case GenerateMinimalInvertedIndexScans:
		return "GenerateMinimalInvertedIndexScans"
	case GenerateTrigramSimilarityInvertedIndexScans:
		return "GenerateTrigramSimilarityInvertedIndexScans"
	case GenerateZigzagJoins:
		return "GenerateZigzagJoins"
	case GenerateInvertedIndexZigzagJoins:
		return "GenerateInvertedIndexZigzagJoins"
	case SplitDisjunction:
		return "SplitDisjunction"
	case SplitDisjunctionAddKey:
		return "SplitDisjunctionAddKey"
	case GenerateStreamingSetOp:
		return "GenerateStreamingSetOp"
	case NumRuleNames:
		return "NumRuleNames"
	default:
		return "RuleName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
