// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server/license/licensepb/license.proto

package licensepb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type License_Type int32

const (
	License_NonCommercial License_Type = 0 // Deprecated: Do not use.
	License_Enterprise    License_Type = 1
	License_Evaluation    License_Type = 2
	License_Free          License_Type = 3
	License_Trial         License_Type = 4
)

var License_Type_name = map[int32]string{
	0: "NonCommercial",
	1: "Enterprise",
	2: "Evaluation",
	3: "Free",
	4: "Trial",
}

var License_Type_value = map[string]int32{
	"NonCommercial": 0,
	"Enterprise":    1,
	"Evaluation":    2,
	"Free":          3,
	"Trial":         4,
}

func (x License_Type) String() string {
	return proto.EnumName(License_Type_name, int32(x))
}

func (License_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_029d3a5acb190b36, []int{0, 0}
}

type License_Environment int32

const (
	Unspecified   License_Environment = 0
	Production    License_Environment = 1
	PreProduction License_Environment = 2
	Development   License_Environment = 3
)

var License_Environment_name = map[int32]string{
	0: "Unspecified",
	1: "Production",
	2: "PreProduction",
	3: "Development",
}

var License_Environment_value = map[string]int32{
	"Unspecified":   0,
	"Production":    1,
	"PreProduction": 2,
	"Development":   3,
}

func (License_Environment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_029d3a5acb190b36, []int{0, 1}
}

type License struct {
	ValidUntilUnixSec int64               `protobuf:"varint,2,opt,name=valid_until_unix_sec,json=validUntilUnixSec,proto3" json:"valid_until_unix_sec,omitempty"`
	Type              License_Type        `protobuf:"varint,3,opt,name=type,proto3,enum=cockroach.ccl.utilccl.licenseccl.License_Type" json:"type,omitempty"`
	OrganizationName  string              `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Environment       License_Environment `protobuf:"varint,5,opt,name=environment,proto3,enum=cockroach.ccl.utilccl.licenseccl.License_Environment" json:"environment,omitempty"`
	// Two UUIDs uniquely identify this license and the associated organization.
	// They are stored as bytes to align with the server's typical usage. We
	// avoided using the custom UUID type normally used in protobufs to minimize
	// dependencies, as the generated code is also used in other repositories.
	LicenseId      []byte `protobuf:"bytes,6,opt,name=license_id,json=licenseId,proto3" json:"license_id,omitempty"`
	OrganizationId []byte `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
}

func (m *License) Reset()         { *m = License{} }
func (m *License) String() string { return proto.CompactTextString(m) }
func (*License) ProtoMessage()    {}
func (*License) Descriptor() ([]byte, []int) {
	return fileDescriptor_029d3a5acb190b36, []int{0}
}
func (m *License) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *License) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *License) XXX_Merge(src proto.Message) {
	xxx_messageInfo_License.Merge(m, src)
}
func (m *License) XXX_Size() int {
	return m.Size()
}
func (m *License) XXX_DiscardUnknown() {
	xxx_messageInfo_License.DiscardUnknown(m)
}

var xxx_messageInfo_License proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.ccl.utilccl.licenseccl.License_Type", License_Type_name, License_Type_value)
	proto.RegisterEnum("cockroach.ccl.utilccl.licenseccl.License_Environment", License_Environment_name, License_Environment_value)
	proto.RegisterType((*License)(nil), "cockroach.ccl.utilccl.licenseccl.License")
}

func init() {
	proto.RegisterFile("server/license/licensepb/license.proto", fileDescriptor_029d3a5acb190b36)
}

var fileDescriptor_029d3a5acb190b36 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x6b, 0xd4, 0x5c,
	0x14, 0xc6, 0x73, 0x33, 0x69, 0x3b, 0x73, 0xe6, 0xed, 0x34, 0x73, 0xe9, 0x0b, 0x61, 0xc0, 0x4b,
	0x98, 0x85, 0x0e, 0x08, 0x09, 0x28, 0x2e, 0xdd, 0x54, 0x2b, 0x54, 0xa4, 0x94, 0xd8, 0x41, 0x10,
	0x21, 0x64, 0x6e, 0x8e, 0xe9, 0xa5, 0xc9, 0xbd, 0xe1, 0xe6, 0x0f, 0xad, 0x6b, 0x17, 0x2e, 0xfd,
	0x0e, 0xba, 0xf0, 0xa3, 0x74, 0xd9, 0x65, 0x97, 0x3a, 0xf3, 0x45, 0x24, 0x99, 0xa9, 0x8d, 0x0b,
	0xd1, 0xd5, 0x39, 0x39, 0xe7, 0xf9, 0x3d, 0xe7, 0xe4, 0x72, 0xe0, 0x7e, 0x81, 0xba, 0x46, 0xed,
	0xa7, 0x82, 0xa3, 0x2c, 0xf0, 0x36, 0xe6, 0x8b, 0xdb, 0xcc, 0xcb, 0xb5, 0x2a, 0x15, 0x75, 0xb9,
	0xe2, 0xe7, 0x5a, 0x45, 0xfc, 0xcc, 0xe3, 0x3c, 0xf5, 0xaa, 0x52, 0xa4, 0x4d, 0xdc, 0x88, 0x38,
	0x4f, 0x27, 0xfb, 0x89, 0x4a, 0x54, 0x2b, 0xf6, 0x9b, 0x6c, 0xcd, 0x4d, 0x3f, 0x5a, 0xb0, 0xf3,
	0x6a, 0x2d, 0xa2, 0x3e, 0xec, 0xd7, 0x51, 0x2a, 0xe2, 0xb0, 0x92, 0xa5, 0x48, 0xc3, 0x4a, 0x8a,
	0x8b, 0xb0, 0x40, 0xee, 0x98, 0x2e, 0x99, 0xf5, 0x82, 0x71, 0xdb, 0x9b, 0x37, 0xad, 0xb9, 0x14,
	0x17, 0xaf, 0x91, 0xd3, 0x03, 0xb0, 0xca, 0xcb, 0x1c, 0x9d, 0x9e, 0x4b, 0x66, 0xa3, 0x47, 0x9e,
	0xf7, 0xb7, 0x1d, 0xbc, 0xcd, 0x24, 0xef, 0xf4, 0x32, 0xc7, 0xa0, 0x65, 0xe9, 0x43, 0x18, 0x2b,
	0x9d, 0x44, 0x52, 0x7c, 0x88, 0x4a, 0xa1, 0x64, 0x28, 0xa3, 0x0c, 0x1d, 0xcb, 0x25, 0xb3, 0x41,
	0x60, 0x77, 0x1b, 0xc7, 0x51, 0x86, 0xf4, 0x0d, 0x0c, 0x51, 0xd6, 0x42, 0x2b, 0x99, 0xa1, 0x2c,
	0x9d, 0xad, 0x76, 0xee, 0x93, 0x7f, 0x9f, 0x7b, 0x78, 0x07, 0x07, 0x5d, 0x27, 0x7a, 0x0f, 0x60,
	0x23, 0x0f, 0x45, 0xec, 0x6c, 0xbb, 0x64, 0xf6, 0x5f, 0x30, 0xd8, 0x54, 0x8e, 0x62, 0xfa, 0x00,
	0xf6, 0x7e, 0x5b, 0x52, 0xc4, 0xce, 0x4e, 0xab, 0x19, 0x75, 0xcb, 0x47, 0xf1, 0x34, 0x00, 0xab,
	0xf9, 0x37, 0xfa, 0x3f, 0xec, 0x1e, 0x2b, 0xf9, 0x4c, 0x65, 0x19, 0x6a, 0x2e, 0xa2, 0xd4, 0x36,
	0x26, 0x66, 0x9f, 0xd0, 0x11, 0xc0, 0xa1, 0x2c, 0x51, 0xe7, 0x5a, 0x14, 0x68, 0xaf, 0xbf, 0xeb,
	0x28, 0xad, 0x5a, 0xdc, 0x36, 0x69, 0x1f, 0xac, 0x17, 0x1a, 0xd1, 0xee, 0xd1, 0x01, 0x6c, 0x9d,
	0xea, 0x06, 0xb4, 0xa6, 0xef, 0x60, 0xd8, 0xd9, 0x9b, 0xee, 0xc1, 0x70, 0x2e, 0x8b, 0x1c, 0xb9,
	0x78, 0x2f, 0x30, 0xb6, 0x8d, 0xc6, 0xe4, 0x44, 0xab, 0xb8, 0xe2, 0xad, 0x09, 0xa1, 0x63, 0xd8,
	0x3d, 0xd1, 0xd8, 0x29, 0x99, 0x0d, 0xf3, 0x1c, 0x6b, 0x4c, 0x55, 0xde, 0x58, 0xd8, 0xbd, 0x49,
	0xff, 0xd3, 0x17, 0x66, 0x7c, 0xfb, 0xca, 0x8c, 0x97, 0x56, 0x9f, 0xd8, 0xe6, 0x41, 0x78, 0xf5,
	0x83, 0x19, 0x57, 0x4b, 0x46, 0xae, 0x97, 0x8c, 0xdc, 0x2c, 0x19, 0xf9, 0xbe, 0x64, 0xe4, 0xf3,
	0x8a, 0x19, 0xd7, 0x2b, 0x66, 0xdc, 0xac, 0x98, 0xf1, 0xf6, 0x69, 0x22, 0xca, 0xb3, 0x6a, 0xe1,
	0x71, 0x95, 0xf9, 0xbf, 0xde, 0x3b, 0x5e, 0xdc, 0xe5, 0x7e, 0x7e, 0x9e, 0xf8, 0x7f, 0xba, 0xd6,
	0xc5, 0x76, 0x7b, 0x6e, 0x8f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x25, 0xbe, 0x75, 0xac, 0xd0,
	0x02, 0x00, 0x00,
}

func (m *License) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *License) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *License) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OrganizationId) > 0 {
		i -= len(m.OrganizationId)
		copy(dAtA[i:], m.OrganizationId)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.OrganizationId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.LicenseId) > 0 {
		i -= len(m.LicenseId)
		copy(dAtA[i:], m.LicenseId)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.LicenseId)))
		i--
		dAtA[i] = 0x32
	}
	if m.Environment != 0 {
		i = encodeVarintLicense(dAtA, i, uint64(m.Environment))
		i--
		dAtA[i] = 0x28
	}
	if len(m.OrganizationName) > 0 {
		i -= len(m.OrganizationName)
		copy(dAtA[i:], m.OrganizationName)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.OrganizationName)))
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintLicense(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.ValidUntilUnixSec != 0 {
		i = encodeVarintLicense(dAtA, i, uint64(m.ValidUntilUnixSec))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func encodeVarintLicense(dAtA []byte, offset int, v uint64) int {
	offset -= sovLicense(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *License) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidUntilUnixSec != 0 {
		n += 1 + sovLicense(uint64(m.ValidUntilUnixSec))
	}
	if m.Type != 0 {
		n += 1 + sovLicense(uint64(m.Type))
	}
	l = len(m.OrganizationName)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	if m.Environment != 0 {
		n += 1 + sovLicense(uint64(m.Environment))
	}
	l = len(m.LicenseId)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	l = len(m.OrganizationId)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	return n
}

func sovLicense(x uint64) (n int) {
	return int((uint32(math_bits.Len64(x|1)+6) * 37) >> 8)
}
func sozLicense(x uint64) (n int) {
	return sovLicense(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *License) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLicense
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: License: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: License: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntilUnixSec", wireType)
			}
			m.ValidUntilUnixSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidUntilUnixSec |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= License_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrganizationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrganizationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Environment", wireType)
			}
			m.Environment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Environment |= License_Environment(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LicenseId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LicenseId = append(m.LicenseId[:0], dAtA[iNdEx:postIndex]...)
			if m.LicenseId == nil {
				m.LicenseId = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrganizationId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrganizationId = append(m.OrganizationId[:0], dAtA[iNdEx:postIndex]...)
			if m.OrganizationId == nil {
				m.OrganizationId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLicense(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLicense
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLicense(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLicense
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLicense
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLicense
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLicense
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLicense        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLicense          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLicense = fmt.Errorf("proto: unexpected end of group")
)

