// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/log/eventpb/bulk_ingest_perf.proto

package eventpb

import (
	fmt "fmt"
	logpb "github.com/cockroachdb/cockroach/pkg/util/log/logpb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BulkIngestCompleted is an event that is logged when a bulk ingest job
// (restore, import, etc.) completes successfully.
// It captures key performance metrics for the operation.
type BulkIngestCompleted struct {
	// Common fields for all events.
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	// JobID is the ID of the bulk ingest job.
	JobID uint64 `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:",omitempty"`
	// JobType identifies the type of bulk ingest job (e.g., "restore", "import").
	JobType string `protobuf:"bytes,3,opt,name=job_type,json=jobType,proto3" json:",omitempty" redact:"nonsensitive"`
	// NumRows is the number of rows successfully ingested.
	NumRows int64 `protobuf:"varint,4,opt,name=num_rows,json=numRows,proto3" json:",omitempty"`
	// Duration of the ingest operation in seconds.
	DurationSeconds int64 `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:",omitempty"`
	// Total logical size of data ingested in megabytes.
	DataSizeMb int64 `protobuf:"varint,6,opt,name=data_size_mb,json=dataSizeMb,proto3" json:",omitempty"`
	// Number of nodes that participated in the ingest operation.
	NodeCount int32 `protobuf:"varint,7,opt,name=node_count,json=nodeCount,proto3" json:",omitempty"`
}

func (m *BulkIngestCompleted) Reset()         { *m = BulkIngestCompleted{} }
func (m *BulkIngestCompleted) String() string { return proto.CompactTextString(m) }
func (*BulkIngestCompleted) ProtoMessage()    {}
func (*BulkIngestCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_f58e13bd77947b7c, []int{0}
}
func (m *BulkIngestCompleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BulkIngestCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BulkIngestCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkIngestCompleted.Merge(m, src)
}
func (m *BulkIngestCompleted) XXX_Size() int {
	return m.Size()
}
func (m *BulkIngestCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkIngestCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_BulkIngestCompleted proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BulkIngestCompleted)(nil), "cockroach.util.log.eventpb.BulkIngestCompleted")
}

func init() {
	proto.RegisterFile("util/log/eventpb/bulk_ingest_perf.proto", fileDescriptor_f58e13bd77947b7c)
}

var fileDescriptor_f58e13bd77947b7c = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0xb1, 0x6e, 0xd3, 0x40,
	0x18, 0x07, 0x70, 0x1f, 0x69, 0x92, 0xf6, 0xa8, 0x00, 0x19, 0x10, 0x56, 0x06, 0xdb, 0xca, 0x40,
	0x8d, 0x04, 0x36, 0x02, 0x31, 0xc0, 0xe8, 0x94, 0x21, 0x08, 0x96, 0x14, 0x09, 0x89, 0xc5, 0xf2,
	0xf9, 0x0e, 0xf7, 0x12, 0xdf, 0x7d, 0x27, 0xdf, 0xb9, 0x55, 0xfa, 0x14, 0x3c, 0x01, 0xcf, 0x93,
	0x31, 0x63, 0x27, 0x0b, 0x9c, 0xad, 0x23, 0x4f, 0x80, 0x9c, 0x94, 0x22, 0xd2, 0x6c, 0x9f, 0x74,
	0xbf, 0xff, 0xf7, 0x1f, 0xee, 0xc3, 0x47, 0x95, 0xe1, 0x45, 0x54, 0x40, 0x1e, 0xb1, 0x33, 0x26,
	0x8d, 0x22, 0x11, 0xa9, 0x8a, 0x59, 0xc2, 0x65, 0xce, 0xb4, 0x49, 0x14, 0x2b, 0xbf, 0x85, 0xaa,
	0x04, 0x03, 0xf6, 0x20, 0x83, 0x6c, 0x56, 0x42, 0x9a, 0x9d, 0x86, 0x6d, 0x24, 0x2c, 0x20, 0x0f,
	0xaf, 0x23, 0x83, 0x47, 0x39, 0xe4, 0xb0, 0x66, 0x51, 0x3b, 0x6d, 0x12, 0x83, 0xc1, 0xcd, 0xea,
	0x02, 0x72, 0x45, 0x36, 0x05, 0x9b, 0xb7, 0xe1, 0x8f, 0x0e, 0x7e, 0x18, 0x57, 0xc5, 0x6c, 0xbc,
	0xee, 0x19, 0x81, 0x50, 0x05, 0x33, 0x8c, 0xda, 0x1f, 0x71, 0x2f, 0x03, 0x21, 0x40, 0x3a, 0xc8,
	0x47, 0xc1, 0xdd, 0x57, 0x4f, 0xc3, 0x1d, 0xb5, 0xa3, 0xb5, 0x78, 0xdf, 0xae, 0x3b, 0x66, 0x26,
	0xe5, 0x85, 0x8e, 0x0f, 0x17, 0xb5, 0x67, 0x2d, 0x6b, 0x0f, 0x5d, 0xd5, 0x9e, 0x35, 0xb9, 0xde,
	0x61, 0x87, 0xb8, 0x37, 0x05, 0x92, 0x70, 0xea, 0xdc, 0xf1, 0x51, 0xb0, 0x17, 0x3f, 0x69, 0x6a,
	0xaf, 0xfb, 0x01, 0xc8, 0xf8, 0xf8, 0xaa, 0xf6, 0xf0, 0x73, 0x10, 0xdc, 0x30, 0xa1, 0xcc, 0x7c,
	0xd2, 0x9d, 0x02, 0x19, 0x53, 0x3b, 0xc6, 0xfb, 0xad, 0x37, 0x73, 0xc5, 0x9c, 0x8e, 0x8f, 0x82,
	0x83, 0xf8, 0xe8, 0x7f, 0xf8, 0xbb, 0xf6, 0x1e, 0x97, 0x8c, 0xa6, 0x99, 0x79, 0x37, 0x94, 0x20,
	0x35, 0x93, 0x9a, 0x1b, 0x7e, 0xc6, 0x86, 0x93, 0xfe, 0x14, 0xc8, 0xe7, 0xb9, 0x62, 0xf6, 0x33,
	0xbc, 0x2f, 0x2b, 0x91, 0x94, 0x70, 0xae, 0x9d, 0x3d, 0x1f, 0x05, 0x9d, 0xf8, 0xde, 0x56, 0x59,
	0x5f, 0x56, 0x62, 0x02, 0xe7, 0xda, 0x7e, 0x8b, 0x1f, 0xd0, 0xaa, 0x4c, 0x0d, 0x07, 0x99, 0x68,
	0x96, 0x81, 0xa4, 0xda, 0xe9, 0xee, 0x8c, 0xdc, 0xff, 0xeb, 0x4e, 0x36, 0xcc, 0x7e, 0x89, 0x0f,
	0x69, 0x6a, 0xd2, 0x44, 0xf3, 0x0b, 0x96, 0x08, 0xe2, 0xf4, 0x76, 0xc6, 0x70, 0x6b, 0x4e, 0xf8,
	0x05, 0xfb, 0x44, 0xec, 0x17, 0x18, 0x4b, 0xa0, 0x2c, 0xc9, 0xa0, 0x92, 0xc6, 0xe9, 0xfb, 0x28,
	0xe8, 0xde, 0xf2, 0x07, 0xad, 0x18, 0xb5, 0x20, 0xfe, 0xb2, 0xf8, 0xe5, 0x5a, 0x8b, 0xc6, 0x45,
	0xcb, 0xc6, 0x45, 0x97, 0x8d, 0x8b, 0x7e, 0x36, 0x2e, 0xfa, 0xbe, 0x72, 0xad, 0xe5, 0xca, 0xb5,
	0x2e, 0x57, 0xae, 0xf5, 0xf5, 0x4d, 0xce, 0xcd, 0x69, 0x45, 0xc2, 0x0c, 0x44, 0x74, 0xf3, 0x49,
	0x94, 0xfc, 0x9b, 0x23, 0x35, 0xcb, 0xa3, 0xed, 0xf3, 0x22, 0xbd, 0xf5, 0x01, 0xbc, 0xfe, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xaf, 0x3a, 0xc9, 0xca, 0x79, 0x02, 0x00, 0x00,
}

func (m *BulkIngestCompleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BulkIngestCompleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BulkIngestCompleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NodeCount != 0 {
		i = encodeVarintBulkIngestPerf(dAtA, i, uint64(m.NodeCount))
		i--
		dAtA[i] = 0x38
	}
	if m.DataSizeMb != 0 {
		i = encodeVarintBulkIngestPerf(dAtA, i, uint64(m.DataSizeMb))
		i--
		dAtA[i] = 0x30
	}
	if m.DurationSeconds != 0 {
		i = encodeVarintBulkIngestPerf(dAtA, i, uint64(m.DurationSeconds))
		i--
		dAtA[i] = 0x28
	}
	if m.NumRows != 0 {
		i = encodeVarintBulkIngestPerf(dAtA, i, uint64(m.NumRows))
		i--
		dAtA[i] = 0x20
	}
	if len(m.JobType) > 0 {
		i -= len(m.JobType)
		copy(dAtA[i:], m.JobType)
		i = encodeVarintBulkIngestPerf(dAtA, i, uint64(len(m.JobType)))
		i--
		dAtA[i] = 0x1a
	}
	if m.JobID != 0 {
		i = encodeVarintBulkIngestPerf(dAtA, i, uint64(m.JobID))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBulkIngestPerf(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintBulkIngestPerf(dAtA []byte, offset int, v uint64) int {
	offset -= sovBulkIngestPerf(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BulkIngestCompleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovBulkIngestPerf(uint64(l))
	if m.JobID != 0 {
		n += 1 + sovBulkIngestPerf(uint64(m.JobID))
	}
	l = len(m.JobType)
	if l > 0 {
		n += 1 + l + sovBulkIngestPerf(uint64(l))
	}
	if m.NumRows != 0 {
		n += 1 + sovBulkIngestPerf(uint64(m.NumRows))
	}
	if m.DurationSeconds != 0 {
		n += 1 + sovBulkIngestPerf(uint64(m.DurationSeconds))
	}
	if m.DataSizeMb != 0 {
		n += 1 + sovBulkIngestPerf(uint64(m.DataSizeMb))
	}
	if m.NodeCount != 0 {
		n += 1 + sovBulkIngestPerf(uint64(m.NodeCount))
	}
	return n
}

func sovBulkIngestPerf(x uint64) (n int) {
	return int((uint32(math_bits.Len64(x|1)+6) * 37) >> 8)
}
func sozBulkIngestPerf(x uint64) (n int) {
	return sovBulkIngestPerf(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BulkIngestCompleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBulkIngestPerf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BulkIngestCompleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BulkIngestCompleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBulkIngestPerf
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBulkIngestPerf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobID", wireType)
			}
			m.JobID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBulkIngestPerf
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBulkIngestPerf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumRows", wireType)
			}
			m.NumRows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumRows |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationSeconds", wireType)
			}
			m.DurationSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DurationSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataSizeMb", wireType)
			}
			m.DataSizeMb = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DataSizeMb |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeCount", wireType)
			}
			m.NodeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBulkIngestPerf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBulkIngestPerf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBulkIngestPerf(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBulkIngestPerf
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBulkIngestPerf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBulkIngestPerf
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBulkIngestPerf
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBulkIngestPerf
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBulkIngestPerf        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBulkIngestPerf          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBulkIngestPerf = fmt.Errorf("proto: unexpected end of group")
)

