// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sql/bulksst/sst_info.proto

package bulksst

import (
	fmt "fmt"
	github_com_cockroachdb_cockroach_pkg_roachpb "github.com/cockroachdb/cockroach/pkg/roachpb"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SSTFileInfo struct {
	URI       string                                           `protobuf:"bytes,1,req,name=uri" json:"uri"`
	StartKey  github_com_cockroachdb_cockroach_pkg_roachpb.Key `protobuf:"bytes,2,req,name=start_key,json=startKey,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.Key" json:"start_key,omitempty"`
	EndKey    github_com_cockroachdb_cockroach_pkg_roachpb.Key `protobuf:"bytes,3,req,name=end_key,json=endKey,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.Key" json:"end_key,omitempty"`
	FileSize  uint64                                           `protobuf:"varint,4,req,name=file_size,json=fileSize" json:"file_size"`
	RowSample github_com_cockroachdb_cockroach_pkg_roachpb.Key `protobuf:"bytes,5,opt,name=row_sample,json=rowSample,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.Key" json:"row_sample,omitempty"`
	KeyCount  uint64                                           `protobuf:"varint,6,opt,name=key_count,json=keyCount" json:"key_count"`
}

func (m *SSTFileInfo) Reset()         { *m = SSTFileInfo{} }
func (m *SSTFileInfo) String() string { return proto.CompactTextString(m) }
func (*SSTFileInfo) ProtoMessage()    {}
func (*SSTFileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4107bc8f88e2797a, []int{0}
}
func (m *SSTFileInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SSTFileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SSTFileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSTFileInfo.Merge(m, src)
}
func (m *SSTFileInfo) XXX_Size() int {
	return m.Size()
}
func (m *SSTFileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SSTFileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SSTFileInfo proto.InternalMessageInfo

type SSTFiles struct {
	SST        []*SSTFileInfo `protobuf:"bytes,1,rep,name=sst" json:"sst,omitempty"`
	RowSamples []string       `protobuf:"bytes,2,rep,name=row_samples,json=rowSamples" json:"row_samples,omitempty"`
	TotalSize  uint64         `protobuf:"varint,3,req,name=total_size,json=totalSize" json:"total_size"`
}

func (m *SSTFiles) Reset()         { *m = SSTFiles{} }
func (m *SSTFiles) String() string { return proto.CompactTextString(m) }
func (*SSTFiles) ProtoMessage()    {}
func (*SSTFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_4107bc8f88e2797a, []int{1}
}
func (m *SSTFiles) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SSTFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SSTFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSTFiles.Merge(m, src)
}
func (m *SSTFiles) XXX_Size() int {
	return m.Size()
}
func (m *SSTFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_SSTFiles.DiscardUnknown(m)
}

var xxx_messageInfo_SSTFiles proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SSTFileInfo)(nil), "cockroach.sql.bulksst.SSTFileInfo")
	proto.RegisterType((*SSTFiles)(nil), "cockroach.sql.bulksst.SSTFiles")
}

func init() { proto.RegisterFile("sql/bulksst/sst_info.proto", fileDescriptor_4107bc8f88e2797a) }

var fileDescriptor_4107bc8f88e2797a = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xb1, 0xcf, 0x9a, 0x40,
	0x1c, 0xe5, 0xc0, 0xaa, 0x1c, 0x9d, 0x2e, 0x6d, 0x42, 0x4c, 0x7a, 0x50, 0xbb, 0x30, 0x41, 0xd3,
	0x74, 0xed, 0x42, 0x93, 0x26, 0xc6, 0x74, 0x28, 0xd8, 0xa5, 0x0b, 0x01, 0x3c, 0x91, 0x80, 0x1c,
	0x72, 0x47, 0x0c, 0xfe, 0x13, 0xed, 0x9f, 0xe5, 0xe8, 0xe8, 0x64, 0x5a, 0x9c, 0xfa, 0x2f, 0x74,
	0x6a, 0x0e, 0x8d, 0x3a, 0x7c, 0xc3, 0x97, 0xef, 0xdb, 0x5e, 0x5e, 0x1e, 0xef, 0xf1, 0x7b, 0xef,
	0xe0, 0x88, 0xad, 0x73, 0x27, 0xaa, 0xf3, 0x8c, 0x31, 0xee, 0x30, 0xc6, 0x83, 0xb4, 0x58, 0x50,
	0xbb, 0xac, 0x28, 0xa7, 0xe8, 0x75, 0x4c, 0xe3, 0xac, 0xa2, 0x61, 0xbc, 0xb4, 0xd9, 0x3a, 0xb7,
	0x2f, 0xaa, 0xd1, 0xab, 0x84, 0x26, 0xb4, 0x53, 0x38, 0x02, 0x9d, 0xc5, 0xe3, 0xbf, 0x32, 0xd4,
	0x7c, 0x7f, 0xf6, 0x25, 0xcd, 0xc9, 0xa4, 0x58, 0x50, 0xf4, 0x06, 0x2a, 0x75, 0x95, 0xea, 0xc0,
	0x94, 0x2d, 0xd5, 0xd5, 0x76, 0x47, 0x43, 0x6a, 0x8f, 0x86, 0xf2, 0xdd, 0x9b, 0x78, 0x82, 0x47,
	0xdf, 0xa0, 0xca, 0x78, 0x58, 0xf1, 0x20, 0x23, 0x8d, 0x2e, 0x9b, 0xb2, 0xf5, 0xd2, 0xfd, 0xf8,
	0xef, 0x68, 0xbc, 0x4f, 0x52, 0xbe, 0xac, 0x23, 0x3b, 0xa6, 0x2b, 0xe7, 0x9a, 0x3e, 0x8f, 0x6e,
	0xd8, 0x29, 0xb3, 0xc4, 0xe9, 0x50, 0x19, 0xd9, 0x53, 0xd2, 0x78, 0xc3, 0xce, 0x66, 0x4a, 0x1a,
	0xf4, 0x15, 0x0e, 0x48, 0x31, 0xef, 0x0c, 0x95, 0x67, 0x18, 0xf6, 0x49, 0x31, 0x17, 0x76, 0x6f,
	0xa1, 0xba, 0x48, 0x73, 0x12, 0xb0, 0x74, 0x4b, 0xf4, 0x9e, 0x29, 0x5b, 0x3d, 0xb7, 0x27, 0xce,
	0xf0, 0x86, 0x82, 0xf6, 0xd3, 0x2d, 0x41, 0x3e, 0x84, 0x15, 0xdd, 0x04, 0x2c, 0x5c, 0x95, 0x39,
	0xd1, 0x5f, 0x98, 0xe0, 0xc9, 0xa1, 0x6a, 0x45, 0x37, 0x7e, 0x67, 0x23, 0x72, 0x33, 0xd2, 0x04,
	0x31, 0xad, 0x0b, 0xae, 0xf7, 0x4d, 0x70, 0xcb, 0xcd, 0x48, 0xf3, 0x59, 0xb0, 0xe3, 0x9f, 0x00,
	0x0e, 0x2f, 0x5d, 0x33, 0xf4, 0x09, 0x2a, 0x8c, 0x71, 0x1d, 0x98, 0x8a, 0xa5, 0x7d, 0x18, 0xdb,
	0x0f, 0x6e, 0x66, 0xdf, 0x2d, 0xe3, 0x0e, 0xc4, 0x10, 0xbe, 0x3f, 0xf3, 0xc4, 0x77, 0xc8, 0x80,
	0xda, 0xed, 0x06, 0xa6, 0xcb, 0xa6, 0x62, 0xa9, 0x1e, 0xbc, 0xfe, 0x0e, 0x43, 0xef, 0x20, 0xe4,
	0x94, 0x87, 0xf9, 0xb9, 0x08, 0xe5, 0xae, 0x08, 0xb5, 0xe3, 0x45, 0x13, 0xae, 0xb7, 0xfb, 0x83,
	0xa5, 0x5d, 0x8b, 0xc1, 0xbe, 0xc5, 0xe0, 0xd0, 0x62, 0xf0, 0xbb, 0xc5, 0xe0, 0xd7, 0x09, 0x4b,
	0xfb, 0x13, 0x96, 0x0e, 0x27, 0x2c, 0xfd, 0x78, 0x5c, 0x27, 0x77, 0xaf, 0xf1, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe8, 0xe0, 0x95, 0x36, 0x9b, 0x02, 0x00, 0x00,
}

func (m *SSTFileInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SSTFileInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SSTFileInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintSstInfo(dAtA, i, uint64(m.KeyCount))
	i--
	dAtA[i] = 0x30
	if m.RowSample != nil {
		i -= len(m.RowSample)
		copy(dAtA[i:], m.RowSample)
		i = encodeVarintSstInfo(dAtA, i, uint64(len(m.RowSample)))
		i--
		dAtA[i] = 0x2a
	}
	i = encodeVarintSstInfo(dAtA, i, uint64(m.FileSize))
	i--
	dAtA[i] = 0x20
	if m.EndKey == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("end_key")
	} else {
		i -= len(m.EndKey)
		copy(dAtA[i:], m.EndKey)
		i = encodeVarintSstInfo(dAtA, i, uint64(len(m.EndKey)))
		i--
		dAtA[i] = 0x1a
	}
	if m.StartKey == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("start_key")
	} else {
		i -= len(m.StartKey)
		copy(dAtA[i:], m.StartKey)
		i = encodeVarintSstInfo(dAtA, i, uint64(len(m.StartKey)))
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.URI)
	copy(dAtA[i:], m.URI)
	i = encodeVarintSstInfo(dAtA, i, uint64(len(m.URI)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *SSTFiles) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SSTFiles) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SSTFiles) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintSstInfo(dAtA, i, uint64(m.TotalSize))
	i--
	dAtA[i] = 0x18
	if len(m.RowSamples) > 0 {
		for iNdEx := len(m.RowSamples) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RowSamples[iNdEx])
			copy(dAtA[i:], m.RowSamples[iNdEx])
			i = encodeVarintSstInfo(dAtA, i, uint64(len(m.RowSamples[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SST) > 0 {
		for iNdEx := len(m.SST) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SST[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSstInfo(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintSstInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovSstInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SSTFileInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.URI)
	n += 1 + l + sovSstInfo(uint64(l))
	if m.StartKey != nil {
		l = len(m.StartKey)
		n += 1 + l + sovSstInfo(uint64(l))
	}
	if m.EndKey != nil {
		l = len(m.EndKey)
		n += 1 + l + sovSstInfo(uint64(l))
	}
	n += 1 + sovSstInfo(uint64(m.FileSize))
	if m.RowSample != nil {
		l = len(m.RowSample)
		n += 1 + l + sovSstInfo(uint64(l))
	}
	n += 1 + sovSstInfo(uint64(m.KeyCount))
	return n
}

func (m *SSTFiles) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SST) > 0 {
		for _, e := range m.SST {
			l = e.Size()
			n += 1 + l + sovSstInfo(uint64(l))
		}
	}
	if len(m.RowSamples) > 0 {
		for _, s := range m.RowSamples {
			l = len(s)
			n += 1 + l + sovSstInfo(uint64(l))
		}
	}
	n += 1 + sovSstInfo(uint64(m.TotalSize))
	return n
}

func sovSstInfo(x uint64) (n int) {
	return int((uint32(math_bits.Len64(x|1)+6) * 37) >> 8)
}
func sozSstInfo(x uint64) (n int) {
	return sovSstInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SSTFileInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSstInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SSTFileInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SSTFileInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSstInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSstInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSstInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSstInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartKey = append(m.StartKey[:0], dAtA[iNdEx:postIndex]...)
			if m.StartKey == nil {
				m.StartKey = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSstInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSstInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndKey = append(m.EndKey[:0], dAtA[iNdEx:postIndex]...)
			if m.EndKey == nil {
				m.EndKey = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowSample", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSstInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSstInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RowSample = append(m.RowSample[:0], dAtA[iNdEx:postIndex]...)
			if m.RowSample == nil {
				m.RowSample = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyCount", wireType)
			}
			m.KeyCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSstInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSstInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("uri")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("start_key")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("end_key")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("file_size")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SSTFiles) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSstInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SSTFiles: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SSTFiles: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SST", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSstInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSstInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SST = append(m.SST, &SSTFileInfo{})
			if err := m.SST[len(m.SST)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowSamples", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSstInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSstInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RowSamples = append(m.RowSamples, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSize", wireType)
			}
			m.TotalSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipSstInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSstInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("total_size")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSstInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSstInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSstInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSstInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSstInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSstInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSstInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSstInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSstInfo = fmt.Errorf("proto: unexpected end of group")
)

