// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kv/kvserver/kvstorage/wag/wagpb/wag.proto

package wagpb

import (
	fmt "fmt"
	github_com_cockroachdb_cockroach_pkg_kv_kvpb "github.com/cockroachdb/cockroach/pkg/kv/kvpb"
	kvserverpb "github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvserverpb"
	github_com_cockroachdb_cockroach_pkg_roachpb "github.com/cockroachdb/cockroach/pkg/roachpb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventType identifies the type of a replica lifecycle event within a WAG node.
type EventType int32

const (
	// EventUnknown is the zero value. It should not be used.
	EventUnknown EventType = 0
	// EventCreate corresponds to the creation of an uninitialized replica. All
	// replicas on a Store go through this transition. The Addr index must be 0,
	// as there is no log to speak of.
	EventCreate EventType = 1
	// EventInit corresponds to initializing a replica's state machine at a
	// specific raft index. This happens when an uninitialized replica receives a
	// snapshot, or when a split creates the RHS. The Addr index is the index at
	// which the replica is initialized.
	EventInit EventType = 2
	// EventApply corresponds to applying a replica's raft log up to a specific
	// committed index. The Addr index identifies the log prefix that has been
	// applied.
	EventApply EventType = 3
	// EventSplit corresponds to applying a split command on a replica. The Addr
	// index is the raft log index of the split command. Implies a dependency on
	// the replica being caught up to index-1 before the split.
	EventSplit EventType = 4
	// EventMerge corresponds to the LHS applying a merge command. The Addr index
	// is the raft log index of the merge command. Implies a dependency on the LHS
	// being caught up to index-1 before the merge.
	EventMerge EventType = 5
	// EventSubsume corresponds to a replica being subsumed as part of a merge.
	// The Addr index is the replica's last applied index before subsumption.
	// Implies a dependency on the replica being caught up to that index. The
	// post-subsumption state of the replica is "destroyed".
	EventSubsume EventType = 6
	// EventDestroy corresponds to a destruction of a replica. The Addr index is
	// the replica's last applied index before destruction, and it implies a
	// dependency on the replica being caught up to that index. The
	// post-destruction state of the replica is "destroyed".
	EventDestroy EventType = 7
)

var EventType_name = map[int32]string{
	0: "EventUnknown",
	1: "EventCreate",
	2: "EventInit",
	3: "EventApply",
	4: "EventSplit",
	5: "EventMerge",
	6: "EventSubsume",
	7: "EventDestroy",
}

var EventType_value = map[string]int32{
	"EventUnknown": 0,
	"EventCreate":  1,
	"EventInit":    2,
	"EventApply":   3,
	"EventSplit":   4,
	"EventMerge":   5,
	"EventSubsume": 6,
	"EventDestroy": 7,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_350f0ec898a3233e, []int{0}
}

// Event describes a single replica lifecycle event within a WAG node.
type Event struct {
	// Addr identifies the range, replica and raft index this event pertains to.
	// The interpretation of the Raft Index depends on the EventType.
	Addr Addr `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr"`
	// Type identifies the kind of lifecycle event.
	Type EventType `protobuf:"varint,2,opt,name=type,proto3,enum=wagpb.EventType" json:"type,omitempty"`
	// StartKey is the range's start key at the time of the event. It allows
	// replay to load the range descriptor via a point read rather than scanning
	// all descriptors. Empty only for EventCreate (uninitialized replicas have
	// no descriptor yet).
	StartKey github_com_cockroachdb_cockroach_pkg_roachpb.RKey `protobuf:"bytes,3,opt,name=start_key,json=startKey,proto3,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.RKey" json:"start_key,omitempty"`
}

func (m *Event) Reset()      { *m = Event{} }
func (*Event) ProtoMessage() {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_350f0ec898a3233e, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

// Addr describes the full address of a WAG event, consisting of RangeID,
// ReplicaID, and index into the raft log.
//
// It establishes "happens before" relationships between WAG events of a
// RangeID. For example, when applying an event with Addr.ReplicaID, we know
// that all events with lower ReplicaIDs (including their destruction), or same
// ReplicaID and lower Index have been applied.
type Addr struct {
	// RangeID is the ID of the range that the event pertains to.
	RangeID github_com_cockroachdb_cockroach_pkg_roachpb.RangeID `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.RangeID" json:"range_id,omitempty"`
	// ReplicaID is the ID of the RangeID replica that the event pertains to.
	ReplicaID github_com_cockroachdb_cockroach_pkg_roachpb.ReplicaID `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.ReplicaID" json:"replica_id,omitempty"`
	// Index identifies the raft log entry associated with this event. Its
	// interpretation depends on the EventType:
	//  - EventCreate: 0, signifying an uninitialized replica.
	//  - EventInit: the index at which the replica is initialized.
	//  - EventApply: the log index identifying a prefix of the raft log.
	//  - EventSplit, EventMerge: the raft log index of the split/merge command.
	//  - EventSubsume, EventDestroy: the replica's last applied index before
	//    removal.
	Index github_com_cockroachdb_cockroach_pkg_kv_kvpb.RaftIndex `protobuf:"varint,4,opt,name=index,proto3,casttype=github.com/cockroachdb/cockroach/pkg/kv/kvpb.RaftIndex" json:"index,omitempty"`
}

func (m *Addr) Reset()      { *m = Addr{} }
func (*Addr) ProtoMessage() {}
func (*Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_350f0ec898a3233e, []int{1}
}
func (m *Addr) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addr.Merge(m, src)
}
func (m *Addr) XXX_Size() int {
	return m.Size()
}
func (m *Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_Addr.DiscardUnknown(m)
}

var xxx_messageInfo_Addr proto.InternalMessageInfo

// Node describes a node of the WAG. A node represents an atomic state machine
// mutation along with one or more replica lifecycle events it encompasses. For
// example, a split node contains an Init event for the newly created RHS and
// a Split event that both initializes the RHS and narrows the LHS.
type Node struct {
	// Events contains the replica lifecycle events that this node encompasses.
	// Each event affects a single replica, identified by its Addr. A given
	// RangeID must appear at most once in this list.
	//
	// Each EventType implicitly carries dependency semantics. For example, a
	// Split event at raft index I implies the replica must be caught up to I-1
	// before the split can be replayed.
	Events []Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events"`
	// Mutation contains the mutation that will be applied to the state machine
	// engine when applying this WAG node.
	Mutation Mutation `protobuf:"bytes,2,opt,name=mutation,proto3" json:"mutation"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_350f0ec898a3233e, []int{2}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return m.Size()
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

// Mutation contains a mutation that can be applied to the state machine engine.
// It can be represented by an encoded Pebble write batch or SSTable ingestion.
type Mutation struct {
	// Batch contains an encoded Pebble write batch.
	Batch []byte `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	// Ingestion contains a Pebble ingestion.
	Ingestion *Ingestion `protobuf:"bytes,2,opt,name=ingestion,proto3" json:"ingestion,omitempty"`
}

func (m *Mutation) Reset()         { *m = Mutation{} }
func (m *Mutation) String() string { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()    {}
func (*Mutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_350f0ec898a3233e, []int{3}
}
func (m *Mutation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Mutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Mutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mutation.Merge(m, src)
}
func (m *Mutation) XXX_Size() int {
	return m.Size()
}
func (m *Mutation) XXX_DiscardUnknown() {
	xxx_messageInfo_Mutation.DiscardUnknown(m)
}

var xxx_messageInfo_Mutation proto.InternalMessageInfo

// Ingestion describes a Pebble ingestion.
type Ingestion struct {
	SSTs           []string                                   `protobuf:"bytes,1,rep,name=SSTs,proto3" json:"SSTs,omitempty"`
	SharedTables   []kvserverpb.SnapshotRequest_SharedTable   `protobuf:"bytes,2,rep,name=shared_tables,json=sharedTables,proto3" json:"shared_tables"`
	ExternalTables []kvserverpb.SnapshotRequest_ExternalTable `protobuf:"bytes,3,rep,name=external_tables,json=externalTables,proto3" json:"external_tables"`
}

func (m *Ingestion) Reset()         { *m = Ingestion{} }
func (m *Ingestion) String() string { return proto.CompactTextString(m) }
func (*Ingestion) ProtoMessage()    {}
func (*Ingestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_350f0ec898a3233e, []int{4}
}
func (m *Ingestion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ingestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Ingestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingestion.Merge(m, src)
}
func (m *Ingestion) XXX_Size() int {
	return m.Size()
}
func (m *Ingestion) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingestion.DiscardUnknown(m)
}

var xxx_messageInfo_Ingestion proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("wagpb.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Event)(nil), "wagpb.Event")
	proto.RegisterType((*Addr)(nil), "wagpb.Addr")
	proto.RegisterType((*Node)(nil), "wagpb.Node")
	proto.RegisterType((*Mutation)(nil), "wagpb.Mutation")
	proto.RegisterType((*Ingestion)(nil), "wagpb.Ingestion")
}

func init() {
	proto.RegisterFile("kv/kvserver/kvstorage/wag/wagpb/wag.proto", fileDescriptor_350f0ec898a3233e)
}

var fileDescriptor_350f0ec898a3233e = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xd6, 0xda, 0x72, 0x62, 0xaf, 0x9d, 0x44, 0x2c, 0x39, 0x98, 0x1c, 0x64, 0xd7, 0xb4, 0xe0,
	0xe6, 0x20, 0x13, 0xf7, 0xe7, 0x10, 0x28, 0x25, 0x4e, 0x42, 0x31, 0x21, 0x25, 0xac, 0xd3, 0x4b,
	0x0f, 0x0d, 0x2b, 0x6b, 0x2c, 0x0b, 0x39, 0x92, 0xba, 0x5a, 0x3b, 0xd1, 0x1b, 0xf4, 0xd8, 0x5b,
	0x7b, 0x2c, 0x14, 0x7a, 0xec, 0x73, 0xe4, 0x98, 0x63, 0x4e, 0xa6, 0x75, 0x9e, 0xa2, 0x39, 0x15,
	0xad, 0x64, 0xd9, 0x14, 0x0a, 0xc9, 0xc1, 0x66, 0xe6, 0x9b, 0xd9, 0xef, 0x9b, 0xd9, 0x19, 0x2d,
	0x7e, 0xea, 0x4e, 0x5a, 0xee, 0x24, 0x04, 0x3e, 0x01, 0x1e, 0x1b, 0xc2, 0xe7, 0xcc, 0x86, 0xd6,
	0x05, 0xb3, 0xe3, 0x5f, 0x60, 0xc6, 0xff, 0x46, 0xc0, 0x7d, 0xe1, 0x93, 0x82, 0x04, 0xb6, 0x36,
	0x6d, 0xdf, 0xf6, 0x25, 0xd2, 0x8a, 0xad, 0x24, 0xb8, 0xf5, 0xe8, 0x1f, 0x1e, 0x69, 0x04, 0x66,
	0x8b, 0xb3, 0x81, 0x48, 0x52, 0x1a, 0x3f, 0x11, 0x2e, 0x1c, 0x4e, 0xc0, 0x13, 0xe4, 0x09, 0x56,
	0x99, 0x65, 0xf1, 0x2a, 0xaa, 0xa3, 0x66, 0xb9, 0x5d, 0x36, 0x24, 0xb1, 0xb1, 0x67, 0x59, 0xbc,
	0xa3, 0x5e, 0x4d, 0x6b, 0x0a, 0x95, 0x61, 0xf2, 0x18, 0xab, 0x22, 0x0a, 0xa0, 0x9a, 0xab, 0xa3,
	0xe6, 0x7a, 0x5b, 0x4b, 0xd3, 0x24, 0xc5, 0x69, 0x14, 0x00, 0x95, 0x51, 0x42, 0x71, 0x29, 0x14,
	0x8c, 0x8b, 0x33, 0x17, 0xa2, 0x6a, 0xbe, 0x8e, 0x9a, 0x95, 0xce, 0x8b, 0xbb, 0x69, 0x6d, 0xc7,
	0x76, 0xc4, 0x70, 0x6c, 0x1a, 0x7d, 0xff, 0xbc, 0xd5, 0xf7, 0xfb, 0x2e, 0xf7, 0x59, 0x7f, 0x68,
	0x99, 0x0b, 0xbb, 0x15, 0xb8, 0x76, 0x4b, 0x5a, 0x81, 0x69, 0xd0, 0x23, 0x88, 0x68, 0x51, 0xf2,
	0x1c, 0x41, 0xb4, 0xab, 0x7e, 0xfd, 0x56, 0x53, 0x1a, 0x3f, 0x72, 0x58, 0x8d, 0x8b, 0x22, 0x1f,
	0x70, 0x91, 0x33, 0xcf, 0x86, 0x33, 0xc7, 0x92, 0x35, 0xe7, 0x3b, 0xfb, 0xb3, 0x69, 0x6d, 0x95,
	0xc6, 0x58, 0xf7, 0xe0, 0x6e, 0x5a, 0x7b, 0xfe, 0x30, 0xb1, 0xe4, 0x1c, 0x5d, 0x95, 0xa4, 0x5d,
	0x8b, 0x0c, 0x30, 0xe6, 0x10, 0x8c, 0x9c, 0x3e, 0x8b, 0x15, 0xe2, 0x76, 0x0b, 0x9d, 0x37, 0xb3,
	0x69, 0xad, 0x44, 0x13, 0x54, 0x6a, 0xbc, 0x7c, 0x98, 0xc6, 0xfc, 0x24, 0x2d, 0xa5, 0xd4, 0x5d,
	0x8b, 0x9c, 0xe0, 0x82, 0xe3, 0x59, 0x70, 0x59, 0x55, 0xeb, 0xa8, 0xa9, 0x76, 0x76, 0xef, 0xcd,
	0x2a, 0x87, 0x2b, 0x2b, 0x1f, 0x88, 0x6e, 0xcc, 0x40, 0x13, 0xa2, 0xf4, 0xa2, 0x00, 0xab, 0x6f,
	0x7d, 0x0b, 0xc8, 0x36, 0x5e, 0x81, 0x78, 0x3a, 0x61, 0x15, 0xd5, 0xf3, 0xcd, 0x72, 0xbb, 0xb2,
	0x3c, 0xb2, 0x74, 0xb4, 0x69, 0x06, 0xd9, 0xc1, 0xc5, 0xf3, 0xb1, 0x60, 0xc2, 0xf1, 0x3d, 0xd9,
	0x71, 0xb9, 0xbd, 0x91, 0x66, 0x1f, 0xa7, 0x70, 0x7a, 0x20, 0x4b, 0x6b, 0x9c, 0xe0, 0xe2, 0x3c,
	0x46, 0x36, 0x71, 0xc1, 0x64, 0xa2, 0x3f, 0x94, 0xf3, 0xa8, 0xd0, 0xc4, 0x21, 0x06, 0x2e, 0x39,
	0x9e, 0x0d, 0xe1, 0x12, 0xeb, 0x7c, 0x6d, 0xba, 0x73, 0x9c, 0x2e, 0x52, 0x1a, 0x7f, 0x10, 0x2e,
	0x65, 0x01, 0x42, 0xb0, 0xda, 0xeb, 0x9d, 0x26, 0xc5, 0x97, 0xa8, 0xb4, 0xc9, 0x10, 0xaf, 0x85,
	0x43, 0xc6, 0xc1, 0x3a, 0x13, 0xcc, 0x1c, 0x41, 0x58, 0xcd, 0xc9, 0xce, 0x5e, 0x19, 0xd9, 0x05,
	0x19, 0xee, 0xc4, 0x98, 0x2f, 0xbc, 0xb1, 0xd8, 0x7c, 0xa3, 0xe7, 0xb1, 0x20, 0x1c, 0xfa, 0x82,
	0xc2, 0xc7, 0x31, 0x84, 0xc2, 0xe8, 0x49, 0x9a, 0xd3, 0x98, 0x25, 0xed, 0xac, 0x12, 0x2e, 0xa0,
	0x90, 0x78, 0x78, 0x03, 0x2e, 0x05, 0x70, 0x8f, 0x8d, 0xe6, 0x5a, 0x79, 0xa9, 0xf5, 0xfa, 0xe1,
	0x5a, 0x87, 0x29, 0xd1, 0xb2, 0xda, 0x3a, 0x2c, 0x83, 0xe1, 0xf6, 0x17, 0x84, 0x4b, 0xd9, 0xb7,
	0x44, 0x34, 0x5c, 0x91, 0xce, 0x3b, 0xcf, 0xf5, 0xfc, 0x0b, 0x4f, 0x53, 0xc8, 0x06, 0x2e, 0x4b,
	0x64, 0x9f, 0x03, 0x13, 0xa0, 0x21, 0xb2, 0x96, 0xe6, 0x77, 0x3d, 0x47, 0x68, 0x39, 0xb2, 0x8e,
	0xb1, 0x74, 0xf7, 0x82, 0x60, 0x14, 0x69, 0xf9, 0xcc, 0xef, 0x05, 0x23, 0x47, 0x68, 0x6a, 0xe6,
	0x1f, 0x03, 0xb7, 0x41, 0x2b, 0x64, 0x0a, 0xbd, 0xb1, 0x19, 0x8e, 0xcf, 0x41, 0x5b, 0xc9, 0x90,
	0x03, 0x08, 0x05, 0xf7, 0x23, 0x6d, 0x75, 0x4b, 0xfd, 0xf4, 0x5d, 0x57, 0x3a, 0x83, 0xab, 0xdf,
	0xba, 0x72, 0x35, 0xd3, 0xd1, 0xf5, 0x4c, 0x47, 0x37, 0x33, 0x1d, 0xfd, 0x9a, 0xe9, 0xe8, 0xf3,
	0xad, 0xae, 0x5c, 0xdf, 0xea, 0xca, 0xcd, 0xad, 0xae, 0xbc, 0x3f, 0xb8, 0xff, 0xd6, 0xfe, 0xff,
	0x69, 0x33, 0x57, 0xe4, 0xbb, 0xf4, 0xec, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x20, 0x58,
	0xbb, 0x04, 0x05, 0x00, 0x00,
}

func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StartKey) > 0 {
		i -= len(m.StartKey)
		copy(dAtA[i:], m.StartKey)
		i = encodeVarintWag(dAtA, i, uint64(len(m.StartKey)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintWag(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Addr.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWag(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Addr) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Addr) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Addr) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintWag(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	if m.ReplicaID != 0 {
		i = encodeVarintWag(dAtA, i, uint64(m.ReplicaID))
		i--
		dAtA[i] = 0x10
	}
	if m.RangeID != 0 {
		i = encodeVarintWag(dAtA, i, uint64(m.RangeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Node) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Node) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Node) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Mutation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWag(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Events) > 0 {
		for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWag(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Mutation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Mutation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Mutation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Ingestion != nil {
		{
			size, err := m.Ingestion.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWag(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Batch) > 0 {
		i -= len(m.Batch)
		copy(dAtA[i:], m.Batch)
		i = encodeVarintWag(dAtA, i, uint64(len(m.Batch)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Ingestion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ingestion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ingestion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExternalTables) > 0 {
		for iNdEx := len(m.ExternalTables) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ExternalTables[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWag(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.SharedTables) > 0 {
		for iNdEx := len(m.SharedTables) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SharedTables[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWag(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SSTs) > 0 {
		for iNdEx := len(m.SSTs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SSTs[iNdEx])
			copy(dAtA[i:], m.SSTs[iNdEx])
			i = encodeVarintWag(dAtA, i, uint64(len(m.SSTs[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintWag(dAtA []byte, offset int, v uint64) int {
	offset -= sovWag(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Addr.Size()
	n += 1 + l + sovWag(uint64(l))
	if m.Type != 0 {
		n += 1 + sovWag(uint64(m.Type))
	}
	l = len(m.StartKey)
	if l > 0 {
		n += 1 + l + sovWag(uint64(l))
	}
	return n
}

func (m *Addr) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RangeID != 0 {
		n += 1 + sovWag(uint64(m.RangeID))
	}
	if m.ReplicaID != 0 {
		n += 1 + sovWag(uint64(m.ReplicaID))
	}
	if m.Index != 0 {
		n += 1 + sovWag(uint64(m.Index))
	}
	return n
}

func (m *Node) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovWag(uint64(l))
		}
	}
	l = m.Mutation.Size()
	n += 1 + l + sovWag(uint64(l))
	return n
}

func (m *Mutation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Batch)
	if l > 0 {
		n += 1 + l + sovWag(uint64(l))
	}
	if m.Ingestion != nil {
		l = m.Ingestion.Size()
		n += 1 + l + sovWag(uint64(l))
	}
	return n
}

func (m *Ingestion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SSTs) > 0 {
		for _, s := range m.SSTs {
			l = len(s)
			n += 1 + l + sovWag(uint64(l))
		}
	}
	if len(m.SharedTables) > 0 {
		for _, e := range m.SharedTables {
			l = e.Size()
			n += 1 + l + sovWag(uint64(l))
		}
	}
	if len(m.ExternalTables) > 0 {
		for _, e := range m.ExternalTables {
			l = e.Size()
			n += 1 + l + sovWag(uint64(l))
		}
	}
	return n
}

func sovWag(x uint64) (n int) {
	return int((uint32(math_bits.Len64(x|1)+6) * 37) >> 8)
}
func sozWag(x uint64) (n int) {
	return sovWag(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Addr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= EventType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartKey = append(m.StartKey[:0], dAtA[iNdEx:postIndex]...)
			if m.StartKey == nil {
				m.StartKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Addr) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Addr: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Addr: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RangeID", wireType)
			}
			m.RangeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RangeID |= github_com_cockroachdb_cockroach_pkg_roachpb.RangeID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicaID", wireType)
			}
			m.ReplicaID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplicaID |= github_com_cockroachdb_cockroach_pkg_roachpb.ReplicaID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= github_com_cockroachdb_cockroach_pkg_kv_kvpb.RaftIndex(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Node) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Node: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Node: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, Event{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mutation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Mutation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Mutation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Mutation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Mutation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Batch", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Batch = append(m.Batch[:0], dAtA[iNdEx:postIndex]...)
			if m.Batch == nil {
				m.Batch = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ingestion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ingestion == nil {
				m.Ingestion = &Ingestion{}
			}
			if err := m.Ingestion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ingestion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ingestion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ingestion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SSTs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SSTs = append(m.SSTs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SharedTables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SharedTables = append(m.SharedTables, kvserverpb.SnapshotRequest_SharedTable{})
			if err := m.SharedTables[len(m.SharedTables)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExternalTables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExternalTables = append(m.ExternalTables, kvserverpb.SnapshotRequest_ExternalTable{})
			if err := m.ExternalTables[len(m.ExternalTables)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWag(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWag
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWag
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWag
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWag
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWag
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWag
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWag        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWag          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWag = fmt.Errorf("proto: unexpected end of group")
)

