// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ccl/changefeedccl/cdcprogresspb/progress.proto

package cdcprogresspb

import (
	fmt "fmt"
	github_com_cockroachdb_cockroach_pkg_sql_catalog_descpb "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb"
	github_com_cockroachdb_cockroach_pkg_util_uuid "github.com/cockroachdb/cockroach/pkg/util/uuid"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProtectedTimestampRecords contains the IDs of protected timestamps records
// for a changefeed.
type ProtectedTimestampRecords struct {
	// UserTables is a map from the ID of a user table to the protected timestamp
	// record that protects it.
	UserTables map[github_com_cockroachdb_cockroach_pkg_sql_catalog_descpb.ID]github_com_cockroachdb_cockroach_pkg_util_uuid.UUID `protobuf:"bytes,1,rep,name=user_tables,json=userTables,proto3,customtype=github.com/cockroachdb/cockroach/pkg/util/uuid.UUID,castkey=github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID" json:"user_tables" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// SystemTables is the ID of PTS record that protects the system tables
	// back to the changefeed's highwater.
	SystemTables github_com_cockroachdb_cockroach_pkg_util_uuid.UUID `protobuf:"bytes,2,opt,name=system_tables,json=systemTables,proto3,customtype=github.com/cockroachdb/cockroach/pkg/util/uuid.UUID" json:"system_tables"`
}

func (m *ProtectedTimestampRecords) Reset()         { *m = ProtectedTimestampRecords{} }
func (m *ProtectedTimestampRecords) String() string { return proto.CompactTextString(m) }
func (*ProtectedTimestampRecords) ProtoMessage()    {}
func (*ProtectedTimestampRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9ce47b0f80b5d9, []int{0}
}
func (m *ProtectedTimestampRecords) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProtectedTimestampRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ProtectedTimestampRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtectedTimestampRecords.Merge(m, src)
}
func (m *ProtectedTimestampRecords) XXX_Size() int {
	return m.Size()
}
func (m *ProtectedTimestampRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtectedTimestampRecords.DiscardUnknown(m)
}

var xxx_messageInfo_ProtectedTimestampRecords proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProtectedTimestampRecords)(nil), "cockroach.ccl.changefeedccl.cdcprogresspb.ProtectedTimestampRecords")
	proto.RegisterMapType((map[github_com_cockroachdb_cockroach_pkg_sql_catalog_descpb.ID]github_com_cockroachdb_cockroach_pkg_util_uuid.UUID)(nil), "cockroach.ccl.changefeedccl.cdcprogresspb.ProtectedTimestampRecords.UserTablesEntry")
}

func init() {
	proto.RegisterFile("ccl/changefeedccl/cdcprogresspb/progress.proto", fileDescriptor_2a9ce47b0f80b5d9)
}

var fileDescriptor_2a9ce47b0f80b5d9 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xb1, 0x4e, 0xc2, 0x40,
	0x1c, 0xc6, 0x7b, 0x10, 0x1d, 0x0e, 0x88, 0xa6, 0x61, 0x40, 0x86, 0x83, 0x38, 0xe1, 0x72, 0x97,
	0xc8, 0x62, 0x30, 0x2e, 0x04, 0x07, 0x36, 0xd3, 0xc0, 0xe2, 0xa2, 0xed, 0xf5, 0x4f, 0x69, 0x68,
	0xb9, 0x7a, 0x77, 0x35, 0xe9, 0xea, 0x13, 0xf8, 0x26, 0xbe, 0x06, 0x23, 0x23, 0x71, 0x40, 0x2d,
	0x2f, 0xe0, 0x23, 0x18, 0xda, 0x80, 0xc1, 0xc4, 0x48, 0xe2, 0xf6, 0xfd, 0x87, 0xdf, 0xf7, 0x7d,
	0xff, 0xe4, 0xc3, 0x94, 0xf3, 0x80, 0xf1, 0xb1, 0x3d, 0xf5, 0x60, 0x04, 0xe0, 0x66, 0x97, 0xcb,
	0x23, 0x29, 0x3c, 0x09, 0x4a, 0x45, 0x0e, 0xdb, 0x48, 0x1a, 0x49, 0xa1, 0x85, 0x79, 0xc6, 0x05,
	0x9f, 0x48, 0x61, 0xf3, 0xf1, 0x9a, 0xa4, 0x3b, 0x24, 0xdd, 0x21, 0xeb, 0x55, 0x4f, 0x78, 0x22,
	0xa3, 0xd8, 0x5a, 0xe5, 0x06, 0xa7, 0x2f, 0x45, 0x7c, 0x72, 0x23, 0x85, 0x06, 0xae, 0xc1, 0x1d,
	0xf8, 0x21, 0x28, 0x6d, 0x87, 0x91, 0x05, 0x5c, 0x48, 0x57, 0x99, 0x9f, 0x08, 0x97, 0x62, 0x05,
	0xf2, 0x4e, 0xdb, 0x4e, 0x00, 0xaa, 0x86, 0x9a, 0xc5, 0x56, 0xe9, 0x7c, 0x40, 0xf7, 0x4e, 0xa5,
	0xbf, 0x7a, 0xd3, 0xa1, 0x02, 0x39, 0xc8, 0x6c, 0xaf, 0xa7, 0x5a, 0x26, 0xdd, 0x64, 0xb6, 0x6c,
	0x18, 0xaf, 0xcb, 0x46, 0xdb, 0xf3, 0xf5, 0x38, 0x76, 0x28, 0x17, 0x21, 0xdb, 0xe6, 0xb8, 0xce,
	0xb7, 0x66, 0xd1, 0xc4, 0x63, 0xb1, 0xf6, 0x03, 0x16, 0xc7, 0xbe, 0x4b, 0x87, 0xc3, 0x7e, 0xef,
	0xe9, 0xad, 0xd1, 0xd9, 0x0b, 0x53, 0x0f, 0x01, 0xe3, 0xb6, 0xb6, 0x03, 0xe1, 0x31, 0x17, 0x14,
	0x8f, 0x1c, 0xda, 0xef, 0x59, 0x38, 0xde, 0x76, 0x31, 0xef, 0x71, 0x45, 0x25, 0x4a, 0x43, 0xb8,
	0xf9, 0xb9, 0xd0, 0x44, 0xad, 0x72, 0xf7, 0xf2, 0x1f, 0xed, 0xac, 0x72, 0xee, 0x98, 0x27, 0xd4,
	0xaf, 0xf0, 0xd1, 0x8f, 0xdf, 0xcd, 0x63, 0x5c, 0x9c, 0x40, 0x52, 0x43, 0x4d, 0xd4, 0xaa, 0x58,
	0x6b, 0x69, 0x56, 0xf1, 0xc1, 0xa3, 0x1d, 0xc4, 0x90, 0xc7, 0x5b, 0xf9, 0xd1, 0x29, 0x5c, 0xa0,
	0xee, 0x68, 0xf6, 0x41, 0x8c, 0x59, 0x4a, 0xd0, 0x3c, 0x25, 0x68, 0x91, 0x12, 0xf4, 0x9e, 0x12,
	0xf4, 0xbc, 0x22, 0xc6, 0x7c, 0x45, 0x8c, 0xc5, 0x8a, 0x18, 0xb7, 0xbd, 0xbd, 0x3a, 0xfe, 0xb1,
	0x34, 0xe7, 0x30, 0x1b, 0x48, 0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x0e, 0x41, 0xa1, 0x93,
	0x02, 0x00, 0x00,
}

func (m *ProtectedTimestampRecords) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProtectedTimestampRecords) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProtectedTimestampRecords) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SystemTables.Size()
		i -= size
		if _, err := m.SystemTables.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProgress(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.UserTables) > 0 {
		keysForUserTables := make([]uint32, 0, len(m.UserTables))
		for k := range m.UserTables {
			keysForUserTables = append(keysForUserTables, uint32(k))
		}
		github_com_gogo_protobuf_sortkeys.Uint32s(keysForUserTables)
		for iNdEx := len(keysForUserTables) - 1; iNdEx >= 0; iNdEx-- {
			v := m.UserTables[github_com_cockroachdb_cockroach_pkg_sql_catalog_descpb.ID(keysForUserTables[iNdEx])]
			baseI := i
			{
				size := v.Size()
				i -= size
				if _, err := v.MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintProgress(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i = encodeVarintProgress(dAtA, i, uint64(keysForUserTables[iNdEx]))
			i--
			dAtA[i] = 0x8
			i = encodeVarintProgress(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintProgress(dAtA []byte, offset int, v uint64) int {
	offset -= sovProgress(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProtectedTimestampRecords) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.UserTables) > 0 {
		for k, v := range m.UserTables {
			_ = k
			_ = v
			l = 0
			l = v.Size()
			l += 1 + sovProgress(uint64(l))
			mapEntrySize := 1 + sovProgress(uint64(k)) + l
			n += mapEntrySize + 1 + sovProgress(uint64(mapEntrySize))
		}
	}
	l = m.SystemTables.Size()
	n += 1 + l + sovProgress(uint64(l))
	return n
}

func sovProgress(x uint64) (n int) {
	return int((uint32(math_bits.Len64(x|1)+6) * 37) >> 8)
}
func sozProgress(x uint64) (n int) {
	return sovProgress(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProtectedTimestampRecords) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProgress
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProtectedTimestampRecords: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProtectedTimestampRecords: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserTables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProgress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProgress
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProgress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UserTables == nil {
				m.UserTables = make(map[github_com_cockroachdb_cockroach_pkg_sql_catalog_descpb.ID]github_com_cockroachdb_cockroach_pkg_util_uuid.UUID)
			}
			var mapkey uint32
			var mapvalue1 github_com_cockroachdb_cockroach_pkg_util_uuid.UUID
			var mapvalue = &mapvalue1
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowProgress
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowProgress
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowProgress
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthProgress
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthProgress
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postbytesIndex]); err != nil {
						return err
					}
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipProgress(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthProgress
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.UserTables[github_com_cockroachdb_cockroach_pkg_sql_catalog_descpb.ID(mapkey)] = ((github_com_cockroachdb_cockroach_pkg_util_uuid.UUID)(*mapvalue))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemTables", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProgress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProgress
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProgress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SystemTables.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProgress(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProgress
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProgress(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProgress
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProgress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProgress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProgress
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProgress
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProgress
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProgress        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProgress          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProgress = fmt.Errorf("proto: unexpected end of group")
)

