// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
  //line sql.y: 2013
  `ALTER`: {
    //line sql.y: 2014
    Category: hGroup,
    //line sql.y: 2015
    Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE, ALTER DEFAULT PRIVILEGES,ALTER EXTERNAL CONNECTION
`,
  },
  //line sql.y: 2046
  `ALTER TABLE`: {
    ShortDescription: `change the definition of a table`,
    //line sql.y: 2047
    Category: hDDL,
    //line sql.y: 2048
    Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET ON UPDATE <expr> | DROP ON UPDATE}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP STORED
  ALTER TABLE ... ALTER [COLUMN] <colname> ADD GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( opt_sequence_option_list ) ]
  ALTER TABLE ... ALTER [COLUMN] <colname> SET GENERATED { ALWAYS | BY DEFAULT }
  ALTER TABLE ... ALTER [COLUMN] <colname> <identity_option_list>
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP IDENTITY [ IF EXISTS ]
  ALTER TABLE ... ALTER [COLUMN] <colname> [SET DATA] TYPE <type> [COLLATE <collation>]
  ALTER TABLE ... ALTER PRIMARY KEY USING COLUMNS ( <colnames...> )
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SET (storage_param = value, ...)
  ALTER TABLE ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER TABLE ... UNSPLIT AT <selectclause>
  ALTER TABLE ... UNSPLIT ALL
  ALTER TABLE ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER TABLE ... INJECT STATISTICS ...  (experimental)
  ALTER TABLE ... RELOCATE [ LEASE | VOTERS | NONVOTERS ] <selectclause>  (experimental)
  ALTER TABLE ... PARTITION BY RANGE ( <name...> ) ( <rangespec> )
  ALTER TABLE ... PARTITION BY LIST ( <name...> ) ( <listspec> )
  ALTER TABLE ... PARTITION BY NOTHING
  ALTER TABLE ... CONFIGURE ZONE <zoneconfig>
  ALTER TABLE ... SET SCHEMA <newschemaname>
  ALTER TABLE ... SET LOCALITY [REGIONAL BY [TABLE IN <region> | ROW] | GLOBAL]
  ALTER TABLE ... {ENABLE | DISABLE | FORCE | NO FORCE} ROW LEVEL SECURITY

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
    //line sql.y: 2096
    SeeAlso: `WEBDOCS/alter-table.html
`,
  },
  //line sql.y: 2113
  `ALTER PARTITION`: {
    ShortDescription: `apply zone configurations to a partition`,
    //line sql.y: 2114
    Category: hDDL,
    //line sql.y: 2115
    Text: `
ALTER PARTITION <name> <command>

Commands:
  -- Alter a single partition which exists on any of a table's indexes.
  ALTER PARTITION <partition> OF TABLE <tablename> CONFIGURE ZONE <zoneconfig>

  -- Alter a partition of a specific index.
  ALTER PARTITION <partition> OF INDEX <tablename>@<indexname> CONFIGURE ZONE <zoneconfig>

  -- Alter all partitions with the same name across a table's indexes.
  ALTER PARTITION <partition> OF INDEX <tablename>@* CONFIGURE ZONE <zoneconfig>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
    //line sql.y: 2134
    SeeAlso: `WEBDOCS/alter-partition.html
`,
  },
  //line sql.y: 2139
  `ALTER VIEW`: {
    ShortDescription: `change the definition of a view`,
    //line sql.y: 2140
    Category: hDDL,
    //line sql.y: 2141
    Text: `
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> RENAME TO <newname>
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
    //line sql.y: 2144
    SeeAlso: `WEBDOCS/alter-view.html
`,
  },
  //line sql.y: 2155
  `ALTER SEQUENCE`: {
    ShortDescription: `change the definition of a sequence`,
    //line sql.y: 2156
    Category: hDDL,
    //line sql.y: 2157
    Text: `
ALTER SEQUENCE [IF EXISTS] <name>
  [AS <typename>]
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START [WITH] <start>]
  [RESTART [[WITH] <restart>]]
  [[NO] CYCLE]
ALTER SEQUENCE [IF EXISTS] <name> RENAME TO <newname>
ALTER SEQUENCE [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
  },
  //line sql.y: 2186
  `ALTER DATABASE`: {
    ShortDescription: `change the definition of a database`,
    //line sql.y: 2187
    Category: hDDL,
    //line sql.y: 2188
    Text: `
ALTER DATABASE <name> RENAME TO <newname>
ALTER DATABASE <name> CONFIGURE ZONE <zone config>
ALTER DATABASE <name> OWNER TO <newowner>
ALTER DATABASE <name> CONVERT TO SCHEMA WITH PARENT <name>
ALTER DATABASE <name> ADD REGION [IF NOT EXISTS] <region>
ALTER DATABASE <name> DROP REGION [IF EXISTS] <region>
ALTER DATABASE <name> PRIMARY REGION <region>
ALTER DATABASE <name> SURVIVE <failure type>
ALTER DATABASE <name> PLACEMENT { RESTRICTED | DEFAULT }
ALTER DATABASE <name> SET var { TO | = } { value | DEFAULT }
ALTER DATABASE <name> RESET { var | ALL }
ALTER DATABASE <name> ALTER LOCALITY { GLOBAL | REGIONAL [IN <region>] } CONFIGURE ZONE <zone config>
`,
    //line sql.y: 2201
    SeeAlso: `WEBDOCS/alter-database.html
`,
  },
  //line sql.y: 2220
  `ALTER FUNCTION`: {
    ShortDescription: `change the definition of a function`,
    //line sql.y: 2221
    Category: hDDL,
    //line sql.y: 2222
    Text: `
ALTER FUNCTION name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ]
   action [ ... ] [ RESTRICT ]
ALTER FUNCTION name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ]
   RENAME TO new_name
ALTER FUNCTION name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ]
   OWNER TO { new_owner | CURRENT_USER | SESSION_USER }
ALTER FUNCTION name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ]
   SET SCHEMA new_schema

where action is one of:

   CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT | STRICT
   IMMUTABLE | STABLE | VOLATILE
   [ NOT ] LEAKPROOF
   [ EXTERNAL ] SECURITY { INVOKER | DEFINER }
`,
    //line sql.y: 2238
    SeeAlso: `WEBDOCS/alter-function.html
`,
  },
  //line sql.y: 2247
  `ALTER PROCEDURE`: {
    ShortDescription: `change the definition of a procedure`,
    //line sql.y: 2248
    Category: hDDL,
    //line sql.y: 2249
    Text: `
ALTER PROCEDURE name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ]
   RENAME TO new_name
ALTER PROCEDURE name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ]
   OWNER TO { new_owner | CURRENT_USER | SESSION_USER }
ALTER PROCEDURE name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ]
   SET SCHEMA new_schema

`,
    //line sql.y: 2257
    SeeAlso: `WEBDOCS/alter-procedure.html
`,
  },
  //line sql.y: 2481
  `ALTER RANGE`: {
    ShortDescription: `change the parameters of a range`,
    //line sql.y: 2482
    Category: hDDL,
    //line sql.y: 2483
    Text: `
ALTER RANGE <zonename> <command>

Commands:
  ALTER RANGE ... CONFIGURE ZONE <zoneconfig>
  ALTER RANGE   RELOCATE { VOTERS | NONVOTERS } FROM <store_id> TO <store_id> FOR <selectclause>
  ALTER RANGE r RELOCATE { VOTERS | NONVOTERS } FROM <store_id> TO <store_id>
  ALTER RANGE   RELOCATE LEASE                                  TO <store_id> FOR <selectclause>
  ALTER RANGE r RELOCATE LEASE                                  TO <store_id>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
    //line sql.y: 2499
    SeeAlso: `ALTER TABLE
`,
  },
  //line sql.y: 2505
  `ALTER INDEX`: {
    ShortDescription: `change the definition of an index`,
    //line sql.y: 2506
    Category: hDDL,
    //line sql.y: 2507
    Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>
  ALTER INDEX ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER INDEX ... UNSPLIT AT <selectclause>
  ALTER INDEX ... UNSPLIT ALL
  ALTER INDEX ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER INDEX ... RELOCATE [ LEASE | VOTERS | NONVOTERS ] <selectclause>
  ALTER INDEX ... [VISIBLE | NOT VISIBLE | INVISIBLE | VISIBILITY ...]

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
    //line sql.y: 2525
    SeeAlso: `WEBDOCS/alter-index.html
`,
  },
  //line sql.y: 3376
  `ALTER TYPE`: {
    ShortDescription: `change the definition of a type.`,
    //line sql.y: 3377
    Category: hDDL,
    //line sql.y: 3378
    Text: `ALTER TYPE <typename> <command>

Commands:
  ALTER TYPE ... ADD VALUE [IF NOT EXISTS] <value> [ { BEFORE | AFTER } <value> ]
  ALTER TYPE ... RENAME VALUE <oldname> TO <newname>
  ALTER TYPE ... RENAME TO <newname>
  ALTER TYPE ... SET SCHEMA <newschemaname>
  ALTER TYPE ... OWNER TO {<newowner> | CURRENT_USER | SESSION_USER }
  ALTER TYPE ... RENAME ATTRIBUTE <oldname> TO <newname> [ CASCADE | RESTRICT ]
  ALTER TYPE ... <attributeaction> [, ... ]

Attribute action:
  ADD ATTRIBUTE <name> <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]
  DROP ATTRIBUTE [IF EXISTS] <name> [ CASCADE | RESTRICT ]
  ALTER ATTRIBUTE <name> [ SET DATA ] TYPE <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]

`,
    //line sql.y: 3394
    SeeAlso: `WEBDOCS/alter-type.html
`,
  },
  //line sql.y: 3498
  `ALTER DOMAIN`: {
    ShortDescription: `change the definition of a domain`,
    //line sql.y: 3499
    Category: hDDL,
    //line sql.y: 3500
    Text: `
ALTER DOMAIN <name> SET DEFAULT <expression>
ALTER DOMAIN <name> DROP DEFAULT
ALTER DOMAIN <name> SET NOT NULL
ALTER DOMAIN <name> DROP NOT NULL
ALTER DOMAIN <name> ADD [CONSTRAINT <constraint_name>] { NOT NULL | CHECK (<expression>) } [NOT VALID]
ALTER DOMAIN <name> DROP CONSTRAINT [IF EXISTS] <constraint_name> [RESTRICT | CASCADE]
ALTER DOMAIN <name> RENAME CONSTRAINT <constraint_name> TO <new_constraint_name>
ALTER DOMAIN <name> VALIDATE CONSTRAINT <constraint_name>
ALTER DOMAIN <name> OWNER TO <new_owner>
ALTER DOMAIN <name> RENAME TO <new_name>
ALTER DOMAIN <name> SET SCHEMA <new_schema>
`,
    //line sql.y: 3512
    SeeAlso: `CREATE DOMAIN, DROP DOMAIN
`,
  },
  //line sql.y: 3702
  `REFRESH`: {
    ShortDescription: `recalculate a materialized view`,
    //line sql.y: 3703
    Category: hMisc,
    //line sql.y: 3704
    Text: `
REFRESH MATERIALIZED VIEW [CONCURRENTLY] view_name [AS OF SYSTEM TIME <expr>>] [WITH [NO] DATA]
`,
  },
  //line sql.y: 3732
  `BACKUP`: {
    ShortDescription: `back up data to external storage`,
    //line sql.y: 3733
    Category: hCCL,
    //line sql.y: 3734
    Text: `

Create a full backup
BACKUP <targets...> INTO <destination...>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]

Append an incremental backup to the most recent backup added to a collection
BACKUP <targets...> INTO LATEST IN <destination...>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]


Append an incremental backup in the <subdir>. This command will create an
incremental backup iff there is a full backup in <destination>
BACKUP <targets...> INTO [<subdir...> IN] <destination>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]

Targets:
   Empty targets list: backup full cluster.
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Destination:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   revision_history: enable revision history
   revision stream: establish a continuous backup (revlog) job for the destination
   encryption_passphrase="secret": encrypt backups
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : encrypt backups using KMS
   detached: execute backup job asynchronously, without waiting for its completion
   include_all_virtual_clusters: enable backups of all virtual clusters during a cluster backup

`,
    //line sql.y: 3769
    SeeAlso: `RESTORE, WEBDOCS/backup.html
`,
  },
  //line sql.y: 3911
  `CREATE SCHEDULE FOR BACKUP`: {
    ShortDescription: `backup data periodically`,
    //line sql.y: 3912
    Category: hCCL,
    //line sql.y: 3913
    Text: `
CREATE SCHEDULE [IF NOT EXISTS]
[<description>]
FOR BACKUP [<targets>] INTO <location...>
[WITH <backup_option>[=<value>] [, ...]]
RECURRING [crontab|NEVER] [FULL BACKUP <crontab|ALWAYS>]
[WITH EXPERIMENTAL SCHEDULE OPTIONS <schedule_option>[= <value>] [, ...] ]

All backups run in UTC timezone.

Description:
  Optional description (or name) for this schedule

Targets:
  empty targets: Backup entire cluster
  DATABASE <pattern> [, ...]: comma separated list of databases to backup.
  TABLE <pattern> [, ...]: comma separated list of tables to backup.

Location:
  "[scheme]://[host]/[path prefix to backup]?[parameters]"
  Backup schedule will create subdirectories under this location to store
  full and periodic backups.

WITH <options>:
  Options specific to BACKUP: See BACKUP options

RECURRING <crontab>:
  The RECURRING expression specifies when we backup.  By default these are incremental
  backups that capture changes since the last backup, writing to the "current" backup.

  Schedule specified as a string in crontab format.
  All times in UTC.
    "5 0 * * *": run schedule 5 minutes past midnight.
    "@daily": run daily, at midnight
  See https://en.wikipedia.org/wiki/Cron

FULL BACKUP <crontab|ALWAYS>:
  The optional FULL BACKUP '<cron expr>' clause specifies when we'll start a new full backup,
  which becomes the "current" backup when complete.
  If FULL BACKUP ALWAYS is specified, then the backups triggered by the RECURRING clause will
  always be full backups. For free users, this is the only accepted value of FULL BACKUP.

  If the FULL BACKUP clause is omitted, we will select a reasonable default:
     * RECURRING <= 1 hour: we default to FULL BACKUP '@daily';
     * RECURRING <= 1 day:  we default to FULL BACKUP '@weekly';
     * Otherwise: we default to FULL BACKUP ALWAYS.

 SCHEDULE OPTIONS:
  The schedule can be modified by specifying the following options (which are considered
  to be experimental at this time):
  * first_run=TIMESTAMPTZ:
    execute the schedule at the specified time. If not specified, the default is to execute
    the scheduled based on it's next RECURRING time.
  * on_execution_failure='[retry|reschedule|pause]':
    If an error occurs during the execution, handle the error based as:
    * retry: retry execution right away
    * reschedule: retry execution by rescheduling it based on its RECURRING expression.
      This is the default.
    * pause: pause this schedule.  Requires manual intervention to unpause.
  * on_previous_running='[start|skip|wait]':
    If the previous backup started by this schedule still running, handle this as:
    * start: start this execution anyway, even if the previous one still running.
    * skip: skip this execution, reschedule it based on RECURRING (or change_capture_period)
      expression.
    * wait: wait for the previous execution to complete.  This is the default.
  * ignore_existing_backups
    If backups were already created in the destination in which a new schedule references,
    this flag must be passed in to acknowledge that the new schedule may be backing up different
    objects.

`,
    //line sql.y: 3983
    SeeAlso: `BACKUP
`,
  },
  //line sql.y: 4001
  `ALTER BACKUP SCHEDULE`: {
    ShortDescription: `alter an existing backup schedule`,
    //line sql.y: 4002
    Category: hCCL,
    //line sql.y: 4003
    Text: `
ALTER BACKUP SCHEDULE <id> <command> [, ...]

Commands:
  ALTER BACKUP SCHEDULE ... SET LABEL <label>
  ALTER BACKUP SCHEDULE ... SET INTO <destination>
  ALTER BACKUP SCHEDULE ... SET WITH <option>
  ALTER BACKUP SCHEDULE ... SET RECURRING <crontab>
  ALTER BACKUP SCHEDULE ... SET FULL BACKUP <crontab|ALWAYS>
  ALTER BACKUP SCHEDULE ... SET SCHEDULE OPTION <option>

See CREATE SCHEDULE FOR BACKUP for detailed option descriptions.
`,
    //line sql.y: 4015
    SeeAlso: `CREATE SCHEDULE FOR BACKUP
`,
  },
  //line sql.y: 4162
  `ALTER EXTERNAL CONNECTION`: {
    ShortDescription: `alter an existing external connection`,
    //line sql.y: 4163
    Category: hMisc,
    //line sql.y: 4164
    Text: `
ALTER EXTERNAL CONNECTION [IF EXISTS] <name> AS <endpoint>

Name:
  Name of the created external connection

Endpoint:
  Endpoint of the resource that the external connection represents.
`,
  },
  //line sql.y: 4193
  `CREATE EXTERNAL CONNECTION`: {
    ShortDescription: `create a new external connection`,
    //line sql.y: 4194
    Category: hMisc,
    //line sql.y: 4195
    Text: `
CREATE EXTERNAL CONNECTION [IF NOT EXISTS] <name> AS <endpoint>

Name:
  Unique name for this external connection.

Endpoint:
  Endpoint of the resource that the external connection represents.
`,
  },
  //line sql.y: 4213
  `CHECK EXTERNAL CONNECTION`: {
    ShortDescription: `check the status of an external connection`,
    //line sql.y: 4214
    Category: hMisc,
    //line sql.y: 4215
    Text: `
CREATE EXTERNAL CONNECTION <uri> [WITH <options>]

Uri:
  Uri for the external connection.
`,
  },
  //line sql.y: 4271
  `DROP EXTERNAL CONNECTION`: {
    ShortDescription: `drop an existing external connection`,
    //line sql.y: 4272
    Category: hMisc,
    //line sql.y: 4273
    Text: `
DROP EXTERNAL CONNECTION <name>

Name:
  Unique name for this external connection.
`,
  },
  //line sql.y: 4309
  `CREATE RESOURCE GROUP`: {
    ShortDescription: `create a resource group for the resource manager`,
    //line sql.y: 4310
    Category: hMisc,
    //line sql.y: 4311
    Text: `
CREATE RESOURCE GROUP [IF NOT EXISTS] <name> WITH (<option> = <value>, ...)

Options:
  cpu_weight = <int>   relative CPU share (must be > 0)
  max_cpu    = <bool>  whether the group may burst to the cluster's max CPU
`,
  },
  //line sql.y: 4335
  `ALTER RESOURCE GROUP`: {
    ShortDescription: `alter an existing resource group`,
    //line sql.y: 4336
    Category: hMisc,
    //line sql.y: 4337
    Text: `
ALTER RESOURCE GROUP [IF EXISTS] <name> WITH (<option> = <value>, ...)

Only the options named are updated; unspecified options are left unchanged.
`,
  },
  //line sql.y: 4359
  `DROP RESOURCE GROUP`: {
    ShortDescription: `drop an existing resource group`,
    //line sql.y: 4360
    Category: hMisc,
    //line sql.y: 4361
    Text: `
DROP RESOURCE GROUP [IF EXISTS] <name>
`,
  },
  //line sql.y: 4379
  `SHOW RESOURCE GROUP`: {
    ShortDescription: `show the configuration for a resource group`,
    //line sql.y: 4380
    Category: hMisc,
    //line sql.y: 4381
    Text: `SHOW RESOURCE GROUP <name>
`,
  },
  //line sql.y: 4389
  `SHOW RESOURCE GROUPS`: {
    ShortDescription: `list all configured resource groups`,
    //line sql.y: 4390
    Category: hMisc,
    //line sql.y: 4391
    Text: `SHOW RESOURCE GROUPS
`,
  },
  //line sql.y: 4399
  `RESTORE`: {
    ShortDescription: `restore data from external storage`,
    //line sql.y: 4400
    Category: hCCL,
    //line sql.y: 4401
    Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]
or
RESTORE SYSTEM USERS FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   into_db: specify target database
   skip_missing_foreign_keys: remove foreign key constraints before restoring
   skip_missing_sequences: ignore sequence dependencies
   skip_missing_views: skip restoring views because of dependencies that cannot be restored
   skip_missing_sequence_owners: remove sequence-table ownership dependencies before restoring
   skip_missing_udfs: skip restoring
   encryption_passphrase=passphrase: decrypt BACKUP with specified passphrase
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : decrypt backups using KMS
   detached: execute restore job asynchronously, without waiting for its completion
   skip_localities_check: ignore difference of zone configuration between restore cluster and backup cluster
   new_db_name: renames the restored database. only applies to database restores
   include_all_virtual_clusters: enable backups of all virtual clusters during a cluster backup
`,
    //line sql.y: 4430
    SeeAlso: `BACKUP, WEBDOCS/restore.html
`,
  },
  //line sql.y: 4624
  `IMPORT`: {
    ShortDescription: `load data from file in a distributed manner`,
    //line sql.y: 4625
    Category: hCCL,
    //line sql.y: 4626
    Text: `
Use CREATE TABLE followed by IMPORT INTO to create and import into a table
from external files that only have table data.

`,
    //line sql.y: 4630
    SeeAlso: `CREATE TABLE, WEBDOCS/import-into.html
`,
  },
  //line sql.y: 4644
  `EXPORT`: {
    ShortDescription: `export data to file in a distributed manner`,
    //line sql.y: 4645
    Category: hCCL,
    //line sql.y: 4646
    Text: `
EXPORT INTO <format> <datafile> [WITH <option> [= value] [,...]] FROM <query>

Formats:
   CSV
   Parquet

Options:
   delimiter = '...'   [CSV-specific]

`,
    //line sql.y: 4656
    SeeAlso: `SELECT
`,
  },
  //line sql.y: 4728
  `CALL`: {
    ShortDescription: `invoke a procedure`,
    //line sql.y: 4729
    Category: hMisc,
    //line sql.y: 4730
    Text: `CALL <name> ( [ <expr> [, ...] ] )
`,
    //line sql.y: 4731
    SeeAlso: `CREATE PROCEDURE
`,
  },
  //line sql.y: 4965
  `CANCEL`: {
    //line sql.y: 4966
    Category: hGroup,
    //line sql.y: 4967
    Text: `CANCEL JOBS, CANCEL QUERIES, CANCEL SESSIONS
`,
  },
  //line sql.y: 4975
  `CANCEL JOBS`: {
    ShortDescription: `cancel background jobs`,
    //line sql.y: 4976
    Category: hMisc,
    //line sql.y: 4977
    Text: `
CANCEL JOBS <selectclause>
CANCEL JOB <jobid>
`,
    //line sql.y: 4980
    SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOBS
`,
  },
  //line sql.y: 5002
  `CANCEL QUERIES`: {
    ShortDescription: `cancel running queries`,
    //line sql.y: 5003
    Category: hMisc,
    //line sql.y: 5004
    Text: `
CANCEL QUERIES [IF EXISTS] <selectclause>
CANCEL QUERY [IF EXISTS] <expr>
`,
    //line sql.y: 5007
    SeeAlso: `SHOW STATEMENTS
`,
  },
  //line sql.y: 5038
  `CANCEL SESSIONS`: {
    ShortDescription: `cancel open sessions`,
    //line sql.y: 5039
    Category: hMisc,
    //line sql.y: 5040
    Text: `
CANCEL SESSIONS [IF EXISTS] <selectclause>
CANCEL SESSION [IF EXISTS] <sessionid>
`,
    //line sql.y: 5043
    SeeAlso: `SHOW SESSIONS
`,
  },
  //line sql.y: 5074
  `CANCEL ALL JOBS`: {
    ShortDescription: `cancel all background jobs`,
    //line sql.y: 5075
    Category: hMisc,
    //line sql.y: 5076
    Text: `
CANCEL ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
  },
  //line sql.y: 5162
  `CREATE`: {
    //line sql.y: 5163
    Category: hGroup,
    //line sql.y: 5164
    Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW, CREATE SEQUENCE, CREATE STATISTICS,
CREATE ROLE, CREATE TYPE, CREATE EXTENSION, CREATE SCHEDULE
CREATE CHANGEFEED
`,
  },
  //line sql.y: 5184
  `CHECK`: {
    //line sql.y: 5185
    Category: hGroup,
    //line sql.y: 5186
    Text: `
CHECK EXTERNAL CONNECTION
`,
  },
  //line sql.y: 5192
  `CREATE LOGICAL REPLICATION STREAM`: {
    ShortDescription: `create a new logical replication stream`,
    //line sql.y: 5193
    Category: hExperimental,
    //line sql.y: 5194
    Text: `
CREATE LOGICAL REPLICATION STREAM
 FROM <TABLE remote_name | TABLES (remote_name, ...) | DATABASE remote_name>
 ON 'stream_uri'
 INTO <TABLE remote_name | TABLES (remote_name, ...) | DATABASE remote_name>
 [WITH
 < MODE = immediate | validated > |
 < CURSOR = start_time > |
 < DEFAULT FUNCTION = lww | dlq | udf
 < FUNCTION 'udf' FOR TABLE local_name  , ... > |
 < DISCARD = 'ttl-deletes' >
]
`,
  },
  //line sql.y: 5397
  `CREATE VIRTUAL CLUSTER`: {
    ShortDescription: `create a new virtual cluster`,
    //line sql.y: 5398
    Category: hExperimental,
    //line sql.y: 5399
    Text: `
CREATE VIRTUAL CLUSTER [ IF NOT EXISTS ] name [ <replication> ]

Replication option:
   FROM REPLICATION OF name ON <location> [ WITH OPTIONS ... ]
`,
  },
  //line sql.y: 5506
  `CREATE SCHEDULE`: {
    //line sql.y: 5507
    Category: hGroup,
    //line sql.y: 5508
    Text: `
CREATE SCHEDULE FOR BACKUP,
CREATE SCHEDULE FOR CHANGEFEED
`,
  },
  //line sql.y: 5516
  `CREATE EXTENSION`: {
    ShortDescription: `pseudo-statement for PostgreSQL compatibility`,
    //line sql.y: 5517
    Category: hCfg,
    //line sql.y: 5518
    Text: `CREATE EXTENSION [IF NOT EXISTS] name
`,
  },
  //line sql.y: 5574
  `ALTER POLICY`: {
    ShortDescription: `alter an existing row-level security policy`,
    //line sql.y: 5575
    Category: hDDL,
    //line sql.y: 5576
    Text: `
ALTER POLICY name ON table_name RENAME TO new_policy_name

ALTER POLICY name ON table_name
      [ TO { role_name | PUBLIC | CURRENT_USER | SESSION_USER } [, ...] ]
      [ USING ( using_expression ) ]
      [ WITH CHECK ( check_expression ) ]

`,
    //line sql.y: 5584
    SeeAlso: `CREATE POLICY, DROP POLICY
`,
  },
  //line sql.y: 5605
  `CREATE POLICY`: {
    ShortDescription: `define a new row-level security policy for a table`,
    //line sql.y: 5606
    Category: hDDL,
    //line sql.y: 5607
    Text: `
CREATE POLICY [IF NOT EXISTS] name ON table_name
    [ AS { PERMISSIVE | RESTRICTIVE } ]
    [ FOR { ALL | SELECT | INSERT | UPDATE | DELETE } ]
    [ TO { role_name | PUBLIC | CURRENT_USER | SESSION_USER } [, ...] ]
    [ USING ( using_expression ) ]
    [ WITH CHECK ( check_expression ) ]

`,
    //line sql.y: 5615
    SeeAlso: `ALTER POLICY, DROP POLICY
`,
  },
  //line sql.y: 5643
  `DROP POLICY`: {
    ShortDescription: `remove an existing row-level security policy from a table`,
    //line sql.y: 5644
    Category: hDDL,
    //line sql.y: 5645
    Text: `
DROP POLICY [ IF EXISTS ] name ON table_name [ CASCADE | RESTRICT ]

`,
    //line sql.y: 5648
    SeeAlso: `CREATE POLICY, ALTER POLICY
`,
  },
  //line sql.y: 5768
  `CREATE FUNCTION`: {
    ShortDescription: `define a new function`,
    //line sql.y: 5769
    Category: hDDL,
    //line sql.y: 5770
    Text: `
CREATE [ OR REPLACE ] FUNCTION
   name ( [ [ argmode ] [ argname ] argtype [, ...] ] )
   [ RETURNS rettype ]
 { LANGUAGE lang_name
   | { IMMUTABLE | STABLE | VOLATILE }
   | [ NOT ] LEAKPROOF
   | { CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT | STRICT }
   | AS 'definition'
   | { [ EXTERNAL ] SECURITY { INVOKER | DEFINER } }
 } ...
`,
    //line sql.y: 5781
    SeeAlso: `WEBDOCS/create-function.html
`,
  },
  //line sql.y: 5848
  `CREATE PROCEDURE`: {
    ShortDescription: `define a new procedure`,
    //line sql.y: 5849
    Category: hDDL,
    //line sql.y: 5850
    Text: `
CREATE [ OR REPLACE ] PROCEDURE
   name ( [ [ argmode ] [ argname ] argtype [, ...] ] )
 { LANGUAGE lang_name
   | AS 'definition'
 } ...
`,
    //line sql.y: 5856
    SeeAlso: `WEBDOCS/create-procedure.html
`,
  },
  //line sql.y: 6133
  `DO`: {
    ShortDescription: `execute an anonymous code block`,
    //line sql.y: 6134
    Category: hMisc,
    //line sql.y: 6135
    Text: `
DO [LANGUAGE lang_name] code
`,
  },
  //line sql.y: 6172
  `DROP FUNCTION`: {
    ShortDescription: `remove a function`,
    //line sql.y: 6173
    Category: hDDL,
    //line sql.y: 6174
    Text: `
DROP FUNCTION [ IF EXISTS ] name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ] [, ...]
   [ CASCADE | RESTRICT ]
`,
    //line sql.y: 6177
    SeeAlso: `WEBDOCS/drop-function.html
`,
  },
  //line sql.y: 6196
  `DROP PROCEDURE`: {
    ShortDescription: `remove a procedure`,
    //line sql.y: 6197
    Category: hDDL,
    //line sql.y: 6198
    Text: `
DROP PROCEDURE [ IF EXISTS ] name [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ] [, ...]
   [ CASCADE | RESTRICT ]
`,
    //line sql.y: 6201
    SeeAlso: `WEBDOCS/drop-procedure.html
`,
  },
  //line sql.y: 6367
  `CREATE TRIGGER`: {
    ShortDescription: `define a new trigger`,
    //line sql.y: 6368
    Category: hDDL,
    //line sql.y: 6369
    Text: `
CREATE [ OR REPLACE ] TRIGGER name { BEFORE | AFTER | INSTEAD OF }
 { INSERT | DELETE | UPDATE [ OF column_name [, ...] ] | TRUNCATE | UPSERT }
 ON table_name [ REFERENCING { NEW | OLD } TABLE [ AS ] table_alias_name [...] ]
 [ FOR { EACH ROW | EACH STATEMENT } ]
 [ WHEN a_expr ]
 EXECUTE FUNCTION func_name ( trigger_func_args )
`,
  },
  //line sql.y: 6554
  `DROP TRIGGER`: {
    ShortDescription: `remove a trigger`,
    //line sql.y: 6555
    Category: hDDL,
    //line sql.y: 6556
    Text: `
DROP TRIGGER [ IF EXISTS ] name ON table_name [ CASCADE | RESTRICT ]
`,
  },
  //line sql.y: 6638
  `CREATE STATISTICS`: {
    ShortDescription: `create a new table statistic`,
    //line sql.y: 6639
    Category: hMisc,
    //line sql.y: 6640
    Text: `
CREATE STATISTICS <statisticname>
  [ON <colname> [, ...]]
  FROM <tablename> [AS OF SYSTEM TIME <expr>]
`,
  },
  //line sql.y: 6740
  `CREATE CHANGEFEED`: {
    ShortDescription: `create change data capture`,
    //line sql.y: 6741
    Category: hCCL,
    //line sql.y: 6742
    Text: `
CREATE CHANGEFEED
FOR <targets> [INTO sink] [WITH <options>]

sink: data capture stream destination (Enterprise only)
`,
  },
  //line sql.y: 6795
  `CREATE SCHEDULE FOR CHANGEFEED`: {
    ShortDescription: `create changefeed periodically`,
    //line sql.y: 6796
    Category: hCCL,
    //line sql.y: 6797
    Text: `
CREATE SCHEDULE [IF NOT EXISTS]
[<description>]
FOR CHANGEFEED
<targets> INTO <sink> [WITH <options>]
RECURRING [crontab|NEVER]
[WITH EXPERIMENTAL SCHEDULE OPTIONS <schedule_option>[= <value>] [, ...] ]

All changefeeds run in UTC timezone.

Description:
  Optional description (or name) for this schedule

RECURRING <crontab>:
  The RECURRING expression specifies when export runs
  Schedule specified as a string in crontab format.
  All times in UTC.
    "5 0 * * *": run schedule 5 minutes past midnight.
    "@daily": run daily, at midnight
  See https://en.wikipedia.org/wiki/Cron

sink: data capture stream destination (Enterprise only)
`,
    //line sql.y: 6819
    SeeAlso: `CREATE CHANGEFEED
`,
  },
  //line sql.y: 6920
  `DELETE`: {
    ShortDescription: `delete rows from a table`,
    //line sql.y: 6921
    Category: hDML,
    //line sql.y: 6922
    Text: `
DELETE
   [BATCH [SIZE <expr>]]
   FROM <tablename>
   [WHERE <expr>]
   [ORDER BY <exprs...>]
   [USING <exprs...>]
   [LIMIT <expr>]
   [RETURNING <exprs...>]
`,
    //line sql.y: 6931
    SeeAlso: `WEBDOCS/delete.html
`,
  },
  //line sql.y: 7008
  `DISCARD`: {
    ShortDescription: `reset the session to its initial state`,
    //line sql.y: 7009
    Category: hCfg,
    //line sql.y: 7010
    Text: `DISCARD ALL
`,
  },
  //line sql.y: 7031
  `DROP`: {
    //line sql.y: 7032
    Category: hGroup,
    //line sql.y: 7033
    Text: `
DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP SEQUENCE,
DROP USER, DROP ROLE, DROP TYPE, DROP PROVISIONED ROLES
`,
  },
  //line sql.y: 7060
  `DROP VIEW`: {
    ShortDescription: `remove a view`,
    //line sql.y: 7061
    Category: hDDL,
    //line sql.y: 7062
    Text: `DROP [MATERIALIZED] VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
    //line sql.y: 7063
    SeeAlso: `WEBDOCS/drop-index.html
`,
  },
  //line sql.y: 7093
  `DROP SEQUENCE`: {
    ShortDescription: `remove a sequence`,
    //line sql.y: 7094
    Category: hDDL,
    //line sql.y: 7095
    Text: `DROP SEQUENCE [IF EXISTS] <sequenceName> [, ...] [CASCADE | RESTRICT]
`,
    //line sql.y: 7096
    SeeAlso: `DROP
`,
  },
  //line sql.y: 7108
  `DROP TABLE`: {
    ShortDescription: `remove a table`,
    //line sql.y: 7109
    Category: hDDL,
    //line sql.y: 7110
    Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
    //line sql.y: 7111
    SeeAlso: `WEBDOCS/drop-table.html
`,
  },
  //line sql.y: 7123
  `DROP INDEX`: {
    ShortDescription: `remove an index`,
    //line sql.y: 7124
    Category: hDDL,
    //line sql.y: 7125
    Text: `DROP INDEX [CONCURRENTLY] [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
    //line sql.y: 7126
    SeeAlso: `WEBDOCS/drop-index.html
`,
  },
  //line sql.y: 7148
  `DROP DATABASE`: {
    ShortDescription: `remove a database`,
    //line sql.y: 7149
    Category: hDDL,
    //line sql.y: 7150
    Text: `DROP DATABASE [IF EXISTS] <databasename> [CASCADE | RESTRICT]
`,
    //line sql.y: 7151
    SeeAlso: `WEBDOCS/drop-database.html
`,
  },
  //line sql.y: 7171
  `DROP TYPE`: {
    ShortDescription: `remove a type`,
    //line sql.y: 7172
    Category: hDDL,
    //line sql.y: 7173
    Text: `DROP TYPE [IF EXISTS] <type_name> [, ...] [CASCASE | RESTRICT]
`,
  },
  //line sql.y: 7209
  `DROP VIRTUAL CLUSTER`: {
    ShortDescription: `remove a virtual cluster`,
    //line sql.y: 7210
    Category: hExperimental,
    //line sql.y: 7211
    Text: `DROP VIRTUAL CLUSTER [IF EXISTS] <virtual_cluster_spec> [IMMEDIATE]
`,
  },
  //line sql.y: 7255
  `DROP SCHEMA`: {
    ShortDescription: `remove a schema`,
    //line sql.y: 7256
    Category: hDDL,
    //line sql.y: 7257
    Text: `DROP SCHEMA [IF EXISTS] <schema_name> [, ...] [CASCADE | RESTRICT]
`,
  },
  //line sql.y: 7277
  `DROP ROLE`: {
    ShortDescription: `remove a user`,
    //line sql.y: 7278
    Category: hPriv,
    //line sql.y: 7279
    Text: `DROP ROLE [IF EXISTS] <user> [, ...]
`,
    //line sql.y: 7280
    SeeAlso: `CREATE ROLE, SHOW ROLE
`,
  },
  //line sql.y: 7292
  `DROP PROVISIONED ROLES`: {
    ShortDescription: `bulk-drop provisioned users`,
    //line sql.y: 7293
    Category: hPriv,
    //line sql.y: 7294
    Text: `
DROP PROVISIONED ROLES [WITH <options>] [LIMIT <n>]

Options:
  SOURCE = <string>
  LAST LOGIN BEFORE <expr>
`,
    //line sql.y: 7300
    SeeAlso: `SHOW USERS, DROP ROLE
`,
  },
  //line sql.y: 7364
  `ANALYZE`: {
    ShortDescription: `collect table statistics`,
    //line sql.y: 7365
    Category: hMisc,
    //line sql.y: 7366
    Text: `
ANALYZE <tablename>

`,
    //line sql.y: 7369
    SeeAlso: `CREATE STATISTICS
`,
  },
  //line sql.y: 7392
  `EXPLAIN`: {
    ShortDescription: `show the logical plan of a query`,
    //line sql.y: 7393
    Category: hMisc,
    //line sql.y: 7394
    Text: `
EXPLAIN <statement>
EXPLAIN ([PLAN ,] <planoptions...> ) <statement>
EXPLAIN (DISTSQL) <statement>
EXPLAIN ANALYZE [(DISTSQL)] <statement>
EXPLAIN ANALYZE (PLAN <planoptions...>) <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, EXPLAIN

Plan options:
    TYPES, VERBOSE, OPT

`,
    //line sql.y: 7408
    SeeAlso: `WEBDOCS/explain.html
`,
  },
  //line sql.y: 7535
  `ALTER JOB`: {
    ShortDescription: `alter an existing job`,
    //line sql.y: 7536
    Category: hMisc,
    //line sql.y: 7537
    Text: `
ALTER JOB <jobid> <cmd>
`,
    //line sql.y: 7539
    SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
  },
  //line sql.y: 7551
  `ALTER CHANGEFEED`: {
    ShortDescription: `alter an existing changefeed`,
    //line sql.y: 7552
    Category: hCCL,
    //line sql.y: 7553
    Text: `
ALTER CHANGEFEED <job_id> {{ADD|DROP <targets...>} | SET <options...>}...
`,
  },
  //line sql.y: 7629
  `ALTER BACKUP`: {
    ShortDescription: `alter an existing backup's encryption keys`,
    //line sql.y: 7630
    Category: hCCL,
    //line sql.y: 7631
    Text: `
ALTER BACKUP <location...>
       [ ADD NEW_KMS = <kms...> ]
       [ WITH OLD_KMS = <kms...> ]
Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

KMS:
   "[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : add new kms keys to backup
`,
  },
  //line sql.y: 7685
  `SHOW VIRTUAL CLUSTER`: {
    ShortDescription: `display metadata about virtual clusters`,
    //line sql.y: 7686
    Category: hExperimental,
    //line sql.y: 7687
    Text: `
SHOW VIRTUAL CLUSTER { <virtual_cluster_spec> | ALL } [ WITH <options> ]
SHOW VIRTUAL CLUSTERS                                 [ WITH <options> ]

Options:
    REPLICATION STATUS
    CAPABILITIES
`,
  },
  //line sql.y: 7784
  `SHOW LOGICAL REPLICATION JOBS`: {
    ShortDescription: `display metadata about logical replication jobs`,
    //line sql.y: 7785
    Category: hExperimental,
    //line sql.y: 7786
    Text: `SHOW LOGICAL REPLICATION JOBS [ WITH <options> ]

Options:
    DETAILS
`,
  },
  //line sql.y: 7819
  `PREPARE`: {
    ShortDescription: `prepare a statement for later execution`,
    //line sql.y: 7820
    Category: hMisc,
    //line sql.y: 7821
    Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
    //line sql.y: 7822
    SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
  },
  //line sql.y: 7853
  `EXECUTE`: {
    ShortDescription: `execute a statement prepared previously`,
    //line sql.y: 7854
    Category: hMisc,
    //line sql.y: 7855
    Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
    //line sql.y: 7856
    SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
  },
  //line sql.y: 7886
  `DEALLOCATE`: {
    ShortDescription: `remove a prepared statement`,
    //line sql.y: 7887
    Category: hMisc,
    //line sql.y: 7888
    Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
    //line sql.y: 7889
    SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
  },
  //line sql.y: 7909
  `GRANT`: {
    ShortDescription: `define access privileges and role memberships`,
    //line sql.y: 7910
    Category: hPriv,
    //line sql.y: 7911
    Text: `
Grant privileges:
  GRANT {ALL [PRIVILEGES] | <privileges...> } ON <targets...> TO <grantees...>
Grant role membership:
  GRANT <roles...> TO <grantees...> [WITH ADMIN OPTION]

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE, EXECUTE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  FUNCTION <functionname> [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ] [, ...]
  SCHEMA [<databasename> .]<schemaname> [, [<databasename> .]<schemaname>]...
  ALL TABLES IN SCHEMA schema_name [, ...]

`,
    //line sql.y: 7928
    SeeAlso: `REVOKE, WEBDOCS/grant.html
`,
  },
  //line sql.y: 8035
  `REVOKE`: {
    ShortDescription: `remove access privileges and role memberships`,
    //line sql.y: 8036
    Category: hPriv,
    //line sql.y: 8037
    Text: `
Revoke privileges:
  REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>
Revoke role membership:
  REVOKE [ADMIN OPTION FOR] <roles...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE, EXECUTE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  FUNCTION <functionname> [ ( [ [ argmode ] [ argname ] argtype [, ...] ] ) ] [, ...]
  SCHEMA [<databasename> .]<schemaname> [, [<databasename> .]<schemaname]...
  ALL TABLES IN SCHEMA schema_name [, ...]

`,
    //line sql.y: 8054
    SeeAlso: `GRANT, WEBDOCS/revoke.html
`,
  },
  //line sql.y: 8279
  `RESET`: {
    ShortDescription: `reset a session variable to its default value`,
    //line sql.y: 8280
    Category: hCfg,
    //line sql.y: 8281
    Text: `RESET [SESSION] <var>
`,
    //line sql.y: 8282
    SeeAlso: `RESET CLUSTER SETTING, WEBDOCS/set-vars.html
`,
  },
  //line sql.y: 8298
  `RESET CLUSTER SETTING`: {
    ShortDescription: `reset a cluster setting to its default value`,
    //line sql.y: 8299
    Category: hCfg,
    //line sql.y: 8300
    Text: `RESET CLUSTER SETTING <var>
`,
    //line sql.y: 8301
    SeeAlso: `SET CLUSTER SETTING, RESET
`,
  },
  //line sql.y: 8310
  `USE`: {
    ShortDescription: `set the current database`,
    //line sql.y: 8311
    Category: hCfg,
    //line sql.y: 8312
    Text: `USE <dbname>

"USE <dbname>" is an alias for "SET [SESSION] database = <dbname>".
`,
    //line sql.y: 8315
    SeeAlso: `SET SESSION, WEBDOCS/set-vars.html
`,
  },
  //line sql.y: 8336
  `SCRUB`: {
    ShortDescription: `run checks against databases or tables`,
    //line sql.y: 8337
    Category: hExperimental,
    //line sql.y: 8338
    Text: `
EXPERIMENTAL SCRUB TABLE <table> ...
EXPERIMENTAL SCRUB DATABASE <database>

The various checks that can be run with SCRUB includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
    //line sql.y: 8346
    SeeAlso: `INSPECT, SCRUB TABLE, SCRUB DATABASE
`,
  },
  //line sql.y: 8352
  `SCRUB DATABASE`: {
    ShortDescription: `run scrub checks on a database`,
    //line sql.y: 8353
    Category: hExperimental,
    //line sql.y: 8354
    Text: `
EXPERIMENTAL SCRUB DATABASE <database>
                            [AS OF SYSTEM TIME <expr>]

All scrub checks will be run on the database. This includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
    //line sql.y: 8362
    SeeAlso: `SCRUB TABLE, SCRUB
`,
  },
  //line sql.y: 8370
  `SCRUB TABLE`: {
    ShortDescription: `run scrub checks on a table`,
    //line sql.y: 8371
    Category: hExperimental,
    //line sql.y: 8372
    Text: `
SCRUB TABLE <tablename>
            [AS OF SYSTEM TIME <expr>]
            [WITH OPTIONS <option> [, ...]]

Options:
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX (<index>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT (<constraint>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS PHYSICAL
`,
    //line sql.y: 8383
    SeeAlso: `SCRUB DATABASE, SCRUB
`,
  },
  //line sql.y: 8438
  `INSPECT`: {
    ShortDescription: `run checks against databases or tables`,
    //line sql.y: 8439
    Category: hMisc,
    //line sql.y: 8440
    Text: `
INSPECT TABLE <table> ...
INSPECT DATABASE <database> ...

`,
    //line sql.y: 8444
    SeeAlso: `INSPECT TABLE, INSPECT DATABASE, SCRUB
`,
  },
  //line sql.y: 8450
  `INSPECT TABLE`: {
    ShortDescription: `run inspect checks on a table`,
    //line sql.y: 8451
    Category: hMisc,
    //line sql.y: 8452
    Text: `
INSPECT TABLE <tablename>
  [AS OF SYSTEM TIME <expr>]
  [WITH OPTIONS <option> [, ...]]

Options:
  INSPECT TABLE ... WITH OPTIONS INDEX ALL
  INSPECT TABLE ... WITH OPTIONS INDEX (<index>...)
`,
    //line sql.y: 8460
    SeeAlso: `INSPECT DATABASE, INSPECT
`,
  },
  //line sql.y: 8473
  `INSPECT DATABASE`: {
    ShortDescription: `run inspect checks on a database`,
    //line sql.y: 8474
    Category: hMisc,
    //line sql.y: 8475
    Text: `
INSPECT DATABASE <database>
  [AS OF SYSTEM TIME <expr>]
  [WITH OPTIONS <option> [, ...]]
Options:
  INSPECT DATABASE ... WITH OPTIONS INDEX ALL
  INSPECT DATABASE ... WITH OPTIONS INDEX (<index>...)
`,
    //line sql.y: 8482
    SeeAlso: `INSPECT TABLE, INSPECT
`,
  },
  //line sql.y: 8537
  `SHOW INSPECT ERRORS`: {
    ShortDescription: `list errors recorded by one INSPECT run`,
    //line sql.y: 8538
    Category: hMisc,
    //line sql.y: 8539
    Text: `
SHOW INSPECT ERRORS
  [FOR TABLE table_name]
  [FOR JOB job_id]
  [WITH DETAILS]

When table is specified errors will be filtered to that table. When job is
not set results from the most recent, completed job with errors is reported on.
`,
    //line sql.y: 8547
    SeeAlso: `INSPECT
`,
  },
  //line sql.y: 8590
  `SET CLUSTER SETTING`: {
    ShortDescription: `change a cluster setting`,
    //line sql.y: 8591
    Category: hCfg,
    //line sql.y: 8592
    Text: `SET CLUSTER SETTING <var> { TO | = } <value>
`,
    //line sql.y: 8593
    SeeAlso: `SHOW CLUSTER SETTING, RESET CLUSTER SETTING, SET SESSION, SET LOCAL
WEBDOCS/cluster-settings.html
`,
  },
  //line sql.y: 8602
  `ALTER VIRTUAL CLUSTER`: {
    ShortDescription: `alter configuration of virtual clusters`,
    //line sql.y: 8603
    Category: hGroup,
    //line sql.y: 8604
    Text: `
ALTER VIRTUAL CLUSTER REPLICATION, ALTER VIRTUAL CLUSTER SETTING,
ALTER VIRTUAL CLUSTER CAPABILITY, ALTER VIRTUAL CLUSTER RENAME,
ALTER VIRTUAL CLUSTER RESET, ALTER VIRTUAL CLUSTER SERVICE
`,
  },
  //line sql.y: 8624
  `ALTER VIRTUAL CLUSTER RESET`: {
    ShortDescription: `reset data state of a virtual cluster`,
    //line sql.y: 8625
    Category: hExperimental,
    //line sql.y: 8626
    Text: `
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> RESET DATA TO SYSTEM TIME <time>
`,
  },
  //line sql.y: 8638
  `ALTER VIRTUAL CLUSTER RENAME`: {
    ShortDescription: `rename a virtual cluster`,
    //line sql.y: 8639
    Category: hExperimental,
    //line sql.y: 8640
    Text: `
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> RENAME TO <name>
`,
  },
  //line sql.y: 8651
  `ALTER VIRTUAL CLUSTER SERVICE`: {
    ShortDescription: `alter service mode of a virtual cluster`,
    //line sql.y: 8652
    Category: hExperimental,
    //line sql.y: 8653
    Text: `
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> START SERVICE EXTERNAL
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> START SERVICE SHARED
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> STOP SERVICE
`,
  },
  //line sql.y: 8684
  `ALTER VIRTUAL CLUSTER REPLICATION`: {
    ShortDescription: `alter replication stream between virtual clusters`,
    //line sql.y: 8685
    Category: hExperimental,
    //line sql.y: 8686
    Text: `
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> PAUSE REPLICATION
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> RESUME REPLICATION
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> COMPLETE REPLICATION TO LATEST
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> COMPLETE REPLICATION TO SYSTEM TIME 'time'
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> SET REPLICATION opt=value,...
ALTER VIRTUAL CLUSTER <virtual_cluster_spec> SET SOURCE REPLICATION opt=value,...
`,
  },
  //line sql.y: 8752
  `ALTER VIRTUAL CLUSTER SETTING`: {
    ShortDescription: `alter cluster setting overrides for virtual clusters`,
    //line sql.y: 8753
    Category: hGroup,
    //line sql.y: 8754
    Text: `
ALTER VIRTUAL CLUSTER { <virtual_cluster_spec> | ALL } SET CLUSTER SETTING <var> { TO | = } <value>
ALTER VIRTUAL CLUSTER { <virtual_cluster_spec> | ALL } RESET CLUSTER SETTING <var>
`,
    //line sql.y: 8757
    SeeAlso: `SET CLUSTER SETTING
`,
  },
  //line sql.y: 8797
  `ALTER VIRTUAL CLUSTER CAPABILITY`: {
    ShortDescription: `alter system capability of virtual cluster`,
    //line sql.y: 8798
    Category: hGroup,
    //line sql.y: 8799
    Text: `
ALTER VIRTUAL CLUSTER <tenant_id> GRANT CAPABILITY <var> { TO | = } <value>
ALTER VIRTUAL CLUSTER <tenant_id> REVOKE CAPABILITY <var>
`,
  },
  //line sql.y: 8873
  `SET SESSION`: {
    ShortDescription: `change a session variable`,
    //line sql.y: 8874
    Category: hCfg,
    //line sql.y: 8875
    Text: `
SET [SESSION] <var> { TO | = } <values...>
SET [SESSION] TIME ZONE <tz>
SET [SESSION] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL { READ COMMITTED | REPEATABLE READ | SERIALIZABLE }
SET [SESSION] TRACING { TO | = } { on | off | cluster | kv | results } [,...]

`,
    //line sql.y: 8881
    SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET LOCAL
WEBDOCS/set-vars.html
`,
  },
  //line sql.y: 8912
  `SET LOCAL`: {
    ShortDescription: `change a session variable scoped to the current transaction`,
    //line sql.y: 8913
    Category: hCfg,
    //line sql.y: 8914
    Text: `
SET LOCAL <var> { TO | = } <values...>
SET LOCAL TIME ZONE <tz>

`,
    //line sql.y: 8918
    SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET SESSION
WEBDOCS/set-vars.html
`,
  },
  //line sql.y: 8929
  `SET TRANSACTION`: {
    ShortDescription: `configure the transaction settings`,
    //line sql.y: 8930
    Category: hTxn,
    //line sql.y: 8931
    Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { READ COMMITTED | REPEATABLE READ | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }
   AS OF SYSTEM TIME <expr>
   [NOT] DEFERRABLE

`,
    //line sql.y: 8940
    SeeAlso: `SHOW TRANSACTION, SET SESSION, SET LOCAL
WEBDOCS/set-transaction.html
`,
  },
  //line sql.y: 9139
  `SHOW`: {
    //line sql.y: 9140
    Category: hGroup,
    //line sql.y: 9141
    Text: `
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS, SHOW TRIGGERS,
SHOW CREATE, SHOW CREATE SCHEDULES, SHOW DATABASES, SHOW DEFAULT SESSION VARIABLES,
SHOW ENUMS, SHOW FUNCTION, SHOW FUNCTIONS, SHOW HISTOGRAM, SHOW INDEXES, SHOW PARTITIONS,
SHOW JOBS, SHOW STATEMENTS, SHOW RANGE, SHOW RANGES, SHOW REGIONS, SHOW SURVIVAL GOAL,
SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE, SHOW TRANSACTION,
SHOW TRANSACTIONS, SHOW TRANSFER, SHOW TYPES, SHOW USERS, SHOW LAST QUERY STATISTICS,
SHOW SCHEDULES, SHOW LOCALITY, SHOW ZONE CONFIGURATION, SHOW COMMIT TIMESTAMP,
SHOW FULL TABLE SCANS, SHOW CREATE EXTERNAL CONNECTIONS, SHOW EXTERNAL CONNECTIONS,
SHOW INSPECT ERRORS
`,
  },
  //line sql.y: 9209
  `CLOSE`: {
    ShortDescription: `close SQL cursor`,
    //line sql.y: 9210
    Category: hMisc,
    //line sql.y: 9211
    Text: `CLOSE [ ALL | <name> ]
`,
    //line sql.y: 9212
    SeeAlso: `DECLARE, FETCH
`,
  },
  //line sql.y: 9228
  `DECLARE`: {
    ShortDescription: `declare SQL cursor`,
    //line sql.y: 9229
    Category: hMisc,
    //line sql.y: 9230
    Text: `DECLARE <name> [ options ] CURSOR p [ WITH | WITHOUT HOLD ] FOR <query>
`,
    //line sql.y: 9231
    SeeAlso: `CLOSE, FETCH
`,
  },
  //line sql.y: 9300
  `FETCH`: {
    ShortDescription: `fetch rows from a SQL cursor`,
    //line sql.y: 9301
    Category: hMisc,
    //line sql.y: 9302
    Text: `FETCH [ direction [ FROM | IN ] ] <name>
`,
    //line sql.y: 9303
    SeeAlso: `MOVE, CLOSE, DECLARE
`,
  },
  //line sql.y: 9313
  `MOVE`: {
    ShortDescription: `move a SQL cursor without fetching rows`,
    //line sql.y: 9314
    Category: hMisc,
    //line sql.y: 9315
    Text: `MOVE [ direction [ FROM | IN ] ] <name>
`,
    //line sql.y: 9316
    SeeAlso: `FETCH, CLOSE, DECLARE
`,
  },
  //line sql.y: 9452
  `SHOW SESSION`: {
    ShortDescription: `display session variables`,
    //line sql.y: 9453
    Category: hCfg,
    //line sql.y: 9454
    Text: `SHOW [SESSION] { <var> | ALL }
`,
    //line sql.y: 9455
    SeeAlso: `WEBDOCS/show-vars.html
`,
  },
  //line sql.y: 9500
  `SHOW STATISTICS`: {
    ShortDescription: `display table statistics`,
    //line sql.y: 9501
    Category: hMisc,
    //line sql.y: 9502
    Text: `SHOW STATISTICS [USING JSON] FOR TABLE <table_name> [WITH FORECAST]

Returns the available statistics for a table. The statistics can include a
histogram ID, which can be used with SHOW HISTOGRAM.

If USING JSON is specified, the statistics and histograms are encoded in JSON
format.

If WITH FORECAST is specified, forecasted statistics are included if
available.

`,
    //line sql.y: 9513
    SeeAlso: `SHOW HISTOGRAM
`,
  },
  //line sql.y: 9535
  `SHOW HISTOGRAM`: {
    ShortDescription: `display histogram (experimental)`,
    //line sql.y: 9536
    Category: hExperimental,
    //line sql.y: 9537
    Text: `SHOW HISTOGRAM <histogram_id>

Returns the data in the histogram with the
given ID (as returned by SHOW STATISTICS).
`,
    //line sql.y: 9541
    SeeAlso: `SHOW STATISTICS
`,
  },
  //line sql.y: 9554
  `SHOW BACKUP`: {
    ShortDescription: `list backup contents`,
    //line sql.y: 9555
    Category: hCCL,
    //line sql.y: 9556
    Text: `SHOW BACKUP [SCHEMAS|FILES|RANGES] <location>
`,
    //line sql.y: 9557
    SeeAlso: `WEBDOCS/show-backup.html
`,
  },
  //line sql.y: 9768
  `SHOW CLUSTER SETTING`: {
    ShortDescription: `display cluster settings`,
    //line sql.y: 9769
    Category: hCfg,
    //line sql.y: 9770
    Text: `
SHOW CLUSTER SETTING <var> [ FOR VIRTUAL CLUSTER <virtual_cluster_spec> ]
SHOW [ PUBLIC | ALL ] CLUSTER SETTINGS [ FOR VIRTUAL CLUSTER <virtual_cluster_spec> ]
`,
    //line sql.y: 9773
    SeeAlso: `WEBDOCS/cluster-settings.html
`,
  },
  //line sql.y: 9823
  `SHOW COLUMNS`: {
    ShortDescription: `list columns in relation`,
    //line sql.y: 9824
    Category: hDDL,
    //line sql.y: 9825
    Text: `SHOW COLUMNS FROM <tablename>
`,
    //line sql.y: 9826
    SeeAlso: `WEBDOCS/show-columns.html
`,
  },
  //line sql.y: 9834
  `SHOW PARTITIONS`: {
    ShortDescription: `list partition information`,
    //line sql.y: 9835
    Category: hDDL,
    //line sql.y: 9836
    Text: `SHOW PARTITIONS FROM { TABLE <table> | INDEX <index> | DATABASE <database> }
`,
    //line sql.y: 9837
    SeeAlso: `WEBDOCS/show-partitions.html
`,
  },
  //line sql.y: 9857
  `SHOW DATABASES`: {
    ShortDescription: `list databases`,
    //line sql.y: 9858
    Category: hDDL,
    //line sql.y: 9859
    Text: `SHOW DATABASES
`,
    //line sql.y: 9860
    SeeAlso: `WEBDOCS/show-databases.html
`,
  },
  //line sql.y: 9868
  `SHOW DEFAULT PRIVILEGES`: {
    ShortDescription: `list default privileges`,
    //line sql.y: 9869
    Category: hDDL,
    //line sql.y: 9870
    Text: `SHOW DEFAULT PRIVILEGES
`,
    //line sql.y: 9871
    SeeAlso: `WEBDOCS/show-default-privileges
`,
  },
  //line sql.y: 9894
  `SHOW ENUMS`: {
    ShortDescription: `list enums`,
    //line sql.y: 9895
    Category: hMisc,
    //line sql.y: 9896
    Text: `SHOW ENUMS
`,
  },
  //line sql.y: 9924
  `SHOW EXTERNAL CONNECTIONS`: {
    ShortDescription: `list external connections`,
    //line sql.y: 9925
    Category: hMisc,
    //line sql.y: 9926
    Text: `
SHOW EXTERNAL CONNECTIONS
SHOW EXTERNAL CONNECTION <connection_name>
`,
  },
  //line sql.y: 9941
  `SHOW TYPES`: {
    ShortDescription: `list user defined types`,
    //line sql.y: 9942
    Category: hMisc,
    //line sql.y: 9943
    Text: `SHOW TYPES [WITH_COMMENT]
`,
  },
  //line sql.y: 9951
  `SHOW GRANTS`: {
    ShortDescription: `list grants`,
    //line sql.y: 9952
    Category: hPriv,
    //line sql.y: 9953
    Text: `
Show privilege grants:
  SHOW GRANTS [ON <targets...>] [FOR <users...>]
Show role grants:
  SHOW GRANTS ON ROLE [<roles...>] [FOR <grantees...>]

`,
    //line sql.y: 9959
    SeeAlso: `WEBDOCS/show-grants.html
`,
  },
  //line sql.y: 9979
  `SHOW INDEXES`: {
    ShortDescription: `list indexes`,
    //line sql.y: 9980
    Category: hDDL,
    //line sql.y: 9981
    Text: `SHOW INDEXES FROM { <tablename> | DATABASE <database_name> } [WITH COMMENT]
`,
    //line sql.y: 9982
    SeeAlso: `WEBDOCS/show-index.html
`,
  },
  //line sql.y: 10012
  `SHOW COMMIT TIMESTAMP`: {
    ShortDescription: `show timestamp commit timestamp of last transaction`,
    //line sql.y: 10013
    Category: hMisc,
    //line sql.y: 10014
    Text: `SHOW COMMIT TIMESTAMP

Shows the commit timestamp of the last committed transaction if not currently
in a transaction. If currently in a transaction, implicitly commits the
transaction, returning any errors which may have occurred during the commit.
The transaction state will remain open from the perspective of the client,
meaning that a COMMIT must be issued to move the connection back to a state
where new statements may be issued.
`,
  },
  //line sql.y: 10028
  `SHOW CONSTRAINTS`: {
    ShortDescription: `list constraints`,
    //line sql.y: 10029
    Category: hDDL,
    //line sql.y: 10030
    Text: `SHOW CONSTRAINTS FROM <tablename>
`,
    //line sql.y: 10031
    SeeAlso: `WEBDOCS/show-constraints.html
`,
  },
  //line sql.y: 10044
  `SHOW TRIGGERS`: {
    ShortDescription: `list triggers on a table`,
    //line sql.y: 10045
    Category: hDDL,
    //line sql.y: 10046
    Text: `SHOW TRIGGERS FROM <tablename>
TODO(drewk): Add docs link.
`,
  },
  //line sql.y: 10056
  `SHOW STATEMENTS`: {
    ShortDescription: `list running statements`,
    //line sql.y: 10057
    Category: hMisc,
    //line sql.y: 10058
    Text: `SHOW [ALL] [CLUSTER | LOCAL] STATEMENTS
`,
    //line sql.y: 10059
    SeeAlso: `CANCEL QUERIES
`,
  },
  //line sql.y: 10086
  `SHOW JOBS`: {
    ShortDescription: `list background jobs`,
    //line sql.y: 10087
    Category: hMisc,
    //line sql.y: 10088
    Text: `
SHOW [AUTOMATIC | CHANGEFEED] JOBS [select clause] [WITH EXECUTION DETAILS]
SHOW JOBS FOR SCHEDULES [select clause]
SHOW [CHANGEFEED] JOB <jobid> [WITH EXECUTION DETAILS]
`,
    //line sql.y: 10092
    SeeAlso: `CANCEL JOBS, PAUSE JOBS, RESUME JOBS
`,
  },
  //line sql.y: 10228
  `SHOW SCHEDULES`: {
    ShortDescription: `list periodic schedules`,
    //line sql.y: 10229
    Category: hMisc,
    //line sql.y: 10230
    Text: `
SHOW [RUNNING | PAUSED] SCHEDULES [FOR BACKUP]
SHOW SCHEDULE <schedule_id>
`,
    //line sql.y: 10233
    SeeAlso: `PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES, EXECUTE SCHEDULES
`,
  },
  //line sql.y: 10288
  `SHOW TRACE`: {
    ShortDescription: `display an execution trace`,
    //line sql.y: 10289
    Category: hMisc,
    //line sql.y: 10290
    Text: `
SHOW [COMPACT] [KV] TRACE FOR SESSION
`,
    //line sql.y: 10292
    SeeAlso: `EXPLAIN
`,
  },
  //line sql.y: 10315
  `SHOW SESSIONS`: {
    ShortDescription: `list open client sessions`,
    //line sql.y: 10316
    Category: hMisc,
    //line sql.y: 10317
    Text: `SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
`,
    //line sql.y: 10318
    SeeAlso: `CANCEL SESSIONS
`,
  },
  //line sql.y: 10331
  `SHOW TABLES`: {
    ShortDescription: `list tables`,
    //line sql.y: 10332
    Category: hDDL,
    //line sql.y: 10333
    Text: `SHOW TABLES [FROM <databasename> [ . <schemaname> ] ] [WITH COMMENT]
`,
    //line sql.y: 10334
    SeeAlso: `WEBDOCS/show-tables.html
`,
  },
  //line sql.y: 10362
  `SHOW FUNCTIONS`: {
    ShortDescription: `list functions`,
    //line sql.y: 10363
    Category: hDDL,
    //line sql.y: 10364
    Text: `SHOW FUNCTIONS [FROM <databasename> [ . <schemaname> ] ]
`,
  },
  //line sql.y: 10390
  `SHOW PROCEDURES`: {
    ShortDescription: `list procedures`,
    //line sql.y: 10391
    Category: hDDL,
    //line sql.y: 10392
    Text: `SHOW PROCEDURES [FROM <databasename> [ . <schemaname> ] ]
`,
  },
  //line sql.y: 10418
  `SHOW TRANSACTIONS`: {
    ShortDescription: `list open client transactions across the cluster`,
    //line sql.y: 10419
    Category: hMisc,
    //line sql.y: 10420
    Text: `SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
`,
  },
  //line sql.y: 10437
  `SHOW SCHEMAS`: {
    ShortDescription: `list schemas`,
    //line sql.y: 10438
    Category: hDDL,
    //line sql.y: 10439
    Text: `SHOW SCHEMAS [FROM <databasename> ] [WITH COMMENT]
`,
  },
  //line sql.y: 10451
  `SHOW SEQUENCES`: {
    ShortDescription: `list sequences`,
    //line sql.y: 10452
    Category: hDDL,
    //line sql.y: 10453
    Text: `SHOW SEQUENCES [FROM <databasename> ]
`,
  },
  //line sql.y: 10465
  `SHOW SYNTAX`: {
    ShortDescription: `analyze SQL syntax`,
    //line sql.y: 10466
    Category: hMisc,
    //line sql.y: 10467
    Text: `SHOW SYNTAX <string>
`,
  },
  //line sql.y: 10486
  `SHOW POLICIES`: {
    ShortDescription: `list row-level security policies defined for a table`,
    //line sql.y: 10487
    Category: hDDL,
    //line sql.y: 10488
    Text: `SHOW POLICIES FOR <table_name>
`,
  },
  //line sql.y: 10518
  `SHOW SAVEPOINT`: {
    ShortDescription: `display current savepoint properties`,
    //line sql.y: 10519
    Category: hCfg,
    //line sql.y: 10520
    Text: `SHOW SAVEPOINT STATUS
`,
  },
  //line sql.y: 10528
  `SHOW TRANSACTION`: {
    ShortDescription: `display current transaction properties`,
    //line sql.y: 10529
    Category: hCfg,
    //line sql.y: 10530
    Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
    //line sql.y: 10531
    SeeAlso: `WEBDOCS/show-vars.html
`,
  },
  //line sql.y: 10550
  `SHOW TRANSFER`: {
    ShortDescription: `display session state for connection migration`,
    //line sql.y: 10551
    Category: hMisc,
    //line sql.y: 10552
    Text: `SHOW TRANSFER STATE [ WITH '<transfer_key>' ]
`,
  },
  //line sql.y: 10564
  `SHOW CREATE`: {
    ShortDescription: `display the CREATE statement for one or more database objects`,
    //line sql.y: 10565
    Category: hDDL,
    //line sql.y: 10566
    Text: `
SHOW CREATE [ TABLE | SEQUENCE | VIEW | DATABASE | FUNCTION | PROCEDURE ] <object_name>
SHOW CREATE TRIGGER <trigger_name> ON <table_name>
SHOW CREATE [ SECONDARY ] INDEXES FROM <table_name>
SHOW CREATE ALL SCHEMAS
SHOW CREATE ALL TABLES
SHOW CREATE ALL TRIGGERS
SHOW CREATE ALL TYPES
SHOW CREATE ALL ROUTINES
`,
    //line sql.y: 10575
    SeeAlso: `WEBDOCS/show-create.html
`,
  },
  //line sql.y: 10684
  `SHOW CREATE SCHEDULES`: {
    ShortDescription: `list CREATE statements for scheduled jobs`,
    //line sql.y: 10685
    Category: hDDL,
    //line sql.y: 10686
    Text: `
SHOW CREATE ALL SCHEDULES
SHOW CREATE SCHEDULE <schedule_id>
`,
    //line sql.y: 10689
    SeeAlso: `SHOW SCHEDULES, PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES, EXECUTE SCHEDULES
`,
  },
  //line sql.y: 10702
  `SHOW CREATE EXTERNAL CONNECTIONS`: {
    ShortDescription: `list CREATE statements for external connections`,
    //line sql.y: 10703
    Category: hDDL,
    //line sql.y: 10704
    Text: `
SHOW CREATE ALL EXTERNAL CONNECTIONS
SHOW CREATE EXTERNAL CONNECTION <connection_name>
`,
  },
  //line sql.y: 10719
  `SHOW USERS`: {
    ShortDescription: `list defined users`,
    //line sql.y: 10720
    Category: hPriv,
    //line sql.y: 10721
    Text: `
SHOW USERS [WITH <options>] [LIMIT <n>]

Options:
  SOURCE = <string>
  LAST LOGIN BEFORE <expr>
`,
    //line sql.y: 10727
    SeeAlso: `CREATE USER, DROP USER, WEBDOCS/show-users.html
`,
  },
  //line sql.y: 10770
  `SHOW DEFAULT SESSION VARIABLES FOR ROLE`: {
    ShortDescription: `list default session variables for role`,
    //line sql.y: 10771
    Category: hPriv,
    //line sql.y: 10772
    Text: `SHOW DEFAULT SESSION VARIABLES FOR ROLE <name>
`,
  },
  //line sql.y: 10788
  `SHOW ROLES`: {
    ShortDescription: `list defined roles`,
    //line sql.y: 10789
    Category: hPriv,
    //line sql.y: 10790
    Text: `
SHOW ROLES [WITH <options>] [LIMIT <n>]

Options:
  SOURCE = <string>
  LAST LOGIN BEFORE <expr>
`,
    //line sql.y: 10796
    SeeAlso: `CREATE ROLE, ALTER ROLE, DROP ROLE
`,
  },
  //line sql.y: 10807
  `SHOW ZONE CONFIGURATION`: {
    ShortDescription: `display current zone configuration`,
    //line sql.y: 10808
    Category: hCfg,
    //line sql.y: 10809
    Text: `SHOW ZONE CONFIGURATION FROM [ RANGE | DATABASE | TABLE | INDEX ] <name>
SHOW ZONE CONFIGURATION FROM PARTITION OF [ INDEX | TABLE ] <name>
SHOW [ALL] ZONE CONFIGURATIONS
`,
    //line sql.y: 10812
    SeeAlso: `WEBDOCS/show-zone-configurations.html
`,
  },
  //line sql.y: 10875
  `SHOW RANGE`: {
    ShortDescription: `show range information for a row`,
    //line sql.y: 10876
    Category: hMisc,
    //line sql.y: 10877
    Text: `
SHOW RANGE FROM TABLE <tablename> FOR ROW (value1, value2, ...)
SHOW RANGE FROM INDEX [ <tablename> @ ] <indexname> FOR ROW (value1, value2, ...)
`,
  },
  //line sql.y: 10898
  `SHOW RANGES`: {
    ShortDescription: `list ranges`,
    //line sql.y: 10899
    Category: hMisc,
    //line sql.y: 10900
    Text: `
SHOW CLUSTER RANGES                                  [ WITH <options...> ]
SHOW RANGES FROM DATABASE <databasename>             [ WITH <options...> ]
SHOW RANGES FROM CURRENT_CATALOG                     [ WITH <options...> ]
SHOW RANGES FROM TABLE   <tablename>                 [ WITH <options...> ]
SHOW RANGES FROM INDEX [ <tablename> @ ] <indexname> [ WITH <options...> ]

Options:
  INDEXES: list indexes contained per range
  TABLES:  list tables contained per range
  DETAILS: add range size, leaseholder and other details
  KEYS:    include binary start/end keys
  ZONE:    include the resolved zone configuration per range
  EXPLAIN: show the SQL queries that produces the result

Note: the availability of some of the options listed above is subject
to cluster configuration. See the documentation for details.

`,
    //line sql.y: 10918
    SeeAlso: `WEBDOCS/show-ranges.html
`,
  },
  //line sql.y: 11001
  `SHOW SURVIVAL GOAL`: {
    ShortDescription: `list survival goals`,
    //line sql.y: 11002
    Category: hDDL,
    //line sql.y: 11003
    Text: `
SHOW SURVIVAL GOAL FROM DATABASE
SHOW SURVIVAL GOAL FROM DATABASE <database>
`,
  },
  //line sql.y: 11018
  `SHOW REGIONS`: {
    ShortDescription: `list regions`,
    //line sql.y: 11019
    Category: hDDL,
    //line sql.y: 11020
    Text: `
SHOW REGIONS
SHOW REGIONS FROM ALL DATABASES
SHOW REGIONS FROM CLUSTER
SHOW REGIONS FROM DATABASE
SHOW REGIONS FROM DATABASE <database>
`,
  },
  //line sql.y: 11141
  `SHOW STATEMENT HINTS`: {
    ShortDescription: `list statement hints for a fingerprint`,
    //line sql.y: 11142
    Category: hMisc,
    //line sql.y: 11143
    Text: `
SHOW STATEMENT HINTS FOR <string>
SHOW STATEMENT HINTS WITH DETAILS FOR <string>

Shows statement hints stored in system.statement_hints for the given
query string (which may be a string literal, dollar-quoted string, or
expression). WITH DETAILS includes decoded hint-specific information.

Examples:
  SHOW STATEMENT HINTS FOR 'SELECT * FROM t WHERE x = 1'
  SHOW STATEMENT HINTS FOR $$ SELECT * FROM t WHERE x = 'value' $$
  SHOW STATEMENT HINTS FOR $1
`,
  },
  //line sql.y: 11505
  `PAUSE`: {
    ShortDescription: `pause background tasks`,
    //line sql.y: 11506
    Category: hGroup,
    //line sql.y: 11507
    Text: `PAUSE JOBS, PAUSE SCHEDULES, PAUSE ALL JOBS
`,
  },
  //line sql.y: 11514
  `RESUME`: {
    ShortDescription: `resume background tasks`,
    //line sql.y: 11515
    Category: hGroup,
    //line sql.y: 11516
    Text: `RESUME JOBS, RESUME SCHEDULES, RESUME ALL BACKUP JOBS
`,
  },
  //line sql.y: 11523
  `RESUME ALL JOBS`: {
    ShortDescription: `resume background jobs`,
    //line sql.y: 11524
    Category: hMisc,
    //line sql.y: 11525
    Text: `
RESUME ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
  },
  //line sql.y: 11534
  `PAUSE JOBS`: {
    ShortDescription: `pause selected background jobs`,
    //line sql.y: 11535
    Category: hMisc,
    //line sql.y: 11536
    Text: `
PAUSE JOBS <selectclause>
PAUSE JOB <jobid>
`,
    //line sql.y: 11539
    SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
  },
  //line sql.y: 11588
  `PAUSE SCHEDULES`: {
    ShortDescription: `pause scheduled jobs`,
    //line sql.y: 11589
    Category: hMisc,
    //line sql.y: 11590
    Text: `
PAUSE SCHEDULES <selectclause>
  select clause: select statement returning schedule id to pause.
PAUSE SCHEDULE <scheduleID>
`,
    //line sql.y: 11594
    SeeAlso: `RESUME SCHEDULES, EXECUTE SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
  },
  //line sql.y: 11615
  `PAUSE ALL JOBS`: {
    ShortDescription: `pause all background jobs`,
    //line sql.y: 11616
    Category: hMisc,
    //line sql.y: 11617
    Text: `
PAUSE ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
  },
  //line sql.y: 11627
  `CREATE SCHEMA`: {
    ShortDescription: `create a new schema`,
    //line sql.y: 11628
    Category: hDDL,
    //line sql.y: 11629
    Text: `
CREATE SCHEMA [IF NOT EXISTS] { [<databasename>.]<schemaname> | [[<databasename>.]<schemaname>] AUTHORIZATION <rolename> }
`,
  },
  //line sql.y: 11662
  `ALTER SCHEMA`: {
    ShortDescription: `alter an existing schema`,
    //line sql.y: 11663
    Category: hDDL,
    //line sql.y: 11664
    Text: `

Commands:
  ALTER SCHEMA ... RENAME TO <newschemaname>
  ALTER SCHEMA ... OWNER TO {<newowner> | CURRENT_USER | SESSION_USER }
`,
  },
  //line sql.y: 11690
  `CREATE TABLE`: {
    ShortDescription: `create a new table`,
    //line sql.y: 11691
    Category: hDDL,
    //line sql.y: 11692
    Text: `
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<on_commit>]
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source> [<on commit>]

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE | INVERTED | VECTOR] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [USING HASH] [{STORING | INCLUDE | COVERING} ( <colnames...> )]
   FAMILY [<name>] ( <colnames...> )
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> ) [USING HASH]
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
   UNIQUE ( <colnames...> ) [{STORING | INCLUDE | COVERING} ( <colnames...> )]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | NOT VISIBLE | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr> | ON UPDATE <expr> | GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [( <opt_sequence_option_list> )]}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
  COLLATE <collationname>
  AS ( <expr> ) { STORED | VIRTUAL }

On commit clause:
   ON COMMIT {PRESERVE ROWS | DROP | DELETE ROWS}

`,
    //line sql.y: 11719
    SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE,
WEBDOCS/create-table.html
WEBDOCS/create-table-as.html
`,
  },
  //line sql.y: 12729
  `CREATE SEQUENCE`: {
    ShortDescription: `create a new sequence`,
    //line sql.y: 12730
    Category: hDDL,
    //line sql.y: 12731
    Text: `
CREATE [TEMPORARY | TEMP] SEQUENCE <seqname>
  [AS <typename>]
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START [WITH] <start>]
  [CACHE <cache>]
  [NO CYCLE]
  [VIRTUAL]

`,
    //line sql.y: 12742
    SeeAlso: `CREATE TABLE
`,
  },
  //line sql.y: 12836
  `TRUNCATE`: {
    ShortDescription: `empty one or more tables`,
    //line sql.y: 12837
    Category: hDML,
    //line sql.y: 12838
    Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
    //line sql.y: 12839
    SeeAlso: `WEBDOCS/truncate.html
`,
  },
  //line sql.y: 12863
  `CREATE ROLE`: {
    ShortDescription: `define a new role`,
    //line sql.y: 12864
    Category: hPriv,
    //line sql.y: 12865
    Text: `CREATE ROLE [IF NOT EXISTS] <name> [ [WITH] <OPTIONS...> ]
`,
    //line sql.y: 12866
    SeeAlso: `ALTER ROLE, DROP ROLE, SHOW ROLES
`,
  },
  //line sql.y: 12878
  `ALTER ROLE`: {
    ShortDescription: `alter a role`,
    //line sql.y: 12879
    Category: hPriv,
    //line sql.y: 12880
    Text: `
ALTER ROLE <name> [WITH] <options...>
ALTER ROLE { name | ALL } [ IN DATABASE database_name ] SET var { TO | = } { value | DEFAULT }
ALTER ROLE { name | ALL } [ IN DATABASE database_name ] RESET { var | ALL }
`,
    //line sql.y: 12884
    SeeAlso: `CREATE ROLE, DROP ROLE, SHOW ROLES
`,
  },
  //line sql.y: 12962
  `CREATE VIEW`: {
    ShortDescription: `create a new view`,
    //line sql.y: 12963
    Category: hDDL,
    //line sql.y: 12964
    Text: `
CREATE [TEMPORARY | TEMP] VIEW [IF NOT EXISTS] <viewname> [( <colnames...> )] [WITH ( <option> [= <value>] [, ....] )] AS <source>
CREATE [TEMPORARY | TEMP] MATERIALIZED VIEW [IF NOT EXISTS] <viewname> [( <colnames...> )] AS <source> [WITH [NO] DATA]

Options:
  security_invoker [= { true | false | 1 | 0 }]: controls view permissions (defaults to true if specified without value)
`,
    //line sql.y: 12970
    SeeAlso: `CREATE TABLE, SHOW CREATE, WEBDOCS/create-view.html
`,
  },
  //line sql.y: 13259
  `CREATE TYPE`: {
    ShortDescription: `create a type`,
    //line sql.y: 13260
    Category: hDDL,
    //line sql.y: 13261
    Text: `CREATE TYPE [IF NOT EXISTS] <type_name> AS ENUM (...)
`,
  },
  //line sql.y: 13409
  `CREATE INDEX`: {
    ShortDescription: `create a new index`,
    //line sql.y: 13410
    Category: hDDL,
    //line sql.y: 13411
    Text: `
CREATE [UNIQUE | INVERTED | VECTOR] INDEX [CONCURRENTLY] [IF NOT EXISTS] [<idxname>]
       ON <tablename> ( <colname> [ASC | DESC] [, ...] )
       [USING HASH] [STORING ( <colnames...> )]
       [PARTITION BY <partition params>]
       [WITH <storage_parameter_list] [WHERE <where_conds...>]

`,
    //line sql.y: 13418
    SeeAlso: `CREATE TABLE, SHOW INDEXES, SHOW CREATE,
WEBDOCS/create-index.html
`,
  },
  //line sql.y: 14118
  `ALTER DEFAULT PRIVILEGES`: {
    ShortDescription: `alter default privileges on an object`,
    //line sql.y: 14119
    Category: hDDL,
    //line sql.y: 14120
    Text: `

Commands:
  ALTER DEFAULT PRIVILEGES [ FOR { ROLE | USER } target_roles... ] [ IN SCHEMA schema_name...] abbreviated_grant_or_revoke
`,
  },
  //line sql.y: 14267
  `RELEASE`: {
    ShortDescription: `complete a sub-transaction`,
    //line sql.y: 14268
    Category: hTxn,
    //line sql.y: 14269
    Text: `RELEASE [SAVEPOINT] <savepoint name>
`,
    //line sql.y: 14270
    SeeAlso: `SAVEPOINT, WEBDOCS/savepoint.html
`,
  },
  //line sql.y: 14278
  `RESUME JOBS`: {
    ShortDescription: `resume selected background jobs`,
    //line sql.y: 14279
    Category: hMisc,
    //line sql.y: 14280
    Text: `
RESUME JOBS <selectclause>
RESUME JOB <jobid>
`,
    //line sql.y: 14283
    SeeAlso: `SHOW JOBS, CANCEL JOBS, PAUSE JOBS
`,
  },
  //line sql.y: 14305
  `RESUME SCHEDULES`: {
    ShortDescription: `resume executing scheduled jobs`,
    //line sql.y: 14306
    Category: hMisc,
    //line sql.y: 14307
    Text: `
RESUME SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

RESUME SCHEDULE <scheduleID>

`,
    //line sql.y: 14313
    SeeAlso: `PAUSE SCHEDULES, EXECUTE SCHEDULES, SHOW JOBS, RESUME JOBS
`,
  },
  //line sql.y: 14334
  `DROP SCHEDULES`: {
    ShortDescription: `destroy specified schedules`,
    //line sql.y: 14335
    Category: hMisc,
    //line sql.y: 14336
    Text: `
DROP SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

DROP SCHEDULE <scheduleID>

`,
    //line sql.y: 14342
    SeeAlso: `PAUSE SCHEDULES, EXECUTE SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
  },
  //line sql.y: 14363
  `EXECUTE SCHEDULES`: {
    ShortDescription: `execute scheduled jobs immediately`,
    //line sql.y: 14364
    Category: hMisc,
    //line sql.y: 14365
    Text: `
EXECUTE SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to execute.

EXECUTE SCHEDULE <scheduleID>

`,
    //line sql.y: 14371
    SeeAlso: `PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES, SHOW JOBS
`,
  },
  //line sql.y: 14392
  `SAVEPOINT`: {
    ShortDescription: `start a sub-transaction`,
    //line sql.y: 14393
    Category: hTxn,
    //line sql.y: 14394
    Text: `SAVEPOINT <savepoint name>
`,
    //line sql.y: 14395
    SeeAlso: `RELEASE, WEBDOCS/savepoint.html
`,
  },
  //line sql.y: 14413
  `BEGIN`: {
    ShortDescription: `start a transaction`,
    //line sql.y: 14414
    Category: hTxn,
    //line sql.y: 14415
    Text: `
BEGIN [TRANSACTION | WORK] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { READ COMMITTED | REPEATABLE READ | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
    //line sql.y: 14423
    SeeAlso: `COMMIT, ROLLBACK, WEBDOCS/begin-transaction.html
`,
  },
  //line sql.y: 14433
  `COMMIT`: {
    ShortDescription: `commit the current transaction`,
    //line sql.y: 14434
    Category: hTxn,
    //line sql.y: 14435
    Text: `
COMMIT [TRANSACTION | WORK] [AND [NO] CHAIN]
END [TRANSACTION | WORK] [AND [NO] CHAIN]
`,
    //line sql.y: 14438
    SeeAlso: `BEGIN, ROLLBACK, WEBDOCS/commit-transaction.html
`,
  },
  //line sql.y: 14452
  `ROLLBACK`: {
    ShortDescription: `abort the current (sub-)transaction`,
    //line sql.y: 14453
    Category: hTxn,
    //line sql.y: 14454
    Text: `
ROLLBACK [TRANSACTION | WORK] [AND [NO] CHAIN]
ROLLBACK [TRANSACTION | WORK] TO [SAVEPOINT] <savepoint name>
`,
    //line sql.y: 14457
    SeeAlso: `BEGIN, COMMIT, SAVEPOINT, WEBDOCS/rollback-transaction.html
`,
  },
  //line sql.y: 14607
  `PREPARE TRANSACTION`: {
    ShortDescription: `prepare the current transaction for two-phase commit`,
    //line sql.y: 14608
    Category: hTxn,
    //line sql.y: 14609
    Text: `PREPARE TRANSACTION <transaction-id>
`,
    //line sql.y: 14610
    SeeAlso: `COMMIT PREPARED, ROLLBACK PREPARED
`,
  },
  //line sql.y: 14617
  `COMMIT PREPARED`: {
    ShortDescription: `commit the named transaction as part of two-phase commit`,
    //line sql.y: 14618
    Category: hTxn,
    //line sql.y: 14619
    Text: `COMMIT PREPARED <transaction-id>
`,
    //line sql.y: 14620
    SeeAlso: `PREPARE TRANSACTION, ROLLBACK PREPARED
`,
  },
  //line sql.y: 14627
  `ROLLBACK PREPARED`: {
    ShortDescription: `rollback the named transaction as part of two-phase commit`,
    //line sql.y: 14628
    Category: hTxn,
    //line sql.y: 14629
    Text: `ROLLBACK PREPARED <transaction-id>
`,
    //line sql.y: 14630
    SeeAlso: `PREPARE TRANSACTION, COMMIT PREPARED
`,
  },
  //line sql.y: 14637
  `CREATE DATABASE`: {
    ShortDescription: `create a new database`,
    //line sql.y: 14638
    Category: hDDL,
    //line sql.y: 14639
    Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
    //line sql.y: 14640
    SeeAlso: `WEBDOCS/create-database.html
`,
  },
  //line sql.y: 14845
  `INSERT`: {
    ShortDescription: `create new rows in a table`,
    //line sql.y: 14846
    Category: hDML,
    //line sql.y: 14847
    Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT {
         [( <colnames...> )] [WHERE <arbiter_predicate>] DO NOTHING |
         ( <colnames...> ) [WHERE <index_predicate>] DO UPDATE SET ... [WHERE <expr>]
       }
       [RETURNING <exprs...>]
`,
    //line sql.y: 14855
    SeeAlso: `UPSERT, UPDATE, DELETE, WEBDOCS/insert.html
`,
  },
  //line sql.y: 14874
  `UPSERT`: {
    ShortDescription: `create or replace rows in a table`,
    //line sql.y: 14875
    Category: hDML,
    //line sql.y: 14876
    Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
    //line sql.y: 14880
    SeeAlso: `INSERT, UPDATE, DELETE, WEBDOCS/upsert.html
`,
  },
  //line sql.y: 15014
  `UPDATE`: {
    ShortDescription: `update rows of a table`,
    //line sql.y: 15015
    Category: hDML,
    //line sql.y: 15016
    Text: `
UPDATE <tablename> [[AS] <name>]
       SET ...
       [FROM <source>]
       [WHERE <expr>]
       [ORDER BY <exprs...>]
       [LIMIT <expr>]
       [RETURNING <exprs...>]
`,
    //line sql.y: 15024
    SeeAlso: `INSERT, UPSERT, DELETE, WEBDOCS/update.html
`,
  },
  //line sql.y: 15080
  `REASSIGN OWNED BY`: {
    ShortDescription: `change ownership of all objects`,
    //line sql.y: 15081
    Category: hPriv,
    //line sql.y: 15082
    Text: `REASSIGN OWNED BY {<name> | CURRENT_USER | SESSION_USER}[,...]
TO {<name> | CURRENT_USER | SESSION_USER}
`,
    //line sql.y: 15084
    SeeAlso: `DROP OWNED BY
`,
  },
  //line sql.y: 15095
  `DROP OWNED BY`: {
    ShortDescription: `remove database objects owned by role(s).`,
    //line sql.y: 15096
    Category: hPriv,
    //line sql.y: 15097
    Text: `DROP OWNED BY {<name> | CURRENT_USER | SESSION_USER}[,...]
[RESTRICT | CASCADE]
`,
    //line sql.y: 15099
    SeeAlso: `REASSIGN OWNED BY
`,
  },
  //line sql.y: 15279
  `<SELECTCLAUSE>`: {
    ShortDescription: `access tabular data`,
    //line sql.y: 15280
    Category: hDML,
    //line sql.y: 15281
    Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
  },
  //line sql.y: 15292
  `SELECT`: {
    ShortDescription: `retrieve rows from a data source and compute a result`,
    //line sql.y: 15293
    Category: hDML,
    //line sql.y: 15294
    Text: `
SELECT [DISTINCT [ ON ( <expr> [ , ... ] ) ] ]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
    //line sql.y: 15306
    SeeAlso: `WEBDOCS/select-clause.html
`,
  },
  //line sql.y: 15380
  `TABLE`: {
    ShortDescription: `select an entire table`,
    //line sql.y: 15381
    Category: hDML,
    //line sql.y: 15382
    Text: `TABLE <tablename>
`,
    //line sql.y: 15383
    SeeAlso: `SELECT, VALUES, WEBDOCS/table-expressions.html
`,
  },
  //line sql.y: 15784
  `VALUES`: {
    ShortDescription: `select a given set of values`,
    //line sql.y: 15785
    Category: hDML,
    //line sql.y: 15786
    Text: `VALUES ( <exprs...> ) [, ...]
`,
    //line sql.y: 15787
    SeeAlso: `SELECT, TABLE, WEBDOCS/table-expressions.html
`,
  },
  //line sql.y: 15931
  `<SOURCE>`: {
    ShortDescription: `define a data source for SELECT`,
    //line sql.y: 15932
    Category: hDML,
    //line sql.y: 15933
    Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexflags> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> [ <jointype> ] JOIN <source> ON <expr>
  <source> [ <jointype> ] JOIN <source> USING ( <colnames...> )
  <source> NATURAL [ <jointype> ] JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index flags:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'
  '{' NO_ZIGZAG_JOIN [, ...] '}'
  '{' NO_FULL_SCAN [, ...] '}'
  '{' AVOID_FULL_SCAN [, ...] '}'
  '{' IGNORE_FOREIGN_KEYS [, ...] '}'
  '{' FORCE_ZIGZAG = <idxname> [, ...]  '}'

Join types:
  { INNER | { LEFT | RIGHT | FULL } [OUTER] } [ { HASH | MERGE | LOOKUP | INVERTED | STRAIGHT } ]

`,
    //line sql.y: 15959
    SeeAlso: `WEBDOCS/table-expressions.html
`,
  },
}
