// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqlproxy/tenant/directory.proto

package tenant

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PodState gives the current state of a tenant pod, so that the proxy knows
// how/where to route traffic.
//
// NOTE: This is not the same as the Kubernetes Pod Status.
type PodState int32

const (
	// UNKNOWN indicates that the pod's state is not known. This is used as the
	// default value for PodState. All pods returned by the tenant directory
	// should have a proper state.
	UNKNOWN PodState = 0
	// RUNNING indicates the pod may have active SQL connections and is ready to
	// accept new SQL connections.
	//
	// NOTE: The proxy must still be prepared to retry connections against a
	// running pod in case of transient failures.
	RUNNING PodState = 1
	// DRAINING indicates that the pod may still have active SQL connections to
	// it, but is in the process of shedding those connections so that it can be
	// terminated. No new connections should be routed to the pod. In addition,
	// the proxy will begin migrating existing connections to other RUNNING pods
	// if they exist.
	DRAINING PodState = 2
	// DELETING indicates that the pod is being terminated. This state is only
	// used by WatchPods.
	DELETING PodState = 3
)

var PodState_name = map[int32]string{
	0: "UNKNOWN",
	1: "RUNNING",
	2: "DRAINING",
	3: "DELETING",
}

var PodState_value = map[string]int32{
	"UNKNOWN":  0,
	"RUNNING":  1,
	"DRAINING": 2,
	"DELETING": 3,
}

func (x PodState) String() string {
	return proto.EnumName(PodState_name, int32(x))
}

func (PodState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{0}
}

// WatchEventType gives the state of a watch event.
type WatchEventType int32

const (
	// EVENT_UNKNOWN indicates that the event's state is not known. This is used
	// as the default value. All events returned by the tenant directory should
	// have a proper type.
	EVENT_UNKNOWN WatchEventType = 0
	// EVENT_ADDED indicates that the event corresponds to a new entry.
	EVENT_ADDED WatchEventType = 1
	// EVENT_MODIFIED indicates that the resource has been modified.
	EVENT_MODIFIED WatchEventType = 2
	// EVENT_DELETED indicates that the resource has been deleted, or is being
	// deleted.
	EVENT_DELETED WatchEventType = 3
)

var WatchEventType_name = map[int32]string{
	0: "EVENT_UNKNOWN",
	1: "EVENT_ADDED",
	2: "EVENT_MODIFIED",
	3: "EVENT_DELETED",
}

var WatchEventType_value = map[string]int32{
	"EVENT_UNKNOWN":  0,
	"EVENT_ADDED":    1,
	"EVENT_MODIFIED": 2,
	"EVENT_DELETED":  3,
}

func (x WatchEventType) String() string {
	return proto.EnumName(WatchEventType_name, int32(x))
}

func (WatchEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{1}
}

// Pod contains information about a tenant pod, such as its tenant owner,
// location, and state.
type Pod struct {
	// TenantID is the tenant that owns the pod.
	TenantID uint64 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Addr is the ip and port combination identifying the tenant pod, (e.g.
	// 132.130.1.11:34576).
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// State gives the current status of the tenant pod.
	State PodState `protobuf:"varint,3,opt,name=state,proto3,enum=cockroach.sqlproxy.tenant.PodState" json:"state,omitempty"`
	// StateTimestamp represents the timestamp that the state was last updated.
	StateTimestamp time.Time `protobuf:"bytes,5,opt,name=stateTimestamp,proto3,stdtime" json:"stateTimestamp"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{0}
}
func (m *Pod) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return m.Size()
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

// ListPodsRequest is used to query the server for the list of current pods of
// a given tenant.
type ListPodsRequest struct {
	// TenantID identifies the tenant for which the client is requesting a list of
	// the pods.
	TenantID uint64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (m *ListPodsRequest) Reset()         { *m = ListPodsRequest{} }
func (m *ListPodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPodsRequest) ProtoMessage()    {}
func (*ListPodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{1}
}
func (m *ListPodsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ListPodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsRequest.Merge(m, src)
}
func (m *ListPodsRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListPodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsRequest proto.InternalMessageInfo

// ListPodsResponse is sent back as a result of requesting the list of pods for
// a given tenant.
type ListPodsResponse struct {
	// Pods is the list of RUNNING and/or DRAINING pods for the requested tenant.
	// It does not include DELETING pods.
	Pods []*Pod `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
}

func (m *ListPodsResponse) Reset()         { *m = ListPodsResponse{} }
func (m *ListPodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPodsResponse) ProtoMessage()    {}
func (*ListPodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{2}
}
func (m *ListPodsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ListPodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsResponse.Merge(m, src)
}
func (m *ListPodsResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListPodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsResponse proto.InternalMessageInfo

// WatchPodsRequest is empty as we want to get all notifications.
type WatchPodsRequest struct {
}

func (m *WatchPodsRequest) Reset()         { *m = WatchPodsRequest{} }
func (m *WatchPodsRequest) String() string { return proto.CompactTextString(m) }
func (*WatchPodsRequest) ProtoMessage()    {}
func (*WatchPodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{3}
}
func (m *WatchPodsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WatchPodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WatchPodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchPodsRequest.Merge(m, src)
}
func (m *WatchPodsRequest) XXX_Size() int {
	return m.Size()
}
func (m *WatchPodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchPodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchPodsRequest proto.InternalMessageInfo

// WatchPodsResponse represents the pod notifications that the server sends to
// its clients when clients want to monitor the directory server activity.
type WatchPodsResponse struct {
	// Pod describes the tenant pod which has been added, modified, or deleted.
	Pod *Pod `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
}

func (m *WatchPodsResponse) Reset()         { *m = WatchPodsResponse{} }
func (m *WatchPodsResponse) String() string { return proto.CompactTextString(m) }
func (*WatchPodsResponse) ProtoMessage()    {}
func (*WatchPodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{4}
}
func (m *WatchPodsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WatchPodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WatchPodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchPodsResponse.Merge(m, src)
}
func (m *WatchPodsResponse) XXX_Size() int {
	return m.Size()
}
func (m *WatchPodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchPodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchPodsResponse proto.InternalMessageInfo

// EnsurePodRequest is used to ensure that at least one tenant pod is in the
// RUNNING state.
type EnsurePodRequest struct {
	// TenantID is the id of the tenant for which a RUNNING pod is requested.
	TenantID uint64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (m *EnsurePodRequest) Reset()         { *m = EnsurePodRequest{} }
func (m *EnsurePodRequest) String() string { return proto.CompactTextString(m) }
func (*EnsurePodRequest) ProtoMessage()    {}
func (*EnsurePodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{5}
}
func (m *EnsurePodRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnsurePodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EnsurePodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnsurePodRequest.Merge(m, src)
}
func (m *EnsurePodRequest) XXX_Size() int {
	return m.Size()
}
func (m *EnsurePodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnsurePodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnsurePodRequest proto.InternalMessageInfo

// EnsurePodResponse is empty and indicates that the server processed the
// request.
type EnsurePodResponse struct {
}

func (m *EnsurePodResponse) Reset()         { *m = EnsurePodResponse{} }
func (m *EnsurePodResponse) String() string { return proto.CompactTextString(m) }
func (*EnsurePodResponse) ProtoMessage()    {}
func (*EnsurePodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{6}
}
func (m *EnsurePodResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnsurePodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EnsurePodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnsurePodResponse.Merge(m, src)
}
func (m *EnsurePodResponse) XXX_Size() int {
	return m.Size()
}
func (m *EnsurePodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnsurePodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnsurePodResponse proto.InternalMessageInfo

// Tenant contains information about a tenant, such as its name and ID.
// Fields are optional except TenantID and Version.
type Tenant struct {
	// TenantID identifies the tenant.
	TenantID uint64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Version represents the version of the tenant resource. This will be used
	// to compare inequalities when determining which object is more up-to-date.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// ClusterName is the name of the tenant's cluster.
	ClusterName string `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// AllowedCIDRRanges corresponds to the list of source CIDR ranges that are
	// allowed to access the tenant. By default, if there are no rules, the proxy
	// will block all public connections.
	AllowedCIDRRanges []string `protobuf:"bytes,5,rep,name=allowed_cidr_ranges,json=allowedCidrRanges,proto3" json:"allowed_cidr_ranges,omitempty"`
	// AllowedPrivateEndpoints corresponds to the list of endpoint identifiers
	// that are allowed to access the tenant. By default, if there are no rules,
	// the proxy will block all private connections.
	AllowedPrivateEndpoints []string `protobuf:"bytes,6,rep,name=allowed_private_endpoints,json=allowedPrivateEndpoints,proto3" json:"allowed_private_endpoints,omitempty"`
}

func (m *Tenant) Reset()         { *m = Tenant{} }
func (m *Tenant) String() string { return proto.CompactTextString(m) }
func (*Tenant) ProtoMessage()    {}
func (*Tenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{7}
}
func (m *Tenant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Tenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tenant.Merge(m, src)
}
func (m *Tenant) XXX_Size() int {
	return m.Size()
}
func (m *Tenant) XXX_DiscardUnknown() {
	xxx_messageInfo_Tenant.DiscardUnknown(m)
}

var xxx_messageInfo_Tenant proto.InternalMessageInfo

// GetTenantRequest is used by a client to request from the sever metadata
// related to a given tenant.
type GetTenantRequest struct {
	// TenantID identifies the tenant for which the metadata is being requested.
	TenantID uint64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (m *GetTenantRequest) Reset()         { *m = GetTenantRequest{} }
func (m *GetTenantRequest) String() string { return proto.CompactTextString(m) }
func (*GetTenantRequest) ProtoMessage()    {}
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{8}
}
func (m *GetTenantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GetTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantRequest.Merge(m, src)
}
func (m *GetTenantRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantRequest proto.InternalMessageInfo

// GetTenantResponse is sent back when a client requests metadata for a tenant.
type GetTenantResponse struct {
	// ClusterName is the name of the tenant's cluster.
	//
	// TODO(jaylim-crl): Remove this field once it is no longer used.
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// Tenant describes the tenant that is being requested.
	Tenant *Tenant `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (m *GetTenantResponse) Reset()         { *m = GetTenantResponse{} }
func (m *GetTenantResponse) String() string { return proto.CompactTextString(m) }
func (*GetTenantResponse) ProtoMessage()    {}
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{9}
}
func (m *GetTenantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GetTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantResponse.Merge(m, src)
}
func (m *GetTenantResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantResponse proto.InternalMessageInfo

// WatchTenantsRequest is empty as we want to get all notifications.
type WatchTenantsRequest struct {
}

func (m *WatchTenantsRequest) Reset()         { *m = WatchTenantsRequest{} }
func (m *WatchTenantsRequest) String() string { return proto.CompactTextString(m) }
func (*WatchTenantsRequest) ProtoMessage()    {}
func (*WatchTenantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{10}
}
func (m *WatchTenantsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WatchTenantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WatchTenantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchTenantsRequest.Merge(m, src)
}
func (m *WatchTenantsRequest) XXX_Size() int {
	return m.Size()
}
func (m *WatchTenantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchTenantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchTenantsRequest proto.InternalMessageInfo

// WatchTenantsResponse represents the tenant notifications that the server
// sends to its clients when clients want to monitor the directory server
// activity.
type WatchTenantsResponse struct {
	// Type represents the type of the event for the watch response.
	Type WatchEventType `protobuf:"varint,1,opt,name=type,proto3,enum=cockroach.sqlproxy.tenant.WatchEventType" json:"type,omitempty"`
	// Tenant describes the tenant which has been added, modified, or deleted.
	Tenant *Tenant `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (m *WatchTenantsResponse) Reset()         { *m = WatchTenantsResponse{} }
func (m *WatchTenantsResponse) String() string { return proto.CompactTextString(m) }
func (*WatchTenantsResponse) ProtoMessage()    {}
func (*WatchTenantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0185b9fa1e6d4797, []int{11}
}
func (m *WatchTenantsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WatchTenantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WatchTenantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchTenantsResponse.Merge(m, src)
}
func (m *WatchTenantsResponse) XXX_Size() int {
	return m.Size()
}
func (m *WatchTenantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchTenantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchTenantsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.sqlproxy.tenant.PodState", PodState_name, PodState_value)
	proto.RegisterEnum("cockroach.sqlproxy.tenant.WatchEventType", WatchEventType_name, WatchEventType_value)
	proto.RegisterType((*Pod)(nil), "cockroach.sqlproxy.tenant.Pod")
	proto.RegisterType((*ListPodsRequest)(nil), "cockroach.sqlproxy.tenant.ListPodsRequest")
	proto.RegisterType((*ListPodsResponse)(nil), "cockroach.sqlproxy.tenant.ListPodsResponse")
	proto.RegisterType((*WatchPodsRequest)(nil), "cockroach.sqlproxy.tenant.WatchPodsRequest")
	proto.RegisterType((*WatchPodsResponse)(nil), "cockroach.sqlproxy.tenant.WatchPodsResponse")
	proto.RegisterType((*EnsurePodRequest)(nil), "cockroach.sqlproxy.tenant.EnsurePodRequest")
	proto.RegisterType((*EnsurePodResponse)(nil), "cockroach.sqlproxy.tenant.EnsurePodResponse")
	proto.RegisterType((*Tenant)(nil), "cockroach.sqlproxy.tenant.Tenant")
	proto.RegisterType((*GetTenantRequest)(nil), "cockroach.sqlproxy.tenant.GetTenantRequest")
	proto.RegisterType((*GetTenantResponse)(nil), "cockroach.sqlproxy.tenant.GetTenantResponse")
	proto.RegisterType((*WatchTenantsRequest)(nil), "cockroach.sqlproxy.tenant.WatchTenantsRequest")
	proto.RegisterType((*WatchTenantsResponse)(nil), "cockroach.sqlproxy.tenant.WatchTenantsResponse")
}

func init() { proto.RegisterFile("sqlproxy/tenant/directory.proto", fileDescriptor_0185b9fa1e6d4797) }

var fileDescriptor_0185b9fa1e6d4797 = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0xd5, 0x5a, 0xb4, 0x23, 0x8e, 0x5c, 0x85, 0x5a, 0x27, 0x28, 0xa3, 0x03, 0xa5, 0xb0, 0x17,
	0xc5, 0x29, 0xa8, 0x40, 0x3d, 0xa5, 0xa8, 0x0f, 0x76, 0x48, 0x07, 0x6a, 0x5d, 0x46, 0x60, 0x95,
	0x06, 0xe8, 0x45, 0x60, 0xc8, 0x8d, 0x4c, 0x54, 0xe2, 0x52, 0xe4, 0xca, 0xad, 0xfe, 0xa0, 0x47,
	0xff, 0x40, 0x4f, 0xfd, 0x19, 0x1f, 0x03, 0xf4, 0x92, 0x93, 0xdb, 0xca, 0x5f, 0xd1, 0x5b, 0xc1,
	0x5d, 0x52, 0x96, 0x64, 0x94, 0x76, 0xda, 0x1b, 0x67, 0xf6, 0xbd, 0x99, 0x37, 0xbb, 0x33, 0x43,
	0x68, 0x26, 0xd3, 0x71, 0x14, 0xd3, 0x9f, 0xe7, 0x1d, 0x46, 0x42, 0x37, 0x64, 0x1d, 0x3f, 0x88,
	0x89, 0xc7, 0x68, 0x3c, 0x37, 0xa2, 0x98, 0x32, 0x8a, 0x1f, 0x79, 0xd4, 0xfb, 0x31, 0xa6, 0xae,
	0x77, 0x6a, 0xe4, 0x50, 0x43, 0x40, 0x1b, 0x0f, 0x46, 0x74, 0x44, 0x39, 0xaa, 0x93, 0x7e, 0x09,
	0x42, 0xa3, 0x39, 0xa2, 0x74, 0x34, 0x26, 0x1d, 0x6e, 0xbd, 0x9d, 0xbd, 0xeb, 0xb0, 0x60, 0x42,
	0x12, 0xe6, 0x4e, 0x22, 0x01, 0xd0, 0x7f, 0x47, 0x50, 0xee, 0x53, 0x1f, 0x3f, 0x01, 0x59, 0x04,
	0x1a, 0x06, 0xbe, 0xba, 0xd5, 0x42, 0x6d, 0xe9, 0x68, 0x77, 0x71, 0xd9, 0xac, 0x0c, 0xb8, 0xb3,
	0x67, 0x3a, 0x15, 0x71, 0xdc, 0xf3, 0x31, 0x06, 0xc9, 0xf5, 0xfd, 0x58, 0x45, 0x2d, 0xd4, 0x96,
	0x1d, 0xfe, 0x8d, 0x9f, 0xc3, 0x76, 0xc2, 0x5c, 0x46, 0xd4, 0x72, 0x0b, 0xb5, 0x6b, 0xdd, 0xcf,
	0x8c, 0x7f, 0x15, 0x6a, 0xf4, 0xa9, 0xff, 0x5d, 0x0a, 0x75, 0x04, 0x03, 0x9f, 0x40, 0x8d, 0x7f,
	0x0c, 0x72, 0x65, 0xea, 0x76, 0x0b, 0xb5, 0xab, 0xdd, 0x86, 0x21, 0xb4, 0x1b, 0xb9, 0x76, 0x63,
	0x89, 0x38, 0xaa, 0x5c, 0x5c, 0x36, 0x4b, 0xe7, 0x7f, 0x34, 0x91, 0xb3, 0xc1, 0xfd, 0x5a, 0xaa,
	0x48, 0xca, 0xb6, 0xfe, 0x15, 0xdc, 0x3f, 0x09, 0x12, 0xd6, 0xa7, 0x7e, 0xe2, 0x90, 0xe9, 0x8c,
	0x24, 0x6c, 0xbd, 0x40, 0x54, 0x54, 0xa0, 0x7e, 0x0c, 0xca, 0x35, 0x3b, 0x89, 0x68, 0x98, 0x10,
	0xdc, 0x05, 0x29, 0xa2, 0x7e, 0xa2, 0xa2, 0x56, 0xb9, 0x5d, 0xed, 0x6a, 0xc5, 0xf5, 0x39, 0x1c,
	0xab, 0x63, 0x50, 0xde, 0xb8, 0xcc, 0x3b, 0x5d, 0x91, 0xa1, 0x5b, 0x50, 0x5f, 0xf1, 0x65, 0xc1,
	0x9f, 0x41, 0x39, 0xa2, 0x42, 0xd5, 0xed, 0xb1, 0x53, 0xa8, 0x7e, 0x00, 0x8a, 0x15, 0x26, 0xb3,
	0x98, 0xa4, 0x9e, 0x8f, 0xaf, 0x70, 0x0f, 0xea, 0x2b, 0x74, 0xa1, 0x42, 0xff, 0x1b, 0xc1, 0x8e,
	0xc0, 0x7e, 0x44, 0x28, 0xac, 0xc2, 0xbd, 0x33, 0x12, 0x27, 0x01, 0x0d, 0x79, 0xdb, 0xc8, 0x4e,
	0x6e, 0xe2, 0xc7, 0xb0, 0xeb, 0x8d, 0x67, 0x09, 0x23, 0xf1, 0x30, 0x74, 0x27, 0xa2, 0x35, 0x64,
	0xa7, 0x9a, 0xf9, 0x6c, 0x77, 0x42, 0xb0, 0x05, 0x7b, 0xee, 0x78, 0x4c, 0x7f, 0x22, 0xfe, 0xd0,
	0x0b, 0xfc, 0x78, 0x18, 0xbb, 0xe1, 0x88, 0x24, 0xea, 0x76, 0xab, 0xdc, 0x96, 0x8f, 0x1e, 0x2e,
	0x2e, 0x9b, 0xf5, 0x43, 0x71, 0xfc, 0xa2, 0x67, 0x3a, 0x0e, 0x3f, 0x74, 0xea, 0x19, 0xe3, 0x45,
	0xe0, 0xc7, 0xc2, 0x85, 0xbf, 0x84, 0x47, 0x79, 0x98, 0x28, 0x0e, 0xce, 0x5c, 0x46, 0x86, 0x24,
	0xf4, 0x23, 0x1a, 0x84, 0x2c, 0x51, 0x77, 0xd2, 0x60, 0xce, 0xa7, 0x19, 0xa0, 0x2f, 0xce, 0xad,
	0xfc, 0x38, 0x6b, 0x98, 0x03, 0x50, 0x5e, 0x12, 0x26, 0xca, 0xfb, 0x0f, 0xf7, 0x39, 0x85, 0xfa,
	0x0a, 0x3d, 0x7b, 0xd5, 0xcd, 0xfa, 0xd1, 0xcd, 0xfa, 0x9f, 0xc3, 0x8e, 0x88, 0xc1, 0xef, 0xae,
	0xda, 0x7d, 0x5c, 0xf0, 0xf6, 0x59, 0xf4, 0x8c, 0xa0, 0x3f, 0x84, 0x3d, 0xde, 0x48, 0xc2, 0xbd,
	0xec, 0xaf, 0x73, 0x04, 0x0f, 0xd6, 0xfd, 0x99, 0x9a, 0x03, 0x90, 0xd8, 0x3c, 0x12, 0x2a, 0x6a,
	0xdd, 0x27, 0x05, 0x89, 0x38, 0xdd, 0x3a, 0x23, 0x21, 0x1b, 0xcc, 0x23, 0xe2, 0x70, 0xda, 0xff,
	0x50, 0xba, 0x7f, 0x0c, 0x95, 0x7c, 0xe6, 0x71, 0x15, 0xee, 0xbd, 0xb6, 0xbf, 0xb1, 0x5f, 0xbd,
	0xb1, 0x95, 0x52, 0x6a, 0x38, 0xaf, 0x6d, 0xbb, 0x67, 0xbf, 0x54, 0x10, 0xde, 0x85, 0x8a, 0xe9,
	0x1c, 0xf6, 0xb8, 0xb5, 0xc5, 0x2d, 0xeb, 0xc4, 0x1a, 0xa4, 0x56, 0xb9, 0x21, 0xfd, 0xf2, 0x9b,
	0x56, 0xda, 0x77, 0xa1, 0xb6, 0x2e, 0x0d, 0xd7, 0xe1, 0x13, 0xeb, 0x7b, 0xcb, 0x1e, 0x0c, 0xaf,
	0x63, 0xde, 0x87, 0xaa, 0x70, 0x1d, 0x9a, 0xa6, 0x65, 0x2a, 0x08, 0x63, 0xa8, 0x09, 0xc7, 0xb7,
	0xaf, 0xcc, 0xde, 0x71, 0xcf, 0x32, 0x95, 0xad, 0x6b, 0x1e, 0xcf, 0x61, 0x99, 0x79, 0x8a, 0xee,
	0xaf, 0x12, 0xc8, 0x66, 0xbe, 0x73, 0xb1, 0x07, 0x95, 0x7c, 0x0f, 0xe0, 0xfd, 0x82, 0x7a, 0x37,
	0x56, 0x4d, 0xe3, 0xe9, 0x9d, 0xb0, 0xd9, 0xbb, 0x9c, 0x82, 0xbc, 0x5c, 0x08, 0xf8, 0xe9, 0x6d,
	0xcf, 0xb2, 0x9a, 0xe6, 0xf3, 0xbb, 0x81, 0x45, 0x9e, 0x67, 0x08, 0xbf, 0x03, 0x79, 0x39, 0xf4,
	0x85, 0x99, 0x36, 0x37, 0x4b, 0x61, 0xa6, 0x1b, 0x7b, 0x24, 0xcd, 0xb3, 0x1c, 0x86, 0xc2, 0x3c,
	0x9b, 0x13, 0x57, 0x98, 0xe7, 0xe6, 0x7c, 0x4d, 0x61, 0x77, 0xb5, 0xd3, 0xb1, 0x71, 0xdb, 0x7d,
	0xac, 0x8f, 0x4a, 0xa3, 0x73, 0x67, 0x7c, 0x7e, 0x85, 0x47, 0xed, 0x8b, 0xbf, 0xb4, 0xd2, 0xc5,
	0x42, 0x43, 0xef, 0x17, 0x1a, 0xfa, 0xb0, 0xd0, 0xd0, 0x9f, 0x0b, 0x0d, 0x9d, 0x5f, 0x69, 0xa5,
	0xf7, 0x57, 0x5a, 0xe9, 0xc3, 0x95, 0x56, 0xfa, 0x21, 0x6b, 0xfa, 0xb7, 0x3b, 0xfc, 0xaf, 0xf5,
	0xc5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x35, 0xc8, 0x10, 0xa6, 0xd3, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirectoryClient is the client API for Directory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectoryClient interface {
	// ListPods is used to query the server for the list of all RUNNING and/or
	// DRAINING pods of a given tenant.
	ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error)
	// WatchPods gets a stream of tenant pod change notifications. Notifications
	// are sent when a tenant pod is created, destroyed, or modified. When
	// WatchPods is first called, it returns notifications for all existing pods.
	WatchPods(ctx context.Context, in *WatchPodsRequest, opts ...grpc.CallOption) (Directory_WatchPodsClient, error)
	// EnsurePod ensures that at least one of the given tenant's pod is in the
	// RUNNING state. If there is already a RUNNING pod, then the server doesn't
	// have to do anything. If there isn't a RUNNING pod, then the server must
	// either convert an existing DRAINING pod to a RUNNING pod, or else bring new
	// RUNNING pod up. If the requested tenant does not exist, EnsurePod returns a
	// GRPC NotFound error.
	EnsurePod(ctx context.Context, in *EnsurePodRequest, opts ...grpc.CallOption) (*EnsurePodResponse, error)
	// GetTenant is used to fetch the metadata of a specific tenant. If the tenant
	// does not exist, GetTenant returns a GRPC NotFound error.
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	// WatchTenants gets a stream of tenant metadata change notifications.
	// Notifications are sent when a tenant is created, modified, or destroyed.
	// When WatchTenants is first called, it returns notifications for all
	// existing tenants as synthetic EVENT_ADDED events.
	WatchTenants(ctx context.Context, in *WatchTenantsRequest, opts ...grpc.CallOption) (Directory_WatchTenantsClient, error)
}

type directoryClient struct {
	cc *grpc.ClientConn
}

func NewDirectoryClient(cc *grpc.ClientConn) DirectoryClient {
	return &directoryClient{cc}
}

func (c *directoryClient) ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error) {
	out := new(ListPodsResponse)
	err := c.cc.Invoke(ctx, "/cockroach.sqlproxy.tenant.Directory/ListPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryClient) WatchPods(ctx context.Context, in *WatchPodsRequest, opts ...grpc.CallOption) (Directory_WatchPodsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Directory_serviceDesc.Streams[0], "/cockroach.sqlproxy.tenant.Directory/WatchPods", opts...)
	if err != nil {
		return nil, err
	}
	x := &directoryWatchPodsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Directory_WatchPodsClient interface {
	Recv() (*WatchPodsResponse, error)
	grpc.ClientStream
}

type directoryWatchPodsClient struct {
	grpc.ClientStream
}

func (x *directoryWatchPodsClient) Recv() (*WatchPodsResponse, error) {
	m := new(WatchPodsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *directoryClient) EnsurePod(ctx context.Context, in *EnsurePodRequest, opts ...grpc.CallOption) (*EnsurePodResponse, error) {
	out := new(EnsurePodResponse)
	err := c.cc.Invoke(ctx, "/cockroach.sqlproxy.tenant.Directory/EnsurePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, "/cockroach.sqlproxy.tenant.Directory/GetTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryClient) WatchTenants(ctx context.Context, in *WatchTenantsRequest, opts ...grpc.CallOption) (Directory_WatchTenantsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Directory_serviceDesc.Streams[1], "/cockroach.sqlproxy.tenant.Directory/WatchTenants", opts...)
	if err != nil {
		return nil, err
	}
	x := &directoryWatchTenantsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Directory_WatchTenantsClient interface {
	Recv() (*WatchTenantsResponse, error)
	grpc.ClientStream
}

type directoryWatchTenantsClient struct {
	grpc.ClientStream
}

func (x *directoryWatchTenantsClient) Recv() (*WatchTenantsResponse, error) {
	m := new(WatchTenantsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DirectoryServer is the server API for Directory service.
type DirectoryServer interface {
	// ListPods is used to query the server for the list of all RUNNING and/or
	// DRAINING pods of a given tenant.
	ListPods(context.Context, *ListPodsRequest) (*ListPodsResponse, error)
	// WatchPods gets a stream of tenant pod change notifications. Notifications
	// are sent when a tenant pod is created, destroyed, or modified. When
	// WatchPods is first called, it returns notifications for all existing pods.
	WatchPods(*WatchPodsRequest, Directory_WatchPodsServer) error
	// EnsurePod ensures that at least one of the given tenant's pod is in the
	// RUNNING state. If there is already a RUNNING pod, then the server doesn't
	// have to do anything. If there isn't a RUNNING pod, then the server must
	// either convert an existing DRAINING pod to a RUNNING pod, or else bring new
	// RUNNING pod up. If the requested tenant does not exist, EnsurePod returns a
	// GRPC NotFound error.
	EnsurePod(context.Context, *EnsurePodRequest) (*EnsurePodResponse, error)
	// GetTenant is used to fetch the metadata of a specific tenant. If the tenant
	// does not exist, GetTenant returns a GRPC NotFound error.
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	// WatchTenants gets a stream of tenant metadata change notifications.
	// Notifications are sent when a tenant is created, modified, or destroyed.
	// When WatchTenants is first called, it returns notifications for all
	// existing tenants as synthetic EVENT_ADDED events.
	WatchTenants(*WatchTenantsRequest, Directory_WatchTenantsServer) error
}

// UnimplementedDirectoryServer can be embedded to have forward compatible implementations.
type UnimplementedDirectoryServer struct {
}

func (*UnimplementedDirectoryServer) ListPods(ctx context.Context, req *ListPodsRequest) (*ListPodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPods not implemented")
}
func (*UnimplementedDirectoryServer) WatchPods(req *WatchPodsRequest, srv Directory_WatchPodsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchPods not implemented")
}
func (*UnimplementedDirectoryServer) EnsurePod(ctx context.Context, req *EnsurePodRequest) (*EnsurePodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsurePod not implemented")
}
func (*UnimplementedDirectoryServer) GetTenant(ctx context.Context, req *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (*UnimplementedDirectoryServer) WatchTenants(req *WatchTenantsRequest, srv Directory_WatchTenantsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchTenants not implemented")
}

func RegisterDirectoryServer(s *grpc.Server, srv DirectoryServer) {
	s.RegisterService(&_Directory_serviceDesc, srv)
}

func _Directory_ListPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).ListPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cockroach.sqlproxy.tenant.Directory/ListPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).ListPods(ctx, req.(*ListPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Directory_WatchPods_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPodsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DirectoryServer).WatchPods(m, &directoryWatchPodsServer{stream})
}

type Directory_WatchPodsServer interface {
	Send(*WatchPodsResponse) error
	grpc.ServerStream
}

type directoryWatchPodsServer struct {
	grpc.ServerStream
}

func (x *directoryWatchPodsServer) Send(m *WatchPodsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Directory_EnsurePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsurePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).EnsurePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cockroach.sqlproxy.tenant.Directory/EnsurePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).EnsurePod(ctx, req.(*EnsurePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Directory_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cockroach.sqlproxy.tenant.Directory/GetTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Directory_WatchTenants_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTenantsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DirectoryServer).WatchTenants(m, &directoryWatchTenantsServer{stream})
}

type Directory_WatchTenantsServer interface {
	Send(*WatchTenantsResponse) error
	grpc.ServerStream
}

type directoryWatchTenantsServer struct {
	grpc.ServerStream
}

func (x *directoryWatchTenantsServer) Send(m *WatchTenantsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Directory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cockroach.sqlproxy.tenant.Directory",
	HandlerType: (*DirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPods",
			Handler:    _Directory_ListPods_Handler,
		},
		{
			MethodName: "EnsurePod",
			Handler:    _Directory_EnsurePod_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _Directory_GetTenant_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPods",
			Handler:       _Directory_WatchPods_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTenants",
			Handler:       _Directory_WatchTenants_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sqlproxy/tenant/directory.proto",
}

func (m *Pod) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pod) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pod) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StateTimestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StateTimestamp):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintDirectory(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	if m.State != 0 {
		i = encodeVarintDirectory(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x18
	}
	if m.TenantID != 0 {
		i = encodeVarintDirectory(dAtA, i, uint64(m.TenantID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintDirectory(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListPodsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPodsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListPodsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TenantID != 0 {
		i = encodeVarintDirectory(dAtA, i, uint64(m.TenantID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ListPodsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPodsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListPodsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pods) > 0 {
		for iNdEx := len(m.Pods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDirectory(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *WatchPodsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WatchPodsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WatchPodsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *WatchPodsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WatchPodsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WatchPodsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pod != nil {
		{
			size, err := m.Pod.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDirectory(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EnsurePodRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnsurePodRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnsurePodRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TenantID != 0 {
		i = encodeVarintDirectory(dAtA, i, uint64(m.TenantID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EnsurePodResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnsurePodResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnsurePodResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Tenant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tenant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tenant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedPrivateEndpoints) > 0 {
		for iNdEx := len(m.AllowedPrivateEndpoints) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedPrivateEndpoints[iNdEx])
			copy(dAtA[i:], m.AllowedPrivateEndpoints[iNdEx])
			i = encodeVarintDirectory(dAtA, i, uint64(len(m.AllowedPrivateEndpoints[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.AllowedCIDRRanges) > 0 {
		for iNdEx := len(m.AllowedCIDRRanges) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedCIDRRanges[iNdEx])
			copy(dAtA[i:], m.AllowedCIDRRanges[iNdEx])
			i = encodeVarintDirectory(dAtA, i, uint64(len(m.AllowedCIDRRanges[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ClusterName) > 0 {
		i -= len(m.ClusterName)
		copy(dAtA[i:], m.ClusterName)
		i = encodeVarintDirectory(dAtA, i, uint64(len(m.ClusterName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintDirectory(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x12
	}
	if m.TenantID != 0 {
		i = encodeVarintDirectory(dAtA, i, uint64(m.TenantID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetTenantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTenantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTenantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TenantID != 0 {
		i = encodeVarintDirectory(dAtA, i, uint64(m.TenantID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetTenantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTenantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTenantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Tenant != nil {
		{
			size, err := m.Tenant.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDirectory(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClusterName) > 0 {
		i -= len(m.ClusterName)
		copy(dAtA[i:], m.ClusterName)
		i = encodeVarintDirectory(dAtA, i, uint64(len(m.ClusterName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WatchTenantsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WatchTenantsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WatchTenantsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *WatchTenantsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WatchTenantsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WatchTenantsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Tenant != nil {
		{
			size, err := m.Tenant.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDirectory(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintDirectory(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDirectory(dAtA []byte, offset int, v uint64) int {
	offset -= sovDirectory(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pod) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovDirectory(uint64(l))
	}
	if m.TenantID != 0 {
		n += 1 + sovDirectory(uint64(m.TenantID))
	}
	if m.State != 0 {
		n += 1 + sovDirectory(uint64(m.State))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StateTimestamp)
	n += 1 + l + sovDirectory(uint64(l))
	return n
}

func (m *ListPodsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TenantID != 0 {
		n += 1 + sovDirectory(uint64(m.TenantID))
	}
	return n
}

func (m *ListPodsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pods) > 0 {
		for _, e := range m.Pods {
			l = e.Size()
			n += 1 + l + sovDirectory(uint64(l))
		}
	}
	return n
}

func (m *WatchPodsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *WatchPodsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pod != nil {
		l = m.Pod.Size()
		n += 1 + l + sovDirectory(uint64(l))
	}
	return n
}

func (m *EnsurePodRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TenantID != 0 {
		n += 1 + sovDirectory(uint64(m.TenantID))
	}
	return n
}

func (m *EnsurePodResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Tenant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TenantID != 0 {
		n += 1 + sovDirectory(uint64(m.TenantID))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovDirectory(uint64(l))
	}
	l = len(m.ClusterName)
	if l > 0 {
		n += 1 + l + sovDirectory(uint64(l))
	}
	if len(m.AllowedCIDRRanges) > 0 {
		for _, s := range m.AllowedCIDRRanges {
			l = len(s)
			n += 1 + l + sovDirectory(uint64(l))
		}
	}
	if len(m.AllowedPrivateEndpoints) > 0 {
		for _, s := range m.AllowedPrivateEndpoints {
			l = len(s)
			n += 1 + l + sovDirectory(uint64(l))
		}
	}
	return n
}

func (m *GetTenantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TenantID != 0 {
		n += 1 + sovDirectory(uint64(m.TenantID))
	}
	return n
}

func (m *GetTenantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClusterName)
	if l > 0 {
		n += 1 + l + sovDirectory(uint64(l))
	}
	if m.Tenant != nil {
		l = m.Tenant.Size()
		n += 1 + l + sovDirectory(uint64(l))
	}
	return n
}

func (m *WatchTenantsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *WatchTenantsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovDirectory(uint64(m.Type))
	}
	if m.Tenant != nil {
		l = m.Tenant.Size()
		n += 1 + l + sovDirectory(uint64(l))
	}
	return n
}

func sovDirectory(x uint64) (n int) {
	return int((uint32(math_bits.Len64(x|1)+6) * 37) >> 8)
}
func sozDirectory(x uint64) (n int) {
	return sovDirectory(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pod) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pod: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pod: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantID", wireType)
			}
			m.TenantID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenantID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= PodState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StateTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPodsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPodsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPodsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantID", wireType)
			}
			m.TenantID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenantID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPodsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPodsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPodsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pods = append(m.Pods, &Pod{})
			if err := m.Pods[len(m.Pods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WatchPodsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WatchPodsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WatchPodsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WatchPodsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WatchPodsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WatchPodsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pod == nil {
				m.Pod = &Pod{}
			}
			if err := m.Pod.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnsurePodRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnsurePodRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnsurePodRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantID", wireType)
			}
			m.TenantID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenantID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnsurePodResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnsurePodResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnsurePodResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tenant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tenant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tenant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantID", wireType)
			}
			m.TenantID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenantID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedCIDRRanges", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedCIDRRanges = append(m.AllowedCIDRRanges, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedPrivateEndpoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedPrivateEndpoints = append(m.AllowedPrivateEndpoints, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTenantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTenantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTenantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantID", wireType)
			}
			m.TenantID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenantID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTenantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTenantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTenantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tenant == nil {
				m.Tenant = &Tenant{}
			}
			if err := m.Tenant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WatchTenantsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WatchTenantsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WatchTenantsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WatchTenantsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WatchTenantsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WatchTenantsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= WatchEventType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDirectory
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDirectory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tenant == nil {
				m.Tenant = &Tenant{}
			}
			if err := m.Tenant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDirectory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDirectory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDirectory(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDirectory
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDirectory
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDirectory
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDirectory
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDirectory
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDirectory        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDirectory          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDirectory = fmt.Errorf("proto: unexpected end of group")
)

